### ISSUE TITLE
what's the meaning of the CYCLES_TO_BUFFER

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/models#10082]
hi,dear
In training NCF , I find the word [here](https://github.com/tensorflow/models/blob/master/official/recommendation/constants.py#L67), but I do not know what does it mean ,
could you pls help me ?

thx

**Comment by laxmareddyp** [comment]
Hi @ucasiggcas,

This plotform is not for supporting Q&A. Please use the [Tensorflow Forum](https://discuss.tensorflow.org/) and [Stack overflow](https://stackoverflow.com/) for your Q&A.

Please use the below template for raising any issues.

The entire URL of the gist file you are using
Describe the bug
Steps to reproduce
Expected behavior
Additional context
System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device name if the issue happens on a mobile device:
TensorFlow installed from (source or binary):
TensorFlow version (use command below):
Python version:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
