### ISSUE TITLE
Enable Serialization of BertTokenizer

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/models#10115]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [ X ] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/nlp/modeling/layers/text_layers.py

## 2. Describe the feature you request

The BertTokenizer appears to wrap the tf text tokenization to enable being used in a Keras Layer.  This trains, but does not serialize.  This feature request is to ensure that these layers are serializable via Keras.

## 3. Additional context
One of the issues is at https://github.com/tensorflow/models/blob/master/official/nlp/modeling/layers/text_layers.py#L277 .

I created a stand alone test case at https://colab.research.google.com/drive/1fuoFmp2AhU_jGlQk-ZL1uQXjBIOxQ02v?usp=sharing .

## 4. Are you willing to contribute it? (Yes or No)
No.

**Comment by laxmareddyp** [comment]
Hi @jeisinge,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.
The TF models official team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tf-models-official/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/models/releases/tag/v2.13.1) to stay up to date with the latest developments which are happening in the TF models official space.

**Comment by jeisinge** [comment]
Thanks for reaching out. I just tired again with the latest Tensorflow as you recommended. Unfortunately, the defect still exists.

With that being said, we found work arounds with KerasNLP, so feel free to close it out if a fix is not high priority.

**Comment by grep-mb** [comment]
@jeisinge would it be possible for you to share the workwround?

**Comment by jeisinge** [comment]
We created two models --- one for preprocessing (not trained, CPU) and one for the model (GPU, trained).  And, then with Triton, we orchestrate them at inference time.

**Comment by grep-mb** [comment]
@jeisinge thanks!
