### ISSUE TITLE
YAMNet for microcontrollers?

### ISSUE THREAD

**Issue by jake-is-ESD-protected** [tensorflow/models#10241]
After days of research and no success I'll try to grab the problem at it's root and ask directly:

### Can YAMNet be ported to microcontrollers such as Arduino, STM32xx, ESP32?

A similar question has been asked [here](https://github.com/tensorflow/models/issues/9693), but with a non-general answer. As of now, passing the the official .tflite-model to the STM CubeIDE with X Cube AI results in the message 
"NOT IMPLEMENTED: Shape with 1 dimensions not supported: (15600, )", 
which of course is ST's problem, but still: is it possible, in general, at least on other platforms? What does one have to do to run YAMNet on a mc? Is there even enough memory?

I hope anybody looking to do the same thing can receive either a clear "NO" or "YES" in an answer provided from someone involved in the YAMNet development.

**Comment by plakal** [comment]
I'll repeat what I said in issue #10235 

"""
We have released a couple of different TF-Lite versions of YAMNet on TF-Hub:

https://tfhub.dev/google/lite-model/yamnet/tflite/1 is an unmodified TF-Lite conversion of YAMNet that accepts variable-length float32 samples as input. This uses the model exporter code from our GitHub repo.

https://tfhub.dev/google/lite-model/yamnet/classification/tflite/1 is a quantized TF-Lite conversion with a simpler signature that accepts a fixed-length 0.975s waveform as input (15600 samples @ 16 kHz). The model is slightly different (Relu6 instead of Relu, to support quantization) and should be more efficient on mobile devices.
"""

In particular, the quantized model can run via TF-Lite on a mobile device or on an Edge TPU (see the "Coral" version of the model on TF-Hub). We have not tried running the model with any microcontrollers and we don't have any plans for doing so in the near future, so the answer is neither "yes" nor "no" but more like "don't know". You would probably have to start with the quantized model and then explore to find out how to make it run. Sorry we can't be any more help at the moment.

**Comment by dpwe** [comment]
I have an idea about this.  I made a test version of yamnet/export.py that exports a 4th model, `tflite_fixed`.  This tflite model accepts *exactly* 15600 samples, and generates *exactly* one frame of output (for scores and embeddings, and a 96x64 spectrogram).  This removes `unknown` dimensions in the model, which should make it easier to compile for special hardware.  It also simplifies the input part of the graph.

https://github.com/tensorflow/models/blob/yamnet_fixed_length_tflite/research/audioset/yamnet/export.py

However, it will now fall on the calling code to segment the input waveform into stretches of exactly 15,600 samples.  To get the same 10 Hz classification cadence of the standard model, this means advancing by 160 samples between each successive call.

**Comment by jake-is-ESD-protected** [comment]
That answers it, thanks. I might have run into memory issues anyways because of the model's size.

**Comment by almirfilho77** [comment]
> I'll repeat what I said in issue #10235
> 
> """ We have released a couple of different TF-Lite versions of YAMNet on TF-Hub:
> 
> https://tfhub.dev/google/lite-model/yamnet/tflite/1 is an unmodified TF-Lite conversion of YAMNet that accepts variable-length float32 samples as input. This uses the model exporter code from our GitHub repo.
> 
> https://tfhub.dev/google/lite-model/yamnet/classification/tflite/1 is a quantized TF-Lite conversion with a simpler signature that accepts a fixed-length 0.975s waveform as input (15600 samples @ 16 kHz). The model is slightly different (Relu6 instead of Relu, to support quantization) and should be more efficient on mobile devices. """
> 
> In particular, the quantized model can run via TF-Lite on a mobile device or on an Edge TPU (see the "Coral" version of the model on TF-Hub). We have not tried running the model with any microcontrollers and we don't have any plans for doing so in the near future, so the answer is neither "yes" nor "no" but more like "don't know". You would probably have to start with the quantized model and then explore to find out how to make it run. Sorry we can't be any more help at the moment.

Hello, could you please tell me the minimum TFLite version that can load the quantized model?
