### ISSUE TITLE
Request for TPU compatible pipeline_config for Mask-RCNN model training.

### ISSUE THREAD

**Issue by mhs-achyut** [tensorflow/models#10380]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [*] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 2. Describe the feature you request

There is no TPU compatible pipeline config file for the maskRCNN model given by the repo. As this is an official model, I would like to request a pipeline config for TPU training.

## 3. Additional context

Add any other context about the feature request here.

## 4. Are you willing to contribute it? (Yes or No)

Yes, I need some guidance.

**Comment by saberkun** [comment]
Yes, TPU is well supported.
Please read: https://github.com/tensorflow/models/blob/master/official/vision/beta/MODEL_GARDEN.md#object-detection-and-instance-segmentation
@xianzhidu @allenwang28 for instructions

**Comment by allenwang28** [comment]
Hi,

Please take a look at the [maskrcnn_resnetfpn_coco](https://github.com/tensorflow/models/blob/master/official/vision/beta/configs/maskrcnn.py#L292-L355) config.

You can do some standard Cloud TPU setup similar to [the Cloud TPU ResNet-RS tutorial](https://cloud.google.com/tpu/docs/tutorials/resnet-rs-2.x).

Your train command might look like this (running on a v3-32, you'll need to modify the config file if you want to use a different TPU size):
```
python3 /usr/share/models/official/vision/beta/train.py \
  --experiment=maskrcnn_resnetfpn_coco \
  --mode=train_and_eval \
  --model_dir=$MODEL_DIR \
  --tpu=$TPU_NAME \
  --config_file=/usr/share/models/official/vision/beta/configs/experiments/maskrcnn/r50fpn_640_coco_scratch_tpu4x4.yaml \
  --params_override="task.train_data.input_path=${PATH_TO_TRAIN_DATA}, task.validation_data.input_path=${PATH_TO_EVAL_DATA}, task.annotation_file=${PATH_TO_ANNOTATION_FILE}"
```

We additionally have instructions for the legacy Mask RCNN binary (including data setup) which you can see [here](https://cloud.google.com/tpu/docs/tutorials/mask-rcnn-2.x#prepare-coco).

The legacy models are in the process of being deprecated, the most stable thing to try would be using TF2.7.0 (for VM/TPU/github branch) rather than nightly/master.
