### ISSUE TITLE
EfficientNet for Semantic Segmentation in TensorFlow

### ISSUE THREAD

**Issue by mradul2** [tensorflow/models#10401]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://arxiv.org/abs/1606.02147

## 2. Describe the feature you request

I want to contribute a new research paper code for the work: `ENet: A Deep Neural Network Architecture for Real-Time Semantic Segmentation`

## 3. Additional context

Efficient Net is a neural network architecture particularly for real-time semantic segmentation, and I plan to implement the model in Tensorflow 2, and also reproduce the baseline results the original paper provides on the CityScapes dataset. Along with publishing the pre-trained model on [TensorFlow Hub](https://tfhub.dev/).

## 4. Are you willing to contribute it? (Yes or No)
Yes

**Comment by innat** [comment]
It would be better to have these models within the high-level API like [keras-CV](https://github.com/keras-team/keras-cv). This `tensorflow/models` is too messy to work with (IMHO).

**Comment by mradul2** [comment]
Sure, can you guide me through that? I could not find appropriate contribution guidelines for keras-CV.

**Comment by innat** [comment]
@mradul2 
Please check this update list about [contributions](https://github.com/keras-team/keras/pull/15447). AFAIK, we may get some updates about keras-cv soon, [source](https://github.com/keras-team/keras/issues/15545#issuecomment-954902928). IMO, if you maintain ENet in your own repo and contribute to `keras.application` when the time comes, that would be really good.

**Comment by laxmareddyp** [comment]
Hi @mradul2,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.
The TF models official team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tf-models-official/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/models/releases/tag/v2.13.1) to stay up to date with the latest developments which are happening in the TF models official space.
