### ISSUE TITLE
MoViNets trained on Epic Kitchens 100

### ISSUE THREAD

**Issue by ezius07** [tensorflow/models#10451]
Could you please provide also models trained on Epic Kitchens 100 as Table 15 in [1].
It would be really important in order to have a comparison for our future works.
@Hyperparticle 
@yuanliangzhe 
@yeqingli 
Kind regards.

[1] MoViNets: Mobile Video Networks for Efficient Video Recognition

**Comment by laxmareddyp** [comment]
Hi @luotigerlsx @fyangf,

Please look into this issue whenever you have some time.

Thanks.

**Comment by laxmareddyp** [comment]
Hi @DianeBouchacourt,

Thank you for opening this issue. Since this issue has been open for a long time and once the team provides above requested models on Epic Kitchens 100 data set, you can see in the latest release notes.The TF models official team is constantly improving the framework by fixing bugs and adding new features. Please follow the [release notes](https://github.com/tensorflow/models/releases/tag/v2.13.1) to stay up to date with the latest developments which are happening in the TF models official space.
