### ISSUE TITLE
Utilise 100% GPU resource for YOLO v3 detection using TensorFlow

### ISSUE THREAD

**Issue by Shubham-cat4** [tensorflow/models#10538]
My System Configuration : I'm working on a Yolov3 model with GeForce RTX 2080 Ti GPU with 11 GB GPU memory and Intel (R) Core (TM) i9-9900KF CPU with 6 cores and 64GB of RAM.

When i inference on images, my average FPS is between 35 FPS and GPU utilisation is 1128MiB (~1GB out of 11GB). I use TensorFlow and convert + loading the yolov3 model on the GPU

I am able to increase the volume of image inference by running the same setup in 6 instances and I am able to achieve 210 FPS and GPU utilisation is 6760MiB (~6GB out of 11GB). However, this method requires me to separate the images and feed non duplicate entries to each of the 6 instances.

How do I run a single instance that utilises the full GPU so I can extract the best FPS from all the 11 GB of GPU.

**Comment by laxmareddyp** [comment]
Hi @Shubham-cat4,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.
The TF models official team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tf-models-official/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/models/releases/tag/v2.13.1) to stay up to date with the latest developments which are happening in the TF models official space.
