### ISSUE TITLE
inference image preprocessing

### ISSUE THREAD

**Issue by dacquaviva** [tensorflow/models#10571]
Hello all!

I am using a pretrained Object detection API models ([SSD MobileNet V2 FPNLite 320x320](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8.tar.gz).) and I have doubts regarding image preprocessing, I tried to look up the doc but couldn't find anything about it.

 - When using tensorflow `tf.saved_model.load(path_model)` to make inference using the above mentioned model (SSD MobileNet V2 FPNLite 320x320) do I need to resize my input image to 300x300 and scale it [-1,1] or will the model do it for me?

- When converting the above mentioned model (SSD MobileNet V2 FPNLite 320x320) to tfLite will the model also resize the image to 300x300 and scale it to [-1,1] or do I need to do it beforehand for example using cv2 and numpy (I tried passing the raw image however I get error therefore I believe I need to do the preprocessing myself).

Thanks!

**Comment by sushreebarsa** [comment]
@dacquaviva Sorry for the late response!
Please find the reference [here](https://www.tensorflow.org/lite/examples/object_detection/overview) and let us know if it helps? 
In order to expedite the trouble-shooting process, could you please provide the entire URL of the repository which you are using. Please provide more details on the issue reported here. Thank you!
