### ISSUE TITLE
Cannot reproduce results of ptb_word_lm.py

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/models#1057]
The scores mentioned in tutorials/rnn/ptb_word_lm.py cannot be reproduced.
The claimed score is:

| config | epochs | train | valid  | test
|------- |----------| ------------|-------|--------|
| medium | 39     | 48.45 |  86.16 |  82.07

I ran the command `python ptb_word_lm.py --data_path=simple-examples/data/ --model medium` for 10 times, and get the following results at 39th epoch:

|train|valid|test
|----|----|----|
|45.746|87.345|83.916|
|45.779|87.408|83.933|
|45.675|87.616|83.919|
|45.442|87.883|83.804|
|45.531|87.399|83.849|
|45.730|87.757|83.553|
|45.607|87.520|83.962|
|45.639|87.485|83.752|
|45.597|87.686|83.715|
|45.609|87.716|83.721|

Ran with tensorflow1.0.

**Comment by tatatodd** [comment]
Note this line immediately after the table:
**The exact results may vary depending on the random initialization.**

Although it's not clear to me that random init is the main factor at play here.

This question might be better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since I don't think it is a  bug or feature request. There is also a larger community that reads questions there. Thanks!

If you do feel there is a bug, feel free to respond to this issue and I'll re-open it.

**Comment by ppwwyyxx** [comment]
I ran it 10 times to avoid the variance caused by random initialization.

Also I think "failed to meet the claimed performance" is a bug.
