### ISSUE TITLE
GPU utilization suddenly dropped by 0

### ISSUE THREAD

**Issue by Massacre96Wj** [tensorflow/models#10803]
tf2.6
gpu=3

Start normal training. At a certain steps, the GPU utilization drops to 0. It is suspected that reading data is blocked. I don’t know if the suspicion is correct and how to deal with it.

**Comment by laxmareddyp** [comment]
Hi @Massacre96Wj,

Could you please help me with more information about the System Info, GPU details and the data size that you are trying to read?

Please use the below template for raising any issues.

**1. The entire URL of the gist file you are using**
**2. Describe the bug**
**3. Steps to reproduce**
**4. Expected behavior**
**5. Additional context**
**##6. System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
