### ISSUE TITLE
cifar10 example should not untar the dataset every time.

### ISSUE THREAD

**Issue by zym1010** [tensorflow/models#1083]
As shown in <https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10.py#L398>, currently, whenever any of `cifar10_train`, `cifar10_eval`, or `	cifar10_multi_gpu_train` is executed, the dataset file will be untarred unconditionally. This causes that one cannot run eval and train scripts simultaneously, as discussed in #892. 

Originally this was not the case, and the change was made in tensorflow/tensorflow#5145, for some other reason.

**Comment by tatatodd** [comment]
@zym1010 Thanks for filing the issue!  I agree that the change in tensorflow/tensorflow#5145 was a regression in this regard.  But rather than reverting that change, it should be possible to add an additional check to not untar if the untarring had previously succeeded.

Would you like to send a PR to do this?  We welcome contributions!

**Comment by zym1010** [comment]
@tatatodd alright! will do it this week.

**Comment by zym1010** [comment]
@tatatodd I have made my PR #1112

**Comment by tatatodd** [comment]
@caisq Can you take a look?

Also, note that this is in the tensorflow/models repo.  I can't assign this issue or the PR to you; perhaps you need to update your github projects?
