### ISSUE TITLE
VGGish model

### ISSUE THREAD

**Issue by bogeng-song** [tensorflow/models#10908]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ 1] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/audioset/vggish

## 2. Describe the bug

I set up tensorflow and other packages and try to run test session, which is vggish_smoke_test.py, and I also run the code on colab, but the script go with error, which says 'Mismatched elements: 1 / 2 (50%) ... ' could you tell where is the error from? 

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by JakeNewmanUEA** [comment]
I have the same issue. It would be good to know if this mismatch between calculated and expected embeddings is because the expected embeddings are wrong (and the calculated values are correct).

**Comment by ValBaron10** [comment]
+1 : the vggish_smoke_test script does not work on my machine (neither with tensorflow 2 nor with tensorflow 1.14 because I saw afterwards that tensorflow 2 was not supported) and it does work neither on the Google Colab (same error as described in the issue above, the first assertion is not verified, the expected mean value for the embedding vector does not correspond to the actual computed value).
@plakal and @dpwe can we have a guess from you about what is going on?
Thanks
