### ISSUE TITLE
word2vec.py is not compatible with the latest tensorflow (1.0.0)

### ISSUE THREAD

**Issue by vaskonov** [tensorflow/models#1092]
## Please let us know which model this issue is about (specify the top-level directory)
The issue is about embedding. 

The word2vec.py script is not compatible with the latest tensorflow (1.0.0). When you try to run it as in tutorial it fails with the following error message:

```
true_logits = tf.reduce_sum(tf.mul(example_emb, true_w), 1) + true_b
AttributeError: 'module' object has no attribute 'mul'
```
The error occurs because of the changes in the latest version of tensorflow 

> tf.mul, tf.sub and tf.neg are deprecated in favor of tf.multiply, tf.subtract and tf.negative.

After renaming the deprecated methods the script  successfully builds the model, however when you open the word embeddings in tensorboard it shows up with indexes instead of words. It looks like either the log or tensorboard fails to map the indexes into the words.

**Comment by tatatodd** [comment]
@nealwu Can you investigate?  It looks like the github version of word2vec.py isn't in sync with our internal version, which might be due to your PR https://github.com/tensorflow/models/commit/86ecc9730d751c1f72e3bfecac958166390f4125

(Compare the github version with our internal version)
https://github.com/tensorflow/models/blob/master/tutorials/embedding/word2vec.py

**Comment by nealwu** [comment]
Yep, it's not in sync with our internal version because we don't have a sync process for this repo currently.

I do however have two pull requests that should help reduce the number of issues we have here. https://github.com/tensorflow/models/pull/1063 and https://github.com/tensorflow/models/pull/1053. Still need a review though, so feel free to review them. :)

**Comment by tatatodd** [comment]
Thanks @nealwu , I'll assign this to you so that you can update it once things are fixed.

**Comment by vaskonov** [comment]
@nealwu, @tatatodd guys, I wonder if I can make modifications by myself. I just want to help you.

**Comment by nealwu** [comment]
Hi @vaskonov, 1.0 compatibility should now be fixed by https://github.com/tensorflow/models/pull/1063. Let me know if you still have any issues there. Unfortunately, I'm not sure about the TensorBoard embedding issue. If you think it might be a bug in TensorBoard, you can ask https://github.com/dandelionmane.
