### ISSUE TITLE
Could not install packages due to an OSError: [Errno 39] Directory not empty: '/usr/local/lib/python3.8/dist-packages/flatbuffers/' 

### ISSUE THREAD

**Issue by SoftChamp** [tensorflow/models#10967]
While running train_model.ipynb file of object detection model using Tensorflow on SageMaker, below error is coming:

ERROR: Could not install packages due to an OSError: [Errno 39] Directory not empty: '/usr/local/lib/python3.8/dist-packages/flatbuffers/'

Please help in resolving this.

**Comment by laxmareddyp** [comment]
Hi @SoftChamp 

Sorry for the late response.

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) and [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks for understanding.
