### ISSUE TITLE
https://github.com/tensorflow/models/blob/master/docs/vision/object_detection.ipynb doesn't work

### ISSUE THREAD

**Issue by GlingK** [tensorflow/models#10972]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ ] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using
https://github.com/tensorflow/models/blob/master/docs/vision/object_detection.ipynb

## 2. Describe the bug

The notebook breaks @ Import required libraries from tensorflow models as image below

![image](https://user-images.githubusercontent.com/114388973/230285747-90e0b9d1-6b8b-49f7-962c-2233cc0d2489.png)

## 3. Steps to reproduce

Run the notebook in colab until section

> Import required libraries from tensorflow models as image below

## 4. Expected behavior

Should pass without errors

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

 2.12

**Comment by laxmareddyp** [comment]
Hi @GlingK,

Please restart runtime after `!pip install "tf-models-official` beacuse the colab doesn't have the new numpy version while doing `!pip install "tf-models-official` it downloads new numpy- version 1.23.5 which is why , need to restart the runtime after pip install.please find the attached [gist](https://colab.sandbox.google.com/gist/sineeli/f7ea1f9ac8ff0e95cb00f949cc008c29/object_detection.ipynb) which is executing properly.

Thanks.
