### ISSUE TITLE
TypeError: cross_entropy_loss(): argument 'target' (position 2) must be Tensor, not tuple

### ISSUE THREAD

**Issue by DanceElephant** [tensorflow/models#10992]
I used my own local data set, and have stored the data set information in the dictionary like cifar10, running the error: TypeError: cross_entropy_loss(): argument 'target' (position 2) must be Tensor, not tuple
The error location appears in torch\nn\functional.py
Could you help me with this question? Thank you very much

**Comment by laxmareddyp** [comment]
Hi @DanceElephant ,

It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/models/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
