### ISSUE TITLE
AttributeError: module 'pasta' has no attribute 'parse'

### ISSUE THREAD

**Issue by LiangYong1216** [tensorflow/models#10991]
when i run tf_upgrade_v2,the error occured ,my pasta version is 0.1,what should i do?

**Comment by laxmareddyp** [comment]
Hi @LiangYong1216 ,

It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/models/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
