### ISSUE TITLE
When I use tflite to detect,it gets error: select tensorflow op(s),included in the given model,is not supported by this interpreter.How to avoid select tensorflow op when training pb model

### ISSUE THREAD

**Issue by JieWade** [tensorflow/models#11007]
When I use tflite to detect,it gets error: select tensorflow op(s),included in the given model,is not supported by this interpreter.
how can I solve it.I used TF2 to train and transfer to tflite,and call on pi.
Addtionally,How to avoid select tensorflow op when training pb model.

**Comment by laxmareddyp** [comment]
Hi @JieWade,

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) and [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks for understanding.
