### ISSUE TITLE
import tensorflow_models as tfm

### ISSUE THREAD

**Issue by andysingal** [tensorflow/models#11018]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ ] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/...

## 3. Steps to reproduce

Steps to reproduce the behavior.

## 5. Additional context

Include any logs that would be helpful to diagnose the problem.

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-18-3b7de3fd28ed>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import tensorflow_models as tfm

4 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow_text/__init__.py](https://localhost:8080/#) in <module>
     18 
     19 # pylint: disable=wildcard-import
---> 20 from tensorflow_text.core.pybinds import tflite_registrar
     21 from tensorflow_text.python import keras
     22 from tensorflow_text.python import metrics

ImportError: /usr/local/lib/python3.10/dist-packages/tensorflow_text/core/pybinds/tflite_registrar.so: undefined symbol: _ZN4absl12lts_2022062320raw_logging_internal21internal_log_functionB5cxx11E

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by Dante-Berth** [comment]
I had the same error , you cannot use it because the directory didn't exist but you have to check in your lib directory if the directory official exists, it it the case you can import the layers you need from official.nlp.modeling.layers. 
In my case tensorflow_models was not created however official which is the tensorflow garden repository was created.  Just check what you have and you will be able to know if it caused by the installation.

**Comment by laxmareddyp** [comment]
Hi @andysingal,

To help resolve the issue more efficiently, could you kindly provide a code snippet that replicates the problem you're experiencing?

 Thank you!

**Comment by Dante-Berth** [comment]
Yesterday, i created a new env with Python 3.11.3 and install the latest version of tf and tensorflow garden ( the framework) but got exactly the same error than the author. As i said, tensorflow_model is a missing directory which was available in the previous versions. My new error is AttributeError: module 'keras.api._v2.keras.mixed_precision' has no attribute 'experimental' ( error is caused by theofficial\nlp\keras_nlp\layers\transformer_encoder_block.py", line 162, in build. I did not test my solution is to downgrade tensorflow and tensorflow garden. The authors was right the version is deprecated for the latest version of tensorflow (2.12>).

I share you the version of my tf packages related :
keras                         2.12.0
keras-nightly                 2.14.0.dev2023061107
tensorflow                    2.12.0
tensorflow-addons             0.20.0
tensorflow-datasets           4.9.2
tensorflow-estimator          2.12.0
tensorflow-hub                0.13.0
tensorflow-intel              2.12.0
tensorflow-io-gcs-filesystem  0.31.0
tensorflow-metadata           1.13.1
tensorflow-model-optimization 0.7.5
tf-estimator-nightly          2.14.0.dev2023060108
tf-models-nightly             2.4.0.dev20210111
tf-models-no-deps             2.11.2
tf-models-official            2.5.1
tf-nightly                    2.14.0.dev20230610
tf_nightly_intel              2.14.0.dev20230610
tf-slim                       1.1.0

**Comment by andysingal** [comment]
> Yesterday, i created a new env with Python 3.11.3 and install the latest version of tf and tensorflow garden ( the framework) but got exactly the same error than the author. As i said, tensorflow_model is a missing directory which was available in the previous versions. My new error is AttributeError: module 'keras.api._v2.keras.mixed_precision' has no attribute 'experimental' ( error is caused by theofficial\nlp\keras_nlp\layers\transformer_encoder_block.py", line 162, in build. I did not test my solution is to downgrade tensorflow and tensorflow garden. The authors was right the version is deprecated for the latest version of tensorflow (2.12>).
> 
> I share you the version of my tf packages related : keras 2.12.0 keras-nightly 2.14.0.dev2023061107 tensorflow 2.12.0 tensorflow-addons 0.20.0 tensorflow-datasets 4.9.2 tensorflow-estimator 2.12.0 tensorflow-hub 0.13.0 tensorflow-intel 2.12.0 tensorflow-io-gcs-filesystem 0.31.0 tensorflow-metadata 1.13.1 tensorflow-model-optimization 0.7.5 tf-estimator-nightly 2.14.0.dev2023060108 tf-models-nightly 2.4.0.dev20210111 tf-models-no-deps 2.11.2 tf-models-official 2.5.1 tf-nightly 2.14.0.dev20230610 tf_nightly_intel 2.14.0.dev20230610 tf-slim 1.1.0

Thanks, [laxmareddyp](https://github.com/laxmareddyp) i hope Dan example is suffice for your query

**Comment by Dante-Berth** [comment]
> Hi @Dante-Berth,
> 
> Installing `tf-models-official` will also install the latest version of TensorFlow by default, eliminating the need for a separate TensorFlow installation.
> 
> Regarding using `tf-models-official` and `tf-models-nightly` at the same time, conflicts may arise when trying to install both packages simultaneously. This is because they can have overlapping dependencies or conflicting version requirements. It's recommended to choose one package based on your specific requirements and stick to it.
> 
> If you decide to use `tf-models-nightly` , you can install it and be mindful of potential conflicts if you have other TensorFlow-related packages installed in your environment.
> 
> Thanks

Unfortuntately, i had unexpected errors such as the version of tensorflow-text which cannot be installed. Thanks you for your answers but i do not need the library, i used to the library for Transformers. But in my case, i need to create custom transformers. I just need Tensorflow.
