### ISSUE TITLE
Label Looks small in object detection 

### ISSUE THREAD

**Issue by MuhammadSaad-ml** [tensorflow/models#11037]
I am working on sign language detection project and its almost complete but when I detecting sign in real time the label with image looks small and I cannot see it clearly is there any way to make the label looks bigger 

OS :Mac OS 2012 
tf version:2.11
python 3.7

**Comment by Petros626** [comment]
show a screenshot dude, how should we imagine the result. Maybe it's just the line thickness of OpenCV draw function.

**Comment by laxmareddyp** [comment]
Hi @MuhammadSaad-ml ,


This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) and [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks for understanding.
