### ISSUE TITLE
Tensorflow2 Multi worker mirrored strategy is not scaling for GPUS 

### ISSUE THREAD

**Issue by sowmya04101998** [tensorflow/models#11042]
Hello all,
 I am using the  TensorFlow Model Garden release and TensorFlow 2.11 gpu
While executing Resnet50 code https://github.com/tensorflow/models/blob/master/official/legacy/image_classification/classifier_trainer.py , it was noticed that throughput doesn't increase even after running it on multinode multigpu in our cluster.

Steps followed

1)salloc --nodes=2  --time=20:00:00 --gres=gpu:2 --partition=gpu --exclusive 

 In gpu1

cd /home/cdacapp1/scaling/models-master/official/legacy/image_classification && \
export PYTHONPATH="$PYTHONPATH:/home/cdacapp1/scaling/models-master" && \
export DATA_DIR=/scratch/cdacapp1/sowmya/actual_imagenet/tf_records && \
export MODEL_DIR=/home/cdacapp1/scaling/models-master/official/legacy/image_classification/checkpointss && \
source /home/apps/anaconda3/bin/activate && \
conda activate tf11

python3 classifier_trainer.py --mode=train_and_eval --model_type=resnet --dataset=imagenet --model_dir=$MODEL_DIR --data_dir=$DATA_DIR  --config_file=configs/examples/resnet/imagenet/gpu.yaml

gpu.yaml consists of

runtime:
  distribution_strategy: 'multi_worker_mirrored'
  worker_hosts: 'ip1:6655,ip2:6655'
  num_gpus: 2
  task_index: 0

In gpu2

cd /home/cdacapp1/scaling/models-master/official/legacy/image_classification && \
export PYTHONPATH="$PYTHONPATH:/home/cdacapp1/scaling/models-master" && \
export DATA_DIR=/scratch/cdacapp1/sowmya/actual_imagenet/tf_records && \
export MODEL_DIR=/home/cdacapp1/scaling/models-master/official/legacy/image_classification/checkpointss && \
source /home/apps/anaconda3/bin/activate && \
conda activate tf11

python3 classifier_trainer.py --mode=train_and_eval --model_type=resnet --dataset=imagenet --model_dir=$MODEL_DIR --data_dir=$DATA_DIR  --config_file=configs/examples/resnet/imagenet/gpu1.yaml

gpu1.yaml consists of

runtime:
  distribution_strategy: 'multi_worker_mirrored'
  worker_hosts: 'ip1:6655,ip2:6655'
  num_gpus: 2
  task_index: 1

 System information
- OS Platform  centos 7):
- tensorflow-gpu 2.11.0
- Python version: 3.9.7
- CUDA/cuDNN version:
- GPU model and memory:Tesla V100-SXM2 with 16 GB memory with Driver Version: 450.51.05    CUDA Version: 11.0  

execution on single gpu is giving approx. 270 examples/sec and is scaling well on the gpus within the node giving approximately 700 samples/sec with 2 gpus in single node with mirrored strategy , However it is not scaling on different nodes ,the throughput is same as that of a single gpu , am i reading the logs wrong can you please guide me on this if I'm doing anything wrong .

**Comment by laxmareddyp** [comment]
Hi @luotigerlsx,

Can you please check this in your free time.

Thanks.

**Comment by laxmareddyp** [comment]
Hi @sowmya04101998,

Could you please use the latest official [trainer.py](https://github.com/tensorflow/models/blob/master/official/vision/train.py) for image calssification instead of legacy codebase.

Thanks.

**Comment by sowmya04101998** [comment]
I am unable to run the multiworker mirrored strategy using the trainer.py on multiple gpus on multi node environment , is the code already implemented in this ?  , please provide the steps to run the same . 

thanks

**Comment by laxmareddyp** [comment]
Hi @sowmya04101998 ,

Same as legacy code you can configure the yaml file and pass it to the trainer.py. For image_classification experiment you can run as below.
python3
python3 official/vision/train.py \
    --experiment=image_classification\
    --mode=train_and_eval\
    --model_dir=/tmp/trained_model/ \
    --config_file=pramas.yamlparams.yaml file should have configuration for multi-worker gpu that you have configured and proper architecture that your model is going to be trained on. For example take a look at this [config](https://github.com/tensorflow/models/blob/master/official/vision/configs/experiments/image_classification/imagenet_mobilenetv2_gpu.yaml) file which is for gpu mirrored strategy. If you still cannot run train.py ,Please share the error so that we can look into it further. I hope this helps to get some insight to train the model.

**Comment by sowmya04101998** [comment]
![image](https://github.com/tensorflow/models/assets/133966292/abef0dde-6375-435d-815e-ef7ec092cad6)

**Comment by sowmya04101998** [comment]
i dont see any example config files for multiworker mirrored strategy which is what im working on  , also does this strategy scale well , i see a lot of scaling issues been raised

**Comment by laxmareddyp** [comment]
Hi @sowmya04101998,

I guess you are cloning repo and trying to use train.py and also have installed pip install tf-models-official==2.11.0 which doesn't have latest code changes of git clone. So if you are using cloned repo make sure to follow this process.

consider this as nightly because you are using latest master branch
bash
$ git clone -q https://github.com/tensorflow/models.git
$ pip install -q -U tensorflow==2.13.0
$ pip install -q -U tensorflow_datasets
$ pip install -q --user -r models/official/requirements.txt
$ pip install -q -U tensorflow-text
Pip install official models which doesn't require you to clone repo for using official code.
bash
$ pip install -U tf-models-official

follow one of the above not both.


Now train the model as done in the notebook:

https://colab.research.google.com/gist/sineeli/e52ecd82a10d82f4955ef7f333ab6b3c/-11042.ipynb
I have downgraded pip because latest release of Cython having some issue while install tf-models-official. Notebook only showcases single GPU but it can be used for single machine multi gpu. But to use multi-machine multi gpu, the yaml file configuration will be different, rest of the steps should be same.

This notebook shows how to train the model using official.vision.train file or else you can train without using train.py file way which is explained in the notebook here:

[Image Classification Example](https://www.tensorflow.org/tfmodels/vision/image_classification)
[Object Detection Example](https://www.tensorflow.org/tfmodels/vision/object_detection)

this notebooks will help you to train end to end with latest official code. Please let us know if this helps you understand.

**Comment by sowmya04101998** [comment]
hi @laxmareddyp ,
I was able to run the following code 
**https://github.com/tensorflow/models/blob/master/official/legacy/image_classification/classifier_trainer.py**
on single-gpu, single node multi-gpu and multi node multi gpu , however i saw that the throughput given by single-node multi-gpu was better than single-gpu , but the numbers I got for mutli-node mutli-gpu was much lesser than single node multi gpu , what is the reason for this behavior? is it because of communication overhead?
 Also the throughput samples are shown in both the node terminal and slightly vary , does the model display the throughput of each gpu separately ? how am i supposed to read the throughput?

I executed the https://github.com/tensorflow/models/blob/master/official/legacy/image_classification/resnet/resnet_ctl_imagenet_main.py code as well , in this case multi-node multi gpu numbers was less than the single gpu numbers which is why I'm trying alternate code that scales well .

So please give me the steps to run this specific code
https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Classification/ConvNets/main.py for multi-node multi-gpu .

I have executed the latest code with TensorFlow  2.13 version itself and was still facing the **TypeError: run_experiment() got an unexpected keyword argument 'enable_async_checkpointing'** error . guide me on this

**Comment by laxmareddyp** [comment]
Hi @sowmya04101998,

Would you mind trying to create the environment I provided in the notebook above and running it? This environment uses the latest tf-models-officials code, instead of the legacy code you are currently using. We do not support the legacy code base, and we encourage everyone to use the latest official code.

To create the environment as described in the notebook and utilize the latest tf-models-official code, Before installing tf-models-official, please make sure to install the specific version 5.3.1 of PyYAML. There have been some reported issues with the latest release version of PyYAML, so it's essential to use version 5.3.1.

You can install PyYAML version 5.3.1 with the following command: `pip install PyYAML==5.3.1`

Once you have installed PyYAML version 5.3.1, you can proceed to install the latest version of tf-models-official using the following command:`pip install tf-models-official`

If you follow the setup above, it should not throw any errors, as we expect.

Thanks.
