### ISSUE TITLE
Cifar10 tutorial - NUM_CLASSES - Tensorflow 1.0

### ISSUE THREAD

**Issue by martin767** [tensorflow/models#1105]
I had tested the cifar10 tutorial with my own dataset which worked great till I updated to Tensorflow 1.0. Now I can not run the code anymore with a different number of classes then 10.

With version 0.12 I only changed NUM_CLASSES in cifar10_input.py to 2 but since updating i get this error:

`InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [2] rhs shape= [10]`

The rest of the code is unchanged, I only changed NUM_CLASSES

**Comment by tatatodd** [comment]
@martin767 In general, you can't expect to change constants in the code to different values, and expect things to work.

You've changed NUM_CLASSES from 10 to 2.  The particular error you're getting says that there is an Assign somewhere (for a variable) where there is a mismatch between the shapes, between a vector of size 2 and a vector of size 10.  I don't know exactly where this is, since you haven't included the rest of the stack trace.

If you're looking for help with running the cifar10 tutorial with 2 classes rather than 10, please ask the question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
