### ISSUE TITLE
textsum error reading data file

### ISSUE THREAD

**Issue by shahbazsyed** [tensorflow/models#1114]
## Please let us know which model this issue is about (textsum)
When i run the program using the toyset data folder provided, I always get the following error 

![image](https://cloud.githubusercontent.com/assets/4356098/23587037/5258c304-01a3-11e7-8420-f76d744c7766.png)

I am running this with Python 3.5

**Comment by lfzCarlosC** [comment]
This is because python3 has type byte, which python 2 all regards as string.
To make this running you need to decode text into string .

**Comment by Martinsos** [comment]
I am getting this same error, but I am not sure what is exactly the problem? I am figuring out from your comment that code was written for Python2?
I saw that there was a commit fixing stuff so it works for Python3, but it seems it didn't fix it completely, since I am also getting this error?

What I did is add `.decode('utf-8')` to the line 265 in batch_reader.py, and that has removed the errors. However, I am not sure if that is actually the right fix? Should I rather be running the code with python2?
Let me know what is the best approach here -> if I can help with getting this running for Python3, I gladly will.

Thanks!
