### ISSUE TITLE
How to add additional class (QR Codes) for coco dataset or any suggested dataset for the class I have mentioned

### ISSUE THREAD

**Issue by slashplusdash** [tensorflow/models#11185]
**Searches**
I have searched a lot of references and guide but I am still confused on what to do. (A beginner at this)

**Our method**
I have a method in mind by acquiring a custom datasets from coco and adding my labeled images (QR codes) using labelImg with xml files to the acquired datasets. I will then train the datasets together to get a new model. I am basing this method on SDD mobilenet since we will be using an Android smartphone for this project.

**Question**
1. I would like to ask from you guys who are experts or veterans on this matter if the labeled images I have are compatible with the coco dataset? 
2. Are our method okay for creating a new model? 
3. I have looked at other questions that would be similar to the question I have regarding adding classes to datasets or pre-trained models and the problem that they had was that the old classes will not be detected while the new ones (1 or 2 classes that they had) were detected. Any help on that if we would encounter this problem?

This is for our thesis project and we have no prior knowledge on object detection. If you have any time to consider our question and problems we would be so thankful for the help.

**Comment by laxmareddyp** [comment]
Hi @slashplusdash ,

I recommend going through this tutorial on object detection using TensorFlow models [here](https://www.tensorflow.org/tfmodels/vision/object_detection). It will provide a solid foundation and help clarify any doubts you may have. Since you're new to this, it's a great starting point and may spark new ideas or questions. 

Addition to that, you can follow this[ tutorial ](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/)for step by step process.

Feel free to reach out if you need further assistance—I'm here to help!
