### ISSUE TITLE
Intent of code for model neural_programmer

### ISSUE THREAD

**Issue by moshoujingli** [tensorflow/models#1137]
branch master
neural_programmer/neural_programmer.py line 185
I don't understand why drop the last model file.
Would someone like to kindly teach me the reason?

**Comment by prb12** [comment]
@arvind2505 is listed as contact for this model, and can probably comment further.

This question is maybe better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by arvind2505** [comment]
@moshoujingli It doesn't really matter. We pick the model that gives the best results on dev set and it usually much before 100k steps.

**Comment by prb12** [comment]
Ok - I'm going to close this since it isn't a bug/issue.
@moshoujingli Thanks for your input.

**Comment by moshoujingli** [comment]
@arvind2505 Thanks for your reply. 
 I agree that it usually happens much before 100k steps, but why we add several lines to do such a thing? If we just want to check less models, why drop only one?
Could I just delete line 184~185 to make it clear ?
