### ISSUE TITLE
[slim/nets] Problem restoring checkpoint of inception_resnet_v2 

### ISSUE THREAD

**Issue by Google1234** [tensorflow/models#1146]
## Please let us know which model this issue is about (specify the top-level directory)
I download pre-trained model form http://download.tensorflow.org/models/inception_resnet_v2_2016_08_30.tar.gz
when I run 

```
CHECKPOINT_PATH=***/checkpoints/inception_resnet_v2_2016_08_30.ckpt
python train_image_classifier.py \
   --train_dir=${TRAIN_DIR} \
   --dataset_dir=${DATASET_DIR} \
   --dataset_name=fishes \
   --dataset_split_name=train \
   --model_name=inception_resnet_v2 \
   --checkpoint_path=${CHECKPOINT_PATH} \
   --checkpoint_exclude_scopes=InceptionResnetV2/Logits,InceptionResnetV2/AuxLogits \
   --trainable_scopes=InceptionResnetV2
```
get error:
```
NotFoundError (see above for traceback): Key InceptionResnetV2/Repeat_1/block17_5/Conv2d_1x1/biases/RMSProp_1 not found in checkpoint
	 [[Node: save/RestoreV2_1402 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1402/tensor_names, save/RestoreV2_1402/shape_and_slices)]]
	 [[Node: save/RestoreV2_930/_833 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_15008_save/RestoreV2_930", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]  
```
while this scipt pass:
```
python train_image_classifier.py \
   --train_dir=${TRAIN_DIR} \
   --dataset_dir=${DATASET_DIR} \
   --dataset_name=fishes \
   --dataset_split_name=train \
   --model_name=inception_resnet_v2 \
   --checkpoint_path=${CHECKPOINT_PATH} \
   --checkpoint_exclude_scopes=InceptionResnetV2/Logits,InceptionResnetV2/AuxLogits \
   --trainable_scopes=InceptionResnetV2/Logits,InceptionResnetV2/AuxLogits
```
any suggest?maybe the pretrained model was damaged？

**Comment by prb12** [comment]
This sort of problem usually happens when the checkpoint was saved from one graph and restored using a TensorFlow graph with different variable names.  It can be caused by different versions of the code, and sometimes by different TensorFlow versions.

@sguada @nathansilberman Could you please comment on whether the pretrained model from August last year is likely to be compatible with the current code? (and TF version)

@Google1234 It would also help if you could please provide the software and OS versions you are using.

**Comment by Google1234** [comment]
ox: Linux version 3.10.104 (root@hadoop65) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #3 SMP Sun Jan 8 15:28:58 CST 2017
software：tensorflow 0.12.0   
slim from https://github.com/tensorflow/models

THX.

**Comment by Google1234** [comment]
of course,when i run:
DATASET_DIR=***/train
TRAIN_DIR=***/inception_resnet_v2
CHECKPOINT_PATH=***checkpoints/inception_resnet_v2_2016_08_30.ckpt
python train_image_classifier.py \
   --train_dir=${TRAIN_DIR} \
   --dataset_dir=${DATASET_DIR} \
   --dataset_name=fishes \
   --dataset_split_name=train \
   --model_name=inception_resnet_v2 \
   --checkpoint_path=${CHECKPOINT_PATH} \
   --checkpoint_exclude_scopes=InceptionResnetV2/Logits,InceptionResnetV2/AuxLogits \
   --trainable_scopes=InceptionResnetV2/Logits,InceptionResnetV2/AuxLogits

raise Error:
NotFoundError (see above for traceback): Key InceptionResnetV2/Repeat_1/block17_19/Branch_1/Conv2d_0b_1x7/BatchNorm/beta/RMSProp not found in checkpoint
	 [[Node: save/RestoreV2_1195 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1195/tensor_names, save/RestoreV2_1195/shape_and_slices)]]
	 [[Node: save/RestoreV2_151/_3727 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_10022_save/RestoreV2_151", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by NanqingD** [comment]
Hi, actually I have similar problem.
`NotFoundError (see above for traceback): Tensor name "InceptionResnetV2/Repeat_1/block17_18/Branch_0/Conv2d_1x1/biases" not found in checkpoint files /home/ndong/tb_v2/pre_trained/inception_resnet_v2_2016_08_30.ckpt
	 [[Node: save/RestoreV2_296 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_296/tensor_names, save/RestoreV2_296/shape_and_slices)]]
	 [[Node: save/RestoreV2_393/_495 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1985_save/RestoreV2_393", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]`



I am using Ubuntu 16.04 LTS, TF1.0.1

**Comment by rAm1n** [comment]
Hello,

I had a look into the code and also the checkpoint and I will post the missing variables from the checkpoint in the following. I think since most of these are biases,  a zero initialization for fine-tuning might work but, In general I was wondering if anyone could update the checkpoint and make it compatible with the code.

Thanks!

InceptionResnetV2/AuxLogits/Conv2d_1b_1x1/biases
InceptionResnetV2/AuxLogits/Conv2d_2a_5x5/biases
InceptionResnetV2/Block8/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Block8/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Block8/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Block8/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Conv2d_1a_3x3/biases
InceptionResnetV2/Conv2d_2a_3x3/biases
InceptionResnetV2/Conv2d_2b_3x3/biases
InceptionResnetV2/Conv2d_3b_1x1/biases
InceptionResnetV2/Conv2d_4a_3x3/biases
InceptionResnetV2/Conv2d_7b_1x1/biases
InceptionResnetV2/Mixed_5b/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Mixed_5b/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Mixed_5b/Branch_1/Conv2d_0b_5x5/biases
InceptionResnetV2/Mixed_5b/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Mixed_5b/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Mixed_5b/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Mixed_5b/Branch_3/Conv2d_0b_1x1/biases
InceptionResnetV2/Mixed_6a/Branch_0/Conv2d_1a_3x3/biases
InceptionResnetV2/Mixed_6a/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Mixed_6a/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Mixed_6a/Branch_1/Conv2d_1a_3x3/biases
InceptionResnetV2/Mixed_7a/Branch_0/Conv2d_0a_1x1/biases
InceptionResnetV2/Mixed_7a/Branch_0/Conv2d_1a_3x3/biases
InceptionResnetV2/Mixed_7a/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Mixed_7a/Branch_1/Conv2d_1a_3x3/biases
InceptionResnetV2/Mixed_7a/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Mixed_7a/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Mixed_7a/Branch_2/Conv2d_1a_3x3/biases
InceptionResnetV2/Repeat/block35_1/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_1/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_1/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_1/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_1/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_1/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_10/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_10/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_10/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_10/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_10/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_10/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_2/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_2/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_2/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_2/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_2/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_2/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_3/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_3/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_3/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_3/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_3/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_3/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_4/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_4/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_4/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_4/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_4/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_4/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_5/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_5/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_5/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_5/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_5/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_5/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_6/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_6/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_6/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_6/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_6/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_6/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_7/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_7/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_7/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_7/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_7/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_7/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_8/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_8/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_8/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_8/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_8/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_8/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat/block35_9/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat/block35_9/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_9/Branch_1/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_9/Branch_2/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat/block35_9/Branch_2/Conv2d_0b_3x3/biases
InceptionResnetV2/Repeat/block35_9/Branch_2/Conv2d_0c_3x3/biases
InceptionResnetV2/Repeat_1/block17_1/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_1/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_1/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_1/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_10/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_10/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_10/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_10/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_11/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_11/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_11/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_11/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_12/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_12/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_12/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_12/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_13/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_13/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_13/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_13/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_14/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_14/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_14/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_14/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_15/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_15/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_15/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_15/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_16/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_16/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_16/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_16/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_17/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_17/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_17/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_17/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_18/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_18/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_18/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_18/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_19/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_19/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_19/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_19/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_2/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_2/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_2/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_2/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_20/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_20/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_20/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_20/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_3/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_3/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_3/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_3/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_4/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_4/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_4/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_4/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_5/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_5/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_5/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_5/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_6/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_6/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_6/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_6/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_7/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_7/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_7/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_7/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_8/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_8/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_8/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_8/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_1/block17_9/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_1/block17_9/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_1/block17_9/Branch_1/Conv2d_0b_1x7/biases
InceptionResnetV2/Repeat_1/block17_9/Branch_1/Conv2d_0c_7x1/biases
InceptionResnetV2/Repeat_2/block8_1/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_1/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_1/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_1/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Repeat_2/block8_2/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_2/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_2/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_2/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Repeat_2/block8_3/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_3/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_3/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_3/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Repeat_2/block8_4/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_4/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_4/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_4/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Repeat_2/block8_5/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_5/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_5/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_5/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Repeat_2/block8_6/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_6/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_6/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_6/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Repeat_2/block8_7/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_7/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_7/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_7/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Repeat_2/block8_8/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_8/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_8/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_8/Branch_1/Conv2d_0c_3x1/biases
InceptionResnetV2/Repeat_2/block8_9/Branch_0/Conv2d_1x1/biases
InceptionResnetV2/Repeat_2/block8_9/Branch_1/Conv2d_0a_1x1/biases
InceptionResnetV2/Repeat_2/block8_9/Branch_1/Conv2d_0b_1x3/biases
InceptionResnetV2/Repeat_2/block8_9/Branch_1/Conv2d_0c_3x1/biases
