### ISSUE TITLE
Check failed: category == it->second (PRON vs. ADV)POS tag cannot be mapped to multiple coarse POS tags. '' is mapped to: 'PRON' and 'ADV'

### ISSUE THREAD

**Issue by dzenteno2** [tensorflow/models#118]
I am trying to train the SyntaxNet POS Tagger using the UD_Spanish from Universal Dependencies. I modified syntaxnet/context.pbtxt to match the location of the training, test and dev files. However when I run this:

```
bazel-bin/syntaxnet/parser_trainer \
  --task_context=syntaxnet/context.pbtxt \
  --arg_prefix=brain_pos \  # read from POS configuration
  --compute_lexicon \       # required for first stage of pipeline
  --graph_builder=greedy \  # no beam search
  --training_corpus=training-corpus \  # names of training/tuning set
  --tuning_corpus=tuning-corpus \
  --output_path=models \  # where to save new resources
  --batch_size=32 \       # Hyper-parameters
  --decay_steps=3600 \
  --hidden_layer_sizes=128 \
  --learning_rate=0.08 \
  --momentum=0.9 \
  --seed=0 \
  --params=128-0.08-3600-0.9-0  # name for these parameters
```

I've got:

`F syntaxnet/term_frequency_map.cc:166] Check failed: category == it->second (PRON vs. ADV)POS tag cannot be mapped to multiple coarse POS tags. '' is mapped to: 'PRON' and 'ADV'`

Do you know what I am missing?

Thanks a lot.

**Comment by dsindex** [comment]
@dzenteno2 
i got the same problem. i think it is very natural that XPOSTAG can map muliple UPOSTAGs.
but term_frequency_map.cc seems not to allow.
and there are only XPOSTAGs in the parsing result( output of `demo.sh` )
```
natural JJ ROOT
 +-- it PRP nsubj
 +-- is VBZ cop
 +-- very RB advmod
 +-- map VB ccomp
 |   +-- that IN mark
 |   +-- XPOSTAG NNP nsubj
 |   +-- can MD aux
 |   +-- UPOSTAGs NNP dobj
 |       +-- muliple VB amod
 +-- . . punct
```
so i decided to map XPOSTAG to UPOSTAG before training.

https://github.com/dsindex/syntaxnet
https://github.com/dsindex/syntaxnet/blob/master/convert.py

that was fine~

**Comment by slavpetrov** [comment]
The coarse tags are supposed to form a hierarchy where the coarse tags are 'coarser' than the fine tags. As such it doesn't make sense for one fine tag to map to multiple coarse tags (because that would invert the relationship and suggest that the coarse tags are actually finer). I will bring this up in the Universal Dependencies forum, but in the meantime you will either flip those tags or refine the fine tags.

The reason that we need to enforce this is that we add the coarse tags by mapping the fine tag deterministically (i.e. no more prediction and we hence wouldn't have a process of figuring out which coarse tag to use). Hope this makes sense.

**Comment by dzenteno2** [comment]
@dsindex, thanks a lot. I used your script to train the UD_English. Although, there are some other problems with UD_Spanish, now I understand it is not related to SyntaxNet.

I am closing this issue.

If anyone else is having this problem, check [UniversalDependencies/docs#297](https://github.com/UniversalDependencies/docs/issues/297) as well.

Thanks a lot.
