### ISSUE TITLE
[Textsum] - 'module' object has no attribute 'bidirectional_rnn'

### ISSUE THREAD

**Issue by ailurus1991** [tensorflow/models#1187]
Hi all,

I'm new to TF and textsum model. I was trying to run the demo by the readme.

When I was trying to train:
```
File "/home/pio/text_sum/ws/textsum/seq2seq_attention_model.py", line 169, in _add_seq2seq
(emb_encoder_inputs, fw_state, _) = tf.nn.bidirectional_rnn(
AttributeError: 'module' object has no attribute 'bidirectional_rnn'
```

So how to solve this? Many thanks.

**Comment by xtr33me** [comment]
What version of TF are you running? If it is 1.0 then it's most likely due to some of the changes that occurred in 1.0. I'm not at a computer right now, but if you are using 1.0, perform a search in the api for that funtion. It will tell you what it has changed to if it has. If you just cloned the repo, then overall most of the files have been updated a few days back but I'm still seeing some things that have not updated that I have tickets for.

If you are running an older version of TF, such as 0.11 then if you clone an earlier tag from models, you should be good. My last working implementation of textsum was using 0.11 and the textsum model prior to the 1.0 update script being run on it.

**Comment by nealwu** [comment]
Should be fixed by https://github.com/tensorflow/models/pull/1197.
