### ISSUE TITLE
Syntaxnet Parsey Mcparse gives dependency tree with two roots.

### ISSUE THREAD

**Issue by utkrist** [tensorflow/models#1306]
I am using parsey_mcparseface as the model in syntaxnet. I get really weird results with two ROOTs. 
An example is as follows:

     $ echo "They never considered themselves to be anything else." | syntaxnet/demo.sh

I get following output. Notice the two roots in token number 3 and 9. This is not the only case when this happens. There are many sentences producing output like this, especially the problem seems to stem from punctuations. Does anyone know the cause for this and the way to fix it. I am using the default context.pbtxt file.

      1	They	_	PRON	PRP	_	3	nsubj	_	_
      2	never	_	ADV	RB	_	3	neg	_	_
      3	considered	_	VERB	VBD	_	0	ROOT	_	_
      4	themselves	_	PRON	PRP	_	7	nsubj	_	_
      5	to	_	PRT	TO	_	7	aux	_	_
      6	be	_	VERB	VB	_	7	cop	_	_
      7	anything	_	NOUN	NN	_	3	xcomp	_	_
      8	else	_	ADJ	JJ	_	7	amod	_	_
      9	.	_	.	.	_	0	ROOT	_	_

**Comment by djweiss** [comment]
Sorry to take so long to get back to you. There is unfortunately no easy fix -- the issue is that, depending on the language, it is sometimes OK to have multiple roots, so the transition system does not enforce the constraint. 

If you find multiple roots, and want to choose a single one, the best thing you can do is pick one heuristically -- regardless, the statistical model would have made a mistake on that example (as you can see by the fact that it has two nsubj's.)
