### ISSUE TITLE
SyntaxNet : echo "i am human" | syntaxnet/demo.sh

### ISSUE THREAD

**Issue by dsindex** [tensorflow/models#132]
using parsey_mcparseface model :  

$ echo "i am human" | syntaxnet/demo.sh
Input: i am human
Parse:
human JJ ROOT
 +-- i PRP nsubj
 +-- am VBP cop

$ echo "i am a student" | syntaxnet/demo.sh
Input: i am a student
Parse:
student NN ROOT
 +-- i PRP nsubj
 +-- am VBP cop
 +-- a DT det

this model seems to be weak for 'be' verb. why?
is this model not the one described in the paper( http://www.petrovi.de/data/acl15.pdf )?

**Comment by slavpetrov** [comment]
These parses are correct as the Stanford dependencies treat the copula as the dependent rather than the root. Quoting from the manual:

4.7 The treatment of copula verbs
The design philosophy of SD has been to maximize dependencies between content words, and so we
normally regard a copula verb like be as an auxiliary modifier, even when its complement is an adjective
or predicative noun (see the references in section 6 for more discussion and motivation). However, some
people do not like this because then the head of some sentences is no longer a verb. In the dependency
conversion software, you can ask for the copula to remain the head when its complement is an adjective
or noun by giving the flag -makeCopulaHead. Uses of the verb be as in auxiliary in passives and
progressives will still be treated as a non-head auxiliary.
http://nlp.stanford.edu/software/dependencies_manual.pdf

Marking as closed, but feel free to reopen if something is unclear.

**Comment by dsindex** [comment]
thank you! i got it :)

**Comment by mastasky** [comment]
@slavpetrov: Can this be changed in Parsey by using a flag as well?
