### ISSUE TITLE
[spatial_transformer bug] what happens if the coordinates fall out of the sampling region

### ISSUE THREAD

**Issue by xcyan** [tensorflow/models#1320]
# models/transformer/spatial_transformer.py
Seems that it simply takes the boundary value for sampling rather than dropping it.
However, in the torch implementation, there is such sanity check (L76-L80).
Reference: https://github.com/qassemoquab/stnbhwd/blob/master/generic/BilinearSamplerBHWD.c

**Comment by michaelisard** [comment]
@cbfinn can you comment?

**Comment by cbfinn** [comment]
I didn't write the code for spatial transformer. It seems like adding such a sanity check would be useful, though I have found that it isn't necessary for the video prediction model.

Some potential reasons for why it isn't a problem in video prediction compared to other use cases: 
(1) redundancy - we use multiple spatial transformer modules, and let the model choose which ones it wants to use (so if one falls of the image, it can just choose not to use it)
(2) initialization - we initialize with the identity affine transformer so that the model starts centered on the sampling region, and shouldn't be encouraged to fall outside of it, unless the gradients are particularly noisy
(see https://github.com/tensorflow/models/blob/master/video_prediction/prediction_model.py#L240)

**Comment by xcyan** [comment]
@cbfinn Thanks for clarification! 
In fact, the current implementation of STN is buggy since it simply takes boundary value (e.g., A[0, 0]) when the pixel falls outside of the 2D space [0, height-1] x [0, width - 1].

**Comment by lvenugopalan** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by lvenugopalan** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
