### ISSUE TITLE
[slim] TF-Slim multi-gpu ignoring device specification

### ISSUE THREAD

**Issue by patrhel** [tensorflow/models#1338]
My aim is to run a given standard script (located in /models/slim/scripts) in multi-GPU mode. Using TensorFlow-Slim, I've tested the **finetune_resnet_v1_50_on_flowers.sh** script (cloned on 12.04.2017). I've just added **--num_clones=2** at the end of the training part:

```
python train_image_classifier.py \
  --train_dir=${TRAIN_DIR} \
  --dataset_name=flowers \
  --dataset_split_name=train \
  --dataset_dir=${DATASET_DIR} \
  --model_name=resnet_v1_50 \
  --checkpoint_path=${PRETRAINED_CHECKPOINT_DIR}/resnet_v1_50.ckpt \
  --checkpoint_exclude_scopes=resnet_v1_50/logits \
  --trainable_scopes=resnet_v1_50/logits \
  --max_number_of_steps=3000 \
  --batch_size=32 \
  --learning_rate=0.01 \
  --save_interval_secs=60 \
  --save_summaries_secs=60 \
  --log_every_n_steps=100 \
  --optimizer=rmsprop \
  --weight_decay=0.00004 \
  --num_clones=2
```

I've got one warning ('Ignoring device specification'):
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-SXM2-16GB, pci bus id: 0000:85:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla P100-SXM2-16GB, pci bus id: 0000:86:00.0)
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:1 for node 'clone_1/fifo_queue_Dequeue' because the input edge from 'prefetch_queue/fifo_queue' is a reference connection and already has a device field set to /CPU:0
I tensorflow/core/common_runtime/simple_placer.cc:669] Ignoring device specification /GPU:0 for node 'clone_0/fifo_queue_Dequeue' because the input edge from 'prefetch_queue/fifo_queue' is a reference connection and already has a device field set to /CPU:0
```

The GPUs run normally (memory usage and GPU utilization), but the training is not faster compared with a single GPU training.

This issue might be related to: https://github.com/tensorflow/tensorflow/issues/8061 and https://github.com/tensorflow/tensorflow/issues/7038

CUDA version: release 8.0, V8.0.53
TensorFlow installed from binary, tested versions: 1.0.1 and 1.1.0rc1
GPU: NVIDIA Tesla P100 (SXM2)

**Comment by jart** [comment]
This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). We're not able to provide support for modified examples.

**Comment by Yonezcy** [comment]
Same problem. This issue was solved?
Ignoring device specification /device:CPU:2 for node xxx because the input edge from xxx is a reference connection and already has a device field set to /device:CPU:1

**Comment by vanillar7** [comment]
> Same problem. This issue was solved?
> Ignoring device specification /device:CPU:2 for node xxx because the input edge from xxx is a reference connection and already has a device field set to /device:CPU:1

i have the same problem， have you solved？

**Comment by Yonezcy** [comment]
The reason is my cluster is not stable.&nbsp;


Regards,
Yone




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorflow/models"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 下午3:04
收件人:&nbsp;"tensorflow/models"<models@noreply.github.com&gt;;
抄送:&nbsp;"赵晨宇"<364251097@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/models] [slim] TF-Slim multi-gpu ignoring device specification (#1338)





  
Same problem. This issue was solved?
 Ignoring device specification /device:CPU:2 for node xxx because the input edge from xxx is a reference connection and already has a device field set to /device:CPU:1
  
i have the same problem， have you solved？
