### ISSUE TITLE
Implementation Question about the slim Resnet Model Downsampling Position

### ISSUE THREAD

**Issue by buaa1406LiuZheng** [tensorflow/models#1418]
I found that in the slim.nets.resnet_v1 and slim.nets.resnet_v2, the implementations of Resnet have a different Downsampling Position compared with the original paper[1] and its official caffe implementation[2].

Take the resnet_v1_50 for example, it downsamples at the first three blocks i.e. block1, block2 and block3, and in each block, it downsamples at the last unit i.e. the last bottleneck, and in each bottleneck, it downsamples at the middle conv layer i.e. the 3*3 conv layer.
But in the original implementation, it downsamples at the last three blocks i.e. block2, block3 and block4, and in each block, it downsamples at the first unit, and in each bottleneck, it downsamples at the first conv layer.

I'm not sure whether it's indeed a variant implementation or I got something wrong.

[1] Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun
    Deep Residual Learning for Image Recognition. arXiv:1512.03385
[2]https://github.com/KaimingHe/deep-residual-networks

**Comment by SummerIcequeen** [comment]
I also find this problem disturbing. From the github of Kaiming He, he also points to the visualization of the network configuration, for example [resnet-101](http://ethereon.github.io/netscope/#/gist/b21e2aae116dc1ac7b50). From there you can see when downsampling, the bottleneck will always perform it at conv1 with stride 2 and then continue to conv2 with stride 1. I checked the current slim implementation [source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py). I think line 116 and 121 should be changed into the following:
```python
residual = layers.conv2d(inputs, depth_bottleneck, [1, 1], stride, scope='conv1')
residual = resnet_utils.conv2d_same(residual, depth_bottleneck, 3, stride=1, rate=rate, scope='conv2')
residual = layers.conv2d(residual, depth, [1, 1], stride=1, activation_fn=None, scope='conv3')
```

But, the current slim implementation makes a bit more sense to me though.

**Comment by EmGarr** [comment]
Did you guys had any information about what paper motivated these choices?

**Comment by irmowan** [comment]
I have tried to modify the slim version to paper implementation version, and the precision decreased much in my detection task. Not only the position of downsample, but also the 'conv2d_same' effects.
So I also want to know, why this implementation, where can we find the motivation? @sguada

**Comment by waleedka** [comment]
I noticed this as well while debugging another issue. The comments in resnet_v1.py say 

> This is the architecture used by MSRA in the Imagenet and MSCOCO 2016 competition models ResNet-101 and ResNet-152

However, MSRA didn't participate in [MSCOCO 2016](http://image-net.org/challenges/LSVRC/2016/results). Maybe they meant [2015](http://image-net.org/challenges/LSVRC/2015/results). The [official code](https://github.com/KaimingHe/deep-residual-networks) from Kaiming He, which he states was used in the MS COCO competition, matches the paper and is different from the implementation in Slim. 

It's also worth noting that the Slim implementation is significantly more processing and memory intensive because it delays the subsampling to the end of each block. For example, in Resnet101 block 4 has 23 residual units, all of which are processed at 4x the resolution (compared to the paper) before finally getting subsampled at the last unit. 

Definitely would be good to get a reply from the Slim authors about whether this is a bug or by design.

**Comment by waleedka** [comment]
Found this note in [resnet_utils.py](https://github.com/tensorflow/models/blob/master/research/slim/nets/resnet_utils.py). 

> Compared to https://github.com/KaimingHe/deep-residual-networks, in the current
implementation we subsample the output activations in the last residual unit of
each block, instead of subsampling the input activations in the first residual
unit of each block. The two implementations give identical results but our
implementation is more memory efficient.

Intuitively, this change should increase memory requirements. Instead of increasing the conv dimension and reducing it's size at the same time, it raises the dimension first and then, many laters later, subsamples to reduce the size. To verify my intuition, I changed my own Keras implementation to do the subsampling at the last unit, just like Slim. As expected, my network didn't fit in GPU anymore and I had to reduce the batch size to make it work. 

Unless I'm missing something, this is looking like a bug that's causing unnecessary memory load.

**Comment by Superlee506** [comment]
@waleedka I also found this issue, and doubted about their explanation.  In the other hand, they said their pretrained parameters of Resnet V1 was converted from the original Caffe. It makes more confused.

![image](https://user-images.githubusercontent.com/13114675/36569473-f592a462-17fb-11e8-9c78-71d9f614c40d.png)

**Comment by Superlee506** [comment]
@irmowan Which version of ResNet did you modify? The ResNet models were trained by themselves except the ResNet V1 which was converted from Caffe. So if change the models trained by themselves, the performance should decrease.

**Comment by yuanzhi-liang** [comment]
Thanks a lot !!!
I take about 2 days thinking to find wether I had somethings misunderstood in code or paper.
Maybe it's weired, but it feels good to find someone have the same problem finally.

**Comment by lucasb-eyer** [comment]
Yup, I think this is a mistake. I was wondering why my identical code was much faster and more memory-efficient in TF than in Theano, and it's due to this.
It would be interesting to see the difference in ImageNet score by simply changing the stride settings here. I don't currently have time for this myself, though.

**Comment by nicolasj92** [comment]
If I am not mistaken this can be changed by setting the parameter 
`
store_non_strided_activations=True`

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
