### ISSUE TITLE
UTF-8 error in the compression model

### ISSUE THREAD

**Issue by berkcoker** [tensorflow/models#1467]
I was having a utf-8 error until I included 'rb' in line 62 of file compression/image_encoder/encoder.py. It is quick fix:)

**Comment by ali01** [comment]
Thanks for the heads up, @berkcoker!
@nickj-google, are you able to make the fix and test?

Thanks,
Ali

**Comment by nickj-google** [comment]
Yeah, I can fix this. I want to spend a little time digging into what broke between then and now as well.

**Comment by nickj-google** [comment]
@berkcoker, What version of TensorFlow are you running?

I'm not seeing the issue on 1.0.1.

**Comment by d-hoke** [comment]
@nmjohn - Are you using a file that contains invalid utf-8 sequences?  If your files don't contain invalid utf-8 sequences, then you won't encounter the outright error.  (I have wondered if the possibility exists of data being silently corrupted from conversions from valid utf-8 that gets transformed into something else internally.)

I have encountered the same issue as @berkcoker, and addressed it similarly (with versions of models cloned in week prior to this post, and tensorflow-gpu installed via pip on windows python 3.5.2 - unfortunately not immediately at hand to see commit or version.)

I think there may also be an issue in decoder.py writing out the files as text, rather than with the additional 'b', with the output file possibly having conversions performed on it, but not sure.

I'm guessing this issue may have resulted from differences between python2 and python3 regarding (unicode changes for) text vs bytes and file io...

**Comment by rzumer** [comment]
Hello,

Using the latest version of Tensorflow with Python 3.6, the example image provided in the repository cannot be read without the modification indicated above by @berkcoker. A similar modification also needed to be applied to the generated code file in order to support decoding.
While this may be presumptuous, I have submitted a PR, #3712, to resolve this issue, as it has been sitting for nearly a year with no resolution despite a simple fix being available. Images are not UTF-8 strings and should not be read as such.

@nmjohn, I would appreciate any comments regarding this issue and PR and assistance to get it pulled if you agree with the fix.

Thanks.

**Comment by rzumer** [comment]
This is fixed in commit dcfe009.

**Comment by karmel** [comment]
Sounds like this issue is resolved; closing. Please open a new issue if new problems arise.
