### ISSUE TITLE
Skip_Thoughts: Key error in encoding data 

### ISSUE THREAD

**Issue by anurag25** [tensorflow/models#1494]
### System information
- **Top-level directory of the model** skip_thoughts
- **OS Platform and Distribution** Linux Ubuntu 16.04
- **Python version** 3.5.2
- **TensorFlow version**  1.1.0
- **CUDA/cuDNN version** N/A
- **GPU model and memory** N/A

### Problem description
I am trying to generate skip-thought vectors using pretrained models, but getting a key error while executing:
`encodings = encoder.encode(data)`
Could anyone please help me out?

### Source code / logs
---------------------------------------------------------------------------
```
KeyError                                  Traceback (most recent call last)
<ipython-input-12-b9d895a94d88> in <module>()
----> 1 encodings = encoder.encode(data)

/home/anurag/skip_thoughts/encoder_manager.py in encode(self, data, use_norm, verbose, batch_size, use_eos)
    125                   verbose=verbose,
    126                   batch_size=batch_size,
--> 127                   use_eos=use_eos)))
    128 
    129     return np.concatenate(encoded, axis=1)

/home/anurag/skip_thoughts/skip_thoughts_encoder.py in encode(self, sess, data, use_norm, verbose, batch_size, use_eos)
    236         encodings of sentences in 'data'.
    237     """
--> 238     data = self._preprocess(data, use_eos)
    239     thought_vectors = []
    240 

/home/anurag/skip_thoughts/skip_thoughts_encoder.py in _preprocess(self, data, use_eos)
    211       if use_eos:
    212         tokenized.append(special_words.EOS)
--> 213       preprocessed_data.append([self._word_to_embedding(w) for w in tokenized])
    214     return preprocessed_data
    215 

/home/anurag/skip_thoughts/skip_thoughts_encoder.py in <listcomp>(.0)
    211       if use_eos:
    212         tokenized.append(special_words.EOS)
--> 213       preprocessed_data.append([self._word_to_embedding(w) for w in tokenized])
    214     return preprocessed_data
    215 

/home/anurag/skip_thoughts/skip_thoughts_encoder.py in _word_to_embedding(self, w)
    193   def _word_to_embedding(self, w):
    194     """Returns the embedding of a word."""
--> 195     return self._embeddings.get(w, self._embeddings[special_words.UNK])
    196 
    197   def _preprocess(self, data, use_eos):

KeyError: '<unk>'

```
Thanks.

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by lucaslingle** [comment]
Hello, 

I had the same problem. I am posting to confirm that it is not a bug.

If the `'<unk>'` token was missing from the pretrained model's `vocab.txt` file, it **would** be a bug to be fixed by the skip_thoughts maintainers, because the code would crash on OOV tokens, when it was explicitly designed not to do so. 

But the truth is, `'<unk>'` is not missing. 

To anyone who encountered the same issue: 

> `self._embeddings` is a dictionary constructed using `reverse_vocab` as its keys. So the only way `self._embeddings` can have a keyerror for `'<unk>'` is that `'<unk>'` isn't in `reverse_vocab`. So the only way that it isn't in `reverse_vocab` is that (a) you have a corrupted vocab file, or (b) you didn't decode the vocab file correctly. 

If you're using Python 3, you have to edit `encoder_manager.py` on L64-L66 in order to get it the vocab to be read properly at all--so make sure you make the right edits!

For Python 3, the following edits to be sufficient to fix all the issues for the pretrained vocab:

1. You have to read the vocab with `mode='rb'` on L64 of `encoder_manager.py`. 
2. Use `.decode("utf-8", errors='ignore')` on L66 of `encoder_manager.py`. 

I'm not a fan of `errors='ignore'`, but the code crashes on a non UTF-8 character without it, and everything works fine with it. I am not sure what the correct codec is supposed to be, for the vocab file, but it's kinda important to know, if you're gonna turn everything into strings like they did in the skip_thoughts implementation. There's even some Japanese characters in the vocab. ¯\\\_(ツ)\_/¯
