### ISSUE TITLE
Mention of Python 3: AttributeError: 'dict' object has no attribute 'iteritems' for "python ./object_detection/builders/model_builder_test.py"

### ISSUE THREAD

**Issue by zhouphd** [tensorflow/models#1587]
When you meet this:

```
File "./object_detection/builders/model_builder_test.py", line 258, in test_create_faster_rcnn_resnet_v1_models_from_config

File "./object_detection/builders/model_builder_test.py", line 448, in test_create_rfcn_resnet_v1_model_from_config

```
This is a Python 2 to Python 3 of dict change.

Solution:
_change iteritems() to items()_

`for extractor_type, extractor_class in FEATURE_EXTRACTOR_MAPS.items():`

Then,
`python ./object_detection/builders/model_builder_test.py`

.......
----------------------------------------------------------------------
Ran 7 tests in 0.055s

OK

**Comment by aselle** [comment]
@zhouphd, thanks for finding this. Could you prepare a pull request, please?

**Comment by nealwu** [comment]
@justanhduc submitted a pull request at https://github.com/tensorflow/models/pull/1571/files.

**Comment by zhouphd** [comment]
@aselle  I’d like to,  it seems a common issue, a pull request more like: moving python 2 to python 3,  just mention user who meet this, I 'll keep watching & following, :)

@nealwu @justanhduc  Thanks for you all, I was sleeping in the midnight, ~~

From #1571 , I think we could close this, :)

Best,

**Comment by kaseyriver11** [comment]
I believe this problem is also occurring when batcher.py is called. 

tensorflow/models/object_detection/core/batcher.py

**Comment by PatelAshish1** [comment]
As you are in python3 , use dict.items() instead of dict.iteritems()

iteritems() was removed in python3, so you can’t use this method anymore.

Take a look at Python 3.0 Wiki Built-in Changes section, where it is stated:

Removed dict.iteritems(), dict.iterkeys(), and dict.itervalues().

Instead: use dict.items(), dict.keys(), and dict.values() respectively

Founded At [Icetutor](https://icetutor.com/question/error-dict-object-has-no-attribute-iteritems/)
