### ISSUE TITLE
GPU device setting for python object_detecttion/train.py running on local machine 

### ISSUE THREAD

**Issue by troylhy1991** [tensorflow/models#1709]
Hi,

I'm running the train.py on my local machine (with four GPUs).

It's running on GPU:0 , but all the other three GPUs also got memory loaded, so I cannot use them for the other job at the same time. 

Is there any idea for setting up the train.py on exactly only one GPU like --gpus 0? 

Thanks,

Troy

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said, you're looking for the environment variable CUDA_VISIBLE_DEVICES.  E.g. CUDA_VISIBLE_DEVICES=0 will restrict to gpu 0.

**Comment by wuwuwuxxx** [comment]
Did you try the multi-gpu training? I want to train it on 2 gpus, and change the parameter 'num_clones' and  'batchsize' to 2, it gives me a out of range error.

**Comment by SimsGautam** [comment]
@wuwuwuxxx I have the same issue. Looking to resolve this. Thanks!
