### ISSUE TITLE
configs for object detection model zoo

### ISSUE THREAD

**Issue by starcrest** [tensorflow/models#1952]
Could you please release the configuration files (pipeline_pb2.TrainEvalPipelineConfig or train_pb2.TrainConfig) used to train the models in the object_detection [model zoo](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md)?  I'd like to see the optimization parameters, etc, to learn best practices -- and ideally be able to reproduce from scratch.

Sorry if I missed it.  Thanks!

**Comment by yanfengliu** [comment]
@starcrest There are all [here](https://github.com/tensorflow/models/tree/a4944a57ad2811e1f6a7a87589a9fc8a776e8d3c/object_detection/protos)

**Comment by thaiat** [comment]
these are the default values, not necessarly the ones they used for training...

**Comment by jch1** [comment]
Hi @thaiat - those are actually almost exactly what we used for training.  The only differences are:
1) For SSD models, we use a batch size of 32 instead of 24.
2) We (obviously) change the number of classes for COCO to be 90.
3) We always initialize from an Imagenet pretrained classification checkpoint, which you can find via the documentation in the tensorflow/models/slim directory and set `from_detection_checkpoint=false`

That's it!  The hyperparameters that we provide are what we have found to work well when training in an asynchronous optimization setting with roughly 10 GPUs (you can reproduce this using our tutorial for Google Cloud if you crank up the number of GPUs).  Just know that training a full model on COCO in this manner can be costly since the jobs take 3-4 days on average to converge.

**Comment by taewookim** [comment]
Apologies in advance if this isn't relevant

How are these pretrained models (from the model zoo) able to detect different classes in COCO dataset when clearly not all classes have same # of training images? For example, "person" class has well over 100k+ images and some don't even have a couple of thousand. But I do see that the smaller image set class does seem to detect ok when found next to a person.

Was there data augmentation done on the classes with smaller # of images? 

I'm using a subset of the COCO dataset combined with WIDERFACE to try and detect person AND face, and this has been challenging.  (Would appreciate if you know of any pretrained models /github repo that's already done this)

**Comment by pabloapast** [comment]
Hi @taewookim 
I'm trying to do something similar like you, did you have success on this? Do you have any recommendation?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
