### ISSUE TITLE
Image Resize for Fine Tuning

### ISSUE THREAD

**Issue by nikhileshsharma91** [tensorflow/models#1953]
I am using the tutorials provided for fine tuning the inception model for the Flowers dataset.

I am running the process on a Tesla K40 GPU.

How long will it approximately on finish the fine tuning process?

I also have a custom dataset and I have created the tfrecords for that dataset (total size = 33GB).

If I were to fine tune on my custom dataset I can imagine taking it a couple of days, if I am not wrong.

Do you think it will be help to resize the images and create new tfrecords? Currently some of the images are 4000 X 3000 pixels. 

What is the recommended size for the inception model?

**Comment by mattryles** [comment]
Not sure if its possible but it would be good if there was some sort of information on model training timing required on different size data sets.

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by drpngx** [comment]
@tfboyd might know or have pointers.

**Comment by tfboyd** [comment]
StackOverflow is definitely better but you still may not get an answer.  I do not know a lot but here is what I know.  

I believe you are talking about this [example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/image_retraining).  I looked at it a few weeks ago to see if we could speed it up and the issue is the model is not built in code but rather loaded from a checkpoint.  This makes it difficult (very) to try and do any type of multi-gpu support.  I think today if you make it multi-GPU it might put some of the ops on each GPU and end up slower.  

In regards to size, I am not remotely an expert.  For one of the most popular imagesets (Imagenet) Inception is normally trained with 299x299 with 3 channels.  I believe it is also common to do random cropping and some level of distortions but you would want to look at an inception example or look up the paper.  I think most models point back to the original Alexnet paper for the distortions used.  

I do not know about fine tuning but training from scratch I believe 100 epochs is common.  You can count your images and record when you have gone through the and then estimate the epochs.  Sorry to say this again, I know very very little about fine tuning so it is very possible 30 epochs or less is what you need to do.  

I hope there is one small piece of useful information above.  Good luck.
