### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/models#1971]
Im getting the following error while running from object_detection directory

```
protoc protos/*.proto --python_out=.
protos/*.proto: Invalid argument
```

how can i sort  this out?

**Comment by drpngx** [comment]
Hi, it's hard to tell without context what you're trying to do. It's likely that you are getting this error because there are no files matching the pattern. We provide build files so that you don't have to do that manually.

**Comment by Zumbalamambo** [comment]
may i know where is the build file?

**Comment by drpngx** [comment]
It's the bazel build file in `objection_detection/protos`, but this is called automatically if you try to build:
```
bazel build --config=opt :train
```
/CC: @derekjchow

**Comment by Zumbalamambo** [comment]
I got this error `BUILD file not found on package path and referenced by '//object_detection:train'.`

**Comment by Aarijit** [comment]
Hi,

I'm also facing the same problem. I build protoc following [this](https://github.com/google/protobuf/blob/master/cmake/README.md). And all my test were fine. I ran till `nmake install`. 

Now I copied `proctoc.exe`, and paste in the folder I'm building the model So my folder structure is "myModelFolder\object_detection". I pasted protoc in "myModelFolder". Then I cd into  "myModelFolder" and running 
`protoc object_detection\protos\*.proto --python_out=.`

But I'm getting `object_detection\protos\*.proto: "Invalid argument"`

So I'm not sure why I'm getting this error. Can anyone please help me?

Thank you!

**Comment by drpngx** [comment]
It's not parsed by the shell. You have to do it one by one

On Jul 26, 2017 2:04 PM, "Arijit" <notifications@github.com> wrote:

Hi,

I'm also facing the same problem. I build protoc following this
<https://github.com/google/protobuf/blob/master/cmake/README.md>. And all
my test were fine. I ran till nmake install.

Now I copied proctoc.exe, and paste in the folder I'm building the model So
my folder structure is "myModelFolder\object_detection". I pasted protoc in
"myModelFolder". Then I cd into "myModelFolder" and running
protoc object_detection\protos\*.proto --python_out=.

But I'm getting object_detection\protos\*.proto: "Invalid argument"

So I'm not sure why I'm getting this error. Can anyone please help me?

Thank you!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/models/issues/1971#issuecomment-318033363>,
or mute the thread

**Comment by Aarijit** [comment]
@drpngx: Thanks for your answer. But when I use "proctoc.exe" from proctoc\bin folder, I could compile it. Now I can import utils modules. Thanks again!

**Comment by trialzuki** [comment]
It's windows make us cry 
run under powershell in 'research' folder for bath compile all of *.proto files

`
$files = Get-ChildItem .\object_detection\protos\*.proto
for ($i=0; $i -lt $files.Count; $i++) {
    $item = $files[$i].Name
    protoc --python_out='.' ./object_detection/protos/$item
}
`
