### ISSUE TITLE
Has this repo implemented Mask RCNN?

### ISSUE THREAD

**Issue by bytesoftly** [tensorflow/models#1974]
I see several references to Mask RCNN in files such as [here](https://github.com/tensorflow/models/blob/master/object_detection/core/box_predictor.py):

    class MaskRCNNBoxPredictor(BoxPredictor):
      """Mask R-CNN Box Predictor.
          See Mask R-CNN: He, K., Gkioxari, G., Dollar, P., & Girshick, R. (2017).
          Mask R-CNN. arXiv preprint arXiv:1703.06870.
          ...

...yet I cannot find any documentation on how to train/use this API to produce masks around segments in an image.

How can I use the Mask RCNN functionality?

Thanks!

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

The `MaskRCNNBoxPredictor` class being alluded to is not part of the TensorFlow APIs (www.tensorflow.org/api_docs), but instead part of the implementation of the Object Detection models. @derekjchow can correct me if I'm wrong, but we may not have the bandwidth to provide additional support or documentation for using internal implementation details at this time, so you'll probably best off looking at the source code. Hope that helps.
