### ISSUE TITLE
Own dataset preparation for attention_ocr

### ISSUE THREAD

**Issue by kjanjua26** [tensorflow/models#1996]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes, I did write one. 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
Installed from source. 

- **TensorFlow version (use command below)**:
Tensorflow v1.12
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:

- **GPU model and memory**:
TITAN X and 12 GB

- **Exact command to reproduce**:
To prepare dataset such as the fsns dataset used in attention_ocr. 

### Describe the problem
I have the dataset in one folder as .png images and have groundtruth as .txt files in the same folder as the images. I want to create the dataset same as that of fsns so that I can fine tune the attention_ocr model. I did run the fsns.py script which is provided and wrote down the newdataset script which is already mentioned in README.md, but of no use. Any one can tell me the proper steps to follow?
I read the stack overflow answer, no use still.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(If the larger community there hasn't answered, then I'm afraid you might be on your own. That said, if you do figure this out, we'd encourage you to contribute back to code/documentation so other users can benefit. Thanks!)
