### ISSUE TITLE
slim multi GPU training is slower than single GPU

### ISSUE THREAD

**Issue by neouyghur** [tensorflow/models#2018]
Why multi GPU training is slower than single GPU?

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. In particular, please provide instructions to reproduce the problem you are observing (such as the code that demonstrates the speed difference between multi and single GPU training and details about the multi-GPU setup being used).  Thank you.

**Comment by neouyghur** [comment]
@asimshankar I saw a similar problem in here https://stackoverflow.com/q/43405358/3043749. It is written with more details. And there is an answer, and I don't know it is a correct one. Thanks.
