### ISSUE TITLE
What should be the desirable size of an input image ?

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2049]
I tried to input images around size 3 -5 Mb. My training operation failed on the cloud giving errors . So what should be the desirable size of inputs ?

**Comment by reedwm** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

In particular, what model are you training on? What is the exact command you're running?

**Comment by yanfengliu** [comment]
@shamanez  It really depends on your model configuration and the hardware you are using. A lot of things can cause the hardware to run out of memory, for example, 

- Model complexity
- Batch size 
- Image resolution

**Comment by shamanez** [comment]
I am using the training pet data set tutorial steps to train my own data set. I want to train this on the cloud . I noticed that images in pet data set are small in (below 50Kb) and around (400*800) in size . 

I took phots with 13MP camera and created my own Tf.Record file. But when I deployed in on the cloud it always gave me memory issues .  Then I reduce the image quality and size both.  Then it worked . No errors ! My question is there a range I should consider when training it on the cloud ?

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

As @yanfengliu said, it depends on your model and hardware. But it seems you already found a range for your configuration:  the original images are too large, and the size you reduced it to works. You should ask on StackOverflow (with lots of details, such as the model and code you are using and the cloud you are running on) for more help.
