### ISSUE TITLE
tensorflow/models/attention_ocr test.py

### ISSUE THREAD

**Issue by znliunwpugmail** [tensorflow/models#2059]
I have already trained from scratch:
python train.py
 And How can I predict characters using testing data.
Can you give me test.py?

**Comment by reedwm** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

Anyway, you can evaluate with [this file](https://github.com/tensorflow/models/blob/master/attention_ocr/python/eval.py), and for inference you can follow the directions under the [How to use a pre-trained model](https://github.com/tensorflow/models/tree/master/attention_ocr#how-to-use-a-pre-trained-model) section. Ask on StackOverflow if you have more questions.
