### ISSUE TITLE
ResNet architecture

### ISSUE THREAD

**Issue by ameliajimenez** [tensorflow/models#2072]
Hello,

Why does the first convolution of ResNet have a kernel 3x3 (instead of 7x7), 16 filters (instead of 64) and stride 1 (instead of 2)?
x = self._conv('init_conv', x, 3, 3, 16, self._stride_arr(1))

and why there is no max_pool operation after it?

Thanks in advance!

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request of TensorFlow. This is more of a question about the research decisions in the ResNet paper (you could ask the original authors). StackOverflow also has a larger community that reads questions there. Thanks!

**Comment by hughbzhang** [comment]
@aselle I think this question is actually asking why the tensorflow/models implementation does not follow the original network structure.

As per http://ethereon.github.io/netscope/#/gist/b21e2aae116dc1ac7b50 (directly from the first author He Kaiming's github) and the original paper (https://arxiv.org/pdf/1512.03385.pdf), the first conv is indeed 7x7 with 64 channels, stride 2.

**Comment by amejs** [comment]
Exactly, my question was regarding why the architecture implemented is different from the one on the original paper. Cheers!

**Comment by panyx0718** [comment]
Are you asking the ResNet for CIFAR10? The ResNet architecutre for CIFAR10 starts with conv3x3 if you read the paper carefully.
