### ISSUE TITLE
What is the batch size for model slim multi gpu setting?

### ISSUE THREAD

**Issue by gaopeng-eugene** [tensorflow/models#2086]
In the model slim repository, multi gpu is supported. The real batch size should be batch size * number of clones, right?

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Amitayus** [comment]
I also ask this problem. It appears that the real batch size is batch_size * num_clones rather than merely batch_size. It's ok when I run my code using 4 GPUs, setting --batch_size=16 and --num_clones=4 whereas failed when I change the --batch_size=20. So the **max batch_size of 4 GPUs** is around 16. But when I running my code using 2 GPUs, it's also ok when setting --batch_size=16 and failed (OOM error) when I setting --batch_size=20. So the **max batch_size of 2 GPUs** is also around 16.
