### ISSUE TITLE
Adding optimization / quantization as an option to export_inference_graph.py script in object detection API?

### ISSUE THREAD

**Issue by shamanez** [tensorflow/models#2201]
How to qunatize a frozen graph in object detection API. In above script it's not optimizing . Can you add it as **# a feature.** 

If it's not the case do we need to follow the normal procedure to follow the quantization ?

**Comment by suharshs** [comment]
What optimization/quantization are you trying to use?

If you want to quantize for inference, you may want to try taking the frozen graph and using the graph transforms tool : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md

If that works, someone may be able to make that part of the export_inference_graph script?

**Comment by shamanez** [comment]
Yeah I was talking about can't we add the [this ](https://www.tensorflow.org/performance/quantization)  to export_inference_graph script . It will be easier just a flag .

**Comment by suharshs** [comment]
For now I don't think we want this to be a default flag in the export_inference_graph script because quantization hasn't been tested with that model yet. So, for now, please relying on using the graph_transform tool for quantization.

The script does output a frozen graph so the graph_transform tool should be able to make arbitrary post-export changes. We should probably err towards not adding all platform specific possibilities as options in script for now.

Thanks!
