### ISSUE TITLE
Error:('all elements of boxlists should be BoxList objects')

### ISSUE THREAD

**Issue by Walid-Ahmed** [tensorflow/models#2429]
Hello,

I am getting the following error when I train: 

> object_detection/core/box_list_ops.py", line 533, in concatenate
>     raise ValueError('all elements of boxlists should be BoxList objects')
> ValueError: all elements of boxlists should be BoxList objects
> 

Can someone help?﻿

System information:
TF 1.3.0
MacOS Sierra

**Comment by poxvoculi** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

Also, you are more likely to get a helpful reply if you provide a bit more detail about what you're doing.

**Comment by jinfanhahaha** [comment]
Excuse me, have you solved the problem now？
