### ISSUE TITLE
Unable to use multiple graphs in a session 

### ISSUE THREAD

**Issue by saikishor** [tensorflow/models#2507]
We are unable to use multiple graphs in a session, which would enable us to merge trained models. I would request this feature.

[Stackoverflow](https://stackoverflow.com/questions/46611649/how-to-combine-multiple-trained-models-of-tensorflow-api)

**Comment by reedwm** [comment]
In the StackOverflow question, it looks like you're trying to import multiple GraphDefs into the same graph, which is possible. For example, the following code imports two GraphDefs:
```python
import tensorflow as tf

with tf.Graph().as_default() as g1:
  tf.constant(1, name='x')
  g1_graphdef = g1.as_graph_def()

with tf.Graph().as_default() as g2:
  tf.constant(2, name='y')
  g2_graphdef = g2.as_graph_def()

with tf.Graph().as_default() as g3:
  x = tf.import_graph_def(g1_graphdef, return_elements=['x:0'])[0]
  y = tf.import_graph_def(g2_graphdef, return_elements=['y:0'])[0]
  with tf.Session() as sess:
    print sess.run([x, y])
```
So, you're issue is caused by something else. If you are still having the issue, please file a new issue with a minimal code sample that reproduces the problem
