### ISSUE TITLE
ImageNet Preprocessing Script

### ISSUE THREAD

**Issue by MichaelX99** [tensorflow/models#2525]
I just wanted to let you all know that the imagenet download and preprocess step in SLIM does not work.  Something seems to be wrong with the build file.  The code works in the inception directory but i not in slim.

**Comment by reedwm** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by kechan** [comment]
I have also problem running:

bazel build slim/download_and_preprocess_imagenet 

The first thing i noticed is in the BUILD under slim, I can't find any mention of download_and_preprocess_imagenet. 

The one under inception directory seemed to work, but would it output things in "slim" format?

**Comment by reedwm** [comment]
When I run `bazel build slim/download_and_convert_imagenet`, I get the errror

```
ERROR: /usr/local/google/home/reedwm/models/research/slim/BUILD:34:1: no such package 'tensorflow': BUILD file not found on package path and referenced by '//research/slim:build_imagenet_data'
ERROR: Analysis of target '//research/slim:download_and_convert_imagenet' failed; build aborted: no such package 'tensorflow': BUILD file not found on package path
INFO: Elapsed time: 0.323s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

@derekjchow, can you take a look? The `//tensorflow` causing the error was added in https://github.com/tensorflow/models/commit/87252d5affbe6f00db7e458b7bc2ae16a527a9e2.

**Comment by joel-shor** [comment]
This should be partially or completely fixed by https://github.com/tensorflow/models/pull/2902

**Comment by wt-huang** [comment]
Closing as this is resolved
