### ISSUE TITLE
InvalidArgumentError (see above for traceback): assertion failed: [maximum box coordinate value is larger than 1.01: ] [1.0111111]

### ISSUE THREAD

**Issue by nikhiljaiswal** [tensorflow/models#2625]
I'm having the above error when I use any of the following:
faster_rcnn_inception_resnet_v2_atrous_coco
rfcn_resnet101_coco

But NOT when I use:
ssd_inception_v2_coco
ssd_mobilenet_v1_coco

Please help.﻿
Show less
REPLY

**Comment by cipri-tom** [comment]
This repository is related for issues with the API. Please complete the whole issue template if you think there is a problem with the implementation, or address your questions on StackOverflow.

The problem is likely with your data, in the sense that you may have forgotten to encode your coordinates relatively to the image.
As far as I can see in the source code, only the Faster RCNN uses the `to_absolute_coordinates` functions, which throws the error in your title.

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
