### ISSUE TITLE
can not import retrained graph.pb into object detection notebook.

### ISSUE THREAD

**Issue by malehmir** [tensorflow/models#2700]
I am trying to import graph.pb that I generated with Tensorflow-for-poets into this object_detection notebook, however I'm getting this error

`KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."`

Do I have to freeze my graph? or create TFRecords?
Appreciate your time!

**Comment by bignamehyp** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by malehmir** [comment]
I use pip version of tensorflow on a tensorflow virtual environment (python3.5) on Ubuntu 16.04. I was able to successfully run the jupyter notebook for pet detection. I trained a graph using tensorflow-for-poets python instruction that works great and classifies without any problem. When I imported that graph.pb and its label.txt to the object_detection_api, it gave me this error:
`KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."`

I don't know what is wrong with my graph.pb that doesn't work on objection detection API?
on the side note, is there any other way to extract the ROI using my trained graph?

Thank you.

**Comment by bignamehyp** [comment]
@tombstone can you please take a look? Thanks.

**Comment by tombstone** [comment]
@malehmir  Tensorflow-for-poets is for a classification model. We do not support its use in object_detection notebook.

Details:
-----------
In object detection API, for inference, we have strict definitions of input and output nodes which you can see in object_detection/export_inference_graph.py script. Your model does not have these nodes. What you could do however, is to find out the input and output nodes in your graph and modify the notebook accordingly.
