### ISSUE TITLE
Example ptb_word_lm.py 'module' object has no attribute 'RNNParamsSaveable'

### ISSUE THREAD

**Issue by avolkov1** [tensorflow/models#2712]
https://github.com/tensorflow/models/blob/9557674c73eb57540672a74366afcab359cb9fd1/tutorials/rnn/ptb/ptb_word_lm.py#L271

Please update the example to be compatible with TF 1.4. Getting error:
```
AttributeError: 'module' object has no attribute 'RNNParamsSaveable'
```
Tried various permutations with `CudnnLSTMSaveable` and couldn't get it to work.

**Comment by bignamehyp** [comment]
Which TF version are you using?

Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by avolkov1** [comment]
Thanks for replying.

I'm using TF 1.4 at commit "756a7fc6370826bcd3dcd155568011077f9928b1". I compiled it from source a few weeks ago on CentOS 7.3.1611. Yeah, I understand regarding the template (I don't have time for that), but basically that class `RNNParamsSaveable` has been removed in TF 1.4, and it's supposed to be replaced via `CudnnLSTMSaveable`, but I couldn't get it to work. So could someone please update this `ptb_word_lm.py` example to use  `CudnnLSTMSaveable` instead of  `RNNParamsSaveable`. To run and reproduce the error follow the instructions at the top of  `ptb_word_lm.py` and run it under TF 1.4 version (any 1.4 version should suffice).
```
The data required for this example is in the data/ dir of the
PTB dataset from Tomas Mikolov's webpage:
$ wget http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz
$ tar xvf simple-examples.tgz
To run:
$ python ptb_word_lm.py --data_path=simple-examples/data/
```

There is an issue sort of relevant to this issue, but no details and documentation is lacking about how to use the new API. [https://github.com/tensorflow/tensorflow/issues/13254](https://github.com/tensorflow/tensorflow/issues/13254)

Refer to @protoget comment:
[https://github.com/tensorflow/tensorflow/issues/13254#issuecomment-341632608](https://github.com/tensorflow/tensorflow/issues/13254#issuecomment-341632608)

**Comment by bignamehyp** [comment]
RNNParamsSaveable is deprecated. Please look out for the new cudnn_rnn layer APIs which takes care of cudnn opaque variable saving.

**Comment by avolkov1** [comment]
RNNParamsSaveable is not deprecated, it's completely missing in TF 1.4.This is not helpful, but whatever. I'll be on the lookout.
Seems another issue has popped up already. Issue #2709
