### ISSUE TITLE
SyntaxNet dockerfile not building

### ISSUE THREAD

**Issue by MathiasDesch** [tensorflow/models#2715]
I am unable to build the current version of Syntaxnet using the Dockerfile.
A first issue is that `libpng12-dev` does not exist anymore. 
A second issue (is I replace `libpng12-dev` to `libpng-dev`) is the during the build using syntaxnet.

I think there might have been some update of tensorflow without checking if everything is working properly. 

Does anyone succeed to build syntaxnet ? @bogatyy is the commit 4594a1ea58f7a8df67d4c1112f34dd4c12c35225 might be the cause of the problem.

I have tried to checkout previous commit without success.

**Comment by angersson** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by bogatyy** [comment]
@MathiasDesch thanks for the fix!
