### ISSUE TITLE
Scores for classes are so weak and api does not create boxes.

### ISSUE THREAD

**Issue by Rasoul20sh** [tensorflow/models#2781]
After updating tensorflow to 1.4.0, I run object_detection api but the scores for classes are so weak for 'ssd_inception_v2_coco_2017_11_08' and 'ssd_mobilenet_v1_coco_2017_11_08' (even for its test classes). Therefore it do not create any boxes inoutput. It is just fine for other models like 'faster_rcnn_inception_v2_coco_2017_11_08'. Whats the problem?

**Comment by erickvinsan** [comment]
I'm walking through that error to! I have opened another issue before read yours. But I think this will reinforce the solution.

**Comment by Rasoul20sh** [comment]
I do my job with an older version of 'ssd_mobilenet..' and it was ok. you can use this one until they correct probable bugs.
this is the link,
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_11_06_2017.tar.gz

**Comment by tombstone** [comment]
@Rasoul20sh  @erickvinsan  Can you confirm if you are on the latest object detection code and have also recompiled the protos using `protoc object_detection/protos/*.proto --python_out=.`

**Comment by Rasoul20sh** [comment]
Yes, with older version of 'ssd_mobilenet..' (I mean ssd_mobilenet_v1_coco_11_06_2017.tar.gz)  and changing the model name in the code to MODEL_NAME = 'ssd_mobilenet_v1_coco_11_06_2017' , scores are good and boxes would be created.

**Comment by cy89** [comment]
There appears to be a related discussion with a similar workaround (use the older version) in #2779.

**Comment by Rasoul20sh** [comment]
>close #2781

**Comment by tombstone** [comment]
Please try the new ssd models from the zoo. That should fix the problem.

**Comment by Rasoul20sh** [comment]
Thanks alot

**Comment by FoilHao** [comment]
I am using ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14 and encounter the same problem.
Have you checked the scores in the output of the model?
Because when testing results I print my scores and find them very weak and close(about 0.004, seeing below)
[[0.00419687 0.00418497 0.00418139 0.00417583 0.00416805 0.00415858
0.00415558 0.00415351 0.00413164 0.00413113 0.00412714 0.00411862
0.00411856 0.00411649 0.00411184 0.00411016 0.0041098 0.00410919
0.00409758 0.00409442 0.0040899 0.00408842 0.00408763 0.00408626
0.00408024 0.00407811 0.00407482 0.00407472 0.0040736 0.00406982
0.00406742 0.00406425 0.00406279 0.00406104 0.00406103 0.00405826
0.00405772 0.0040577 0.00405703 0.00405589 0.0040556 0.00405431
0.00405431 0.00405312 0.00405309 0.00405135 0.00405067 0.00404945
0.00404913 0.00404735 0.00404232 0.00404043 0.00403672 0.00403497
0.00403496 0.00403377 0.00403241 0.00403187 0.00402924 0.00402779
0.00402603 0.00402491 0.00402476 0.00402465 0.00402272 0.00401924
0.00401717 0.0040153 0.00401324 0.0040128 0.00401214 0.00400906
0.00400729 0.00400648 0.0039996 0.00399941 0.00399737 0.00399632
0.0039911 0.00398869 0.00398591 0.00398581 0.00398468 0.00398437
0.00398409 0.00398409 0.00398229 0.00398111 0.00397723 0.00397705
0.00397654 0.00397599 0.00397588 0.00397508 0.0039742 0.0039735
0.00397325 0.00397292 0.00397287 0.00397195]]
So is this also a bug of the model? Shall I change another model?
