### ISSUE TITLE
Cannot freeze embedded_ssd_mobilenet_v1

### ISSUE THREAD

**Issue by mpeniak** [tensorflow/models#2790]
I cannot freeze embedded_ssd_mobilenet_v1. Previously I would get this:

https://github.com/tensorflow/models/issues/2777

but after reverting to previous version of that file I get error specified in this thread:

https://github.com/tensorflow/models/issues/2774

I have tried all possible combinations of versions of tf as well as models repo but no luck. 
Any ideas what to do and how to freeze this model?

**Comment by rohan100jain** [comment]
When you're using TF v1.4, what is the behaviour?

**Comment by mpeniak** [comment]
Using 1.4 TF and the latest models verison of the repo I get the folliowing:

Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 96, in <module>
    tf.app.flags.mark_flag_as_required('pipeline_config_path')
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'mark_flag_as_required'

**Comment by hugosimasalmeida** [comment]
I have the same issue but with a previous version of tensorflow (this issue was not there before so i am unsure what changed (was it an update on protobuf version?), tried on ubuntu14.04 with GPU and Mac os with CPU and i have the same error):
python3 export_inference_graph.py \
>     --input_type image_tensor \
>     --pipeline_config_path training/ssd_inception_v2.config \
>     --trained_checkpoint_prefix training/model.ckpt-5490 \
>     --output_directory wt_corrosao
Traceback (most recent call last):
  File "export_inference_graph.py", line 96, in <module>
    tf.app.flags.mark_flag_as_required('pipeline_config_path')
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'mark_flag_as_required'
(/Users/hugosimasalmeida/anaconda3/envs/pipenv) python3 -c 'import tensorflow as tf; print(tf.__version__)'
My setup is using anaconda virtual environment with:
Python3.5
tf 1.3.0
protobuf 3.5
matplotlib 2.1
tflearn 0.3.2
six 1.11
pillow 4.3
pandas 0.23
opencv 3.1
lxml 4.1.1
jupyter 1

If i comment out the flags then i can't get the jupyter notebook object_detection_tutorial to work with my model. On that scenario (of commenting out the flags when exporting the inference graph) i get the label_map_util.py issue as it is can't decode de string on label map (line 117 of that file).

**Comment by drpngx** [comment]
@petewarden any idea?

**Comment by Robinxin123** [comment]
i got the same problem, have you solve it now?
