### ISSUE TITLE
no such package '@protobuf//' when installed syntaxnet from source

### ISSUE THREAD

**Issue by wujun** [tensorflow/models#283]
## Please let us know which model this issue is about (specify the top-level directory)
syntaxnet

my envrinoment: ubuntu==15.10, bazel==0.2.2b, protobuf==0.3.0.0b2 and I've confirmed that the network is no problem. while I run bazel test syntaxnet/... util/utf8/... I got the following error every time.

ERROR: package contains errors: syntaxnet.
ERROR: no such package '@protobuf//': Error cloning repository: https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/googl
e/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack.
INFO: Elapsed time: 1.421s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by zqma** [comment]
had the same issue. bazel=0.2.1, protobuff=3.0.0b2, RHEL 6.5.
both https_proxy and http_proxy are set to the proxy addresses in /etc/environment
please help.

**Comment by zqma** [comment]
update to bazel=3.0 solved this problem.

**Comment by makrandgupta** [comment]
I'm running into the same issue and upgrading to bazel=0.3 does not solve it for me. Any idea why this is happening? I dont have any proxy set up.

**Comment by Narsil** [comment]
Just solved it by deleting and repulling the repo..

**Comment by jsgreenawalt** [comment]
Same issue, same OS, same versions as wujun.  I'm using Anaconda "Python 2.7.12 :: Anaconda 4.1.1 (64-bit)"  I've tried and retried everything that comes up when googling for a solution; no dice, no progress, nothing seems to clear this error.  I've also tried manually cloning the protobuf repo and copying it pretty much anywhere/everywhere in the tree.   Maybe the developers would care to share what OS and software versions can be used to get past this?  Somebody must have a 'correct' software environment to get this to build?

**Comment by makrandgupta** [comment]
Managed to build it successfully in two environments. One was an Ubuntu 14.04 Server VM. I just followed all the steps and got no errors. Tried the same on a VM on a different host and ran into the error above. Second successful build was using a docker container on a OSX machine.

**Comment by jsgreenawalt** [comment]
@makrandgupta thanks for the info -- I'll retry w/ Ubuntu 14.04 Server.  What I find really baffling is that I'm not behind any kind of proxy, and a manual git clone of protobuf at the same url as given in the error succeeds just fine... but I can't find any way to get bazel to see that the package is already there.  I've been digging into these build scripts trying to find some workaround

**Comment by BrightFeather** [comment]
@jsgreenawalt I'm stuck here. Can you tell in more detail how you get through it? Is internet connection a must while doing fetch?

**Comment by vitojph** [comment]
Same problem here :-( Any hint to solve this? I'm using  virtualenv on Ubuntu==15.10, python=2.7.10, bazel==0.3.1, protobuf==3.0.0b2

   $ bazel test syntaxnet/... util/utf8/...
   ..
   ERROR: package contains errors: syntaxnet.
   ERROR: error loading package 'syntaxnet': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error cloning repository: https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack caused by java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty caused by the trustAnchors parameter must be non-empty.
   INFO: Elapsed time: 2.639s
   ERROR: Couldn't start the build. Unable to run tests.
