### ISSUE TITLE
Is there a similar API for C/C++

### ISSUE THREAD

**Issue by scotthuang1989** [tensorflow/models#2899]
I can only find python API for object detection with TF. If I want do this with c/c++, if there a similar API?

**Comment by tatatodd** [comment]
@scotthuang1989 Note that since object_detection is just loading and running a frozen graph, in concept you should be able to just use the regular TensorFlow C++ support:
https://www.tensorflow.org/api_guides/cc/guide

That said, the python object_detection API provides some nice utilities and stuff like that.

@jch1 @tombstone @derekjchow do we have any plans for C++ support?

**Comment by sorny92** [comment]
Maybe #1741 can help you. There's a C++ example.

**Comment by tatatodd** [comment]
Ah nice, thanks @sorny92 for the link!

I'm closing this out since this really is a dup of #1741 (sorry, I should have found that earlier).  If there are any follow-ups, they should go on that issue.
