### ISSUE TITLE
[Slim] There is no op named "input" in custom trained inception v3 model on custom data.

### ISSUE THREAD

**Issue by SnShine** [tensorflow/models#2913]
Hello,

(Following the read me here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image)

I've trained inception v3 model from scratch with custom data and ran eval code. It worked fine and gave good results.

When I'm trying to run inference via `feed_dict`, I have to find the tensor named "input" as shown in tutorials and Slim Readme.md. However, I couldn't find an op named `input` in my `frozen.pb` model.

Although, it worked perfectly fine when using pre-trained inception model by following readme here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image. By failed on my custom build model.

After digging, I realized that it is a placeholder op. Do we have to add it to the model before training? Or can we add it to `forzen.pb` file? Any idea how to add this placeholder op to `inception_v3` or `inception_v3_base`?

Thanks. :)

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by SnShine** [comment]
Is there any way we can encourage some questions in here? Lack of proper documentation is one reason for this question.
Someone would work on documentation if issues like this are allowed on GitHub.

**Comment by tatatodd** [comment]
I do sympathize with the need for more documentation.  We're making efforts in that regard.

In case you missed it, below is the template that's auto-filled when you click on "New issue" on github.  This attempts to explain our policy.  Also note that we regularly monitor StackOverflow issues, just as we do for github issues.

AUTO-FILLED TEMPLATE BELOW
---

Please go to Stack Overflow for help and support:

http://stackoverflow.com/questions/tagged/tensorflow

Also, please understand that many of the models included in this repository are experimental and research-style code. If you open a GitHub issue, here is our policy:

1. It must be a bug or a feature request.
2. The form below must be filled out.

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by lironsamara** [comment]
Hi SnShine, 

I also didn't find an op named input in my frozen.pb model when training inception v3 from scratch . Did you find an answer for this issue?

Thanks!
