### ISSUE TITLE
visualization_utils.py change font size but still does not work.

### ISSUE THREAD

**Issue by cindysillence** [tensorflow/models#2921]
hallo
I just run the object_detection_tutorial.ipynb script , but the text in the bounding box is too small and not clear. So I go to **/visualization_utils.py ** script to change the font size to "font = ImageFont.truetype('arial.ttf', 24)" but it still does not work. 

how can I do it right now?

waiting for help

cindy chen

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ifnull** [comment]
This is a bug. `ImageFont.truetype('arial.ttf', 24)` fails because `arial.ttf` does not exist in the repo throwing a `IOError: cannot open resource` exception. As a result, `ImageFont.load_default()` is called every time. 

@cindysillence you could just drop a copy of `arial.ttf` from your system folder in the `./research` directory. This should cause `ImageFont.truetype()` to load `arial.ttf` correctly and then successfully set the font size.
