### ISSUE TITLE
feature requests: inference in batch mode in im2txt?

### ISSUE THREAD

**Issue by vanpersie32** [tensorflow/models#2923]
According to [https://github.com/tensorflow/models/blob/master/research/im2txt/im2txt/inference_utils/caption_generator.py](https://github.com/tensorflow/models/blob/master/research/im2txt/im2txt/inference_utils/caption_generator.py),  inference in im2txt is done in single image mode, not in batch mode. 

System information:
    OS Platform and Distribution : Linux Ubuntu 14.04
    8  Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    python 2.7.6
    TensorFlow installed from  binary
    TensorFlow version: 1.01
    CUDA version: cuda8.0
    cuDNN version: cudnn5.0
    GPU model and memory: titanx black/ 12GB

Test about 0.3s per image in inference. I think it so slow and I want to speed inference step by doing it in batch mode.

**Comment by tatatodd** [comment]
@cshallue might be able to tell us how feasible this is.

**Comment by cshallue** [comment]
In inference mode a single image is actually a batch of captions because we use beam search. For example, if beam_size=100 then inference for that image uses a batch size of 100 captions. This code is just one example of running inference for generating captions, and is not meant to cover all use cases.

**Comment by vanpersie32** [comment]
Thanks for your reply. I agree with you.
