### ISSUE TITLE
Segmentation fault while training with 22 classes an large dataset

### ISSUE THREAD

**Issue by SumanyuShukla** [tensorflow/models#2955]
When I am training with 22 classes with around 8000 images while training it is using entire memory and showing segmentation fault, even with batch size 1 it is not working. I am using ssd mobilenet model and its configuration file provided by tensorflow.

**Comment by aselle** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by SumanyuShukla** [comment]
Tensorflow version 3.5
Ubuntu OS 16.04
Installed from source
exact command-
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/c.config
