### ISSUE TITLE
Object_detection: Corrupt JPEG data: 240 extraneous bytes before marker 0xd9.

### ISSUE THREAD

**Issue by WZMIAOMIAO** [tensorflow/models#3134]
### System information
- **What is the top-level directory of the model you are using**:   /home/xx/models
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu16.04
- **Python version**: python 3.5
- **TensorFlow installed from (source or binary)**: install from pip3 install xxxxx
- **TensorFlow version (use command below)**: Tensorflow v1.4.0-19-ga52c8d9 1.4.1
- **Bazel version (if compiling from source)**: No
- **CUDA/cuDNN version**: CUDA 8 / cuDNN 6
- **GPU model and memory**: GTX 1060 6G
- **Exact command to reproduce**:  # From the tensorflow/models/research/ directory
python object_detection/eval.py 
    --logtostderr 
    --pipeline_config_path=/home/xx/faster-rcnn/config/pets.config 
    --checkpoint_dir=/home/xx/faster-rcnn/save_train_2018 
    --eval_dir=/home/xx/faster-rcnn/save_eval_2018

### Describe the problem
When working on the pet data set, I have successfully run the training job, according to Running Locally. But when I run the evaluation job, I got a problem. Corrupt JPEG data: 240 extraneous bytes before marker 0xd9.
When I use VOC data set, I don't get this problem, meanwhile I don't get any evaluation informations.

### Source code / logs
Runing eval.py, some information follow  (pet data set):
2018-01-06 18:26:33.614505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /home/xx/faster-rcnn/save_train_2018/model.ckpt-5000
INFO:tensorflow:Restoring parameters from /home/xx/faster-rcnn/save_train_2018/model.ckpt-5000
Corrupt JPEG data: 240 extraneous bytes before marker 0xd9
Corrupt JPEG data: 240 extraneous bytes before marker 0xd9

Runing eval.py, some information follow  (VOC data set):
INFO:tensorflow:Restoring parameters from /home/xx/VOC/train_2018/model.ckpt-5000
INFO:tensorflow:Restoring parameters from /home/xx/VOC/train_2018/model.ckpt-5000
xx@xx-System:~/models/research$

**Comment by cy89** [comment]
@jch1 @tombstone, PTAL.

**Comment by jason-zhu** [comment]
Hi, I got the same problem. Error "Corrupt JPEG data: 240 extraneous bytes before marker 0xd9" appears and I didn't get the eval result.
I checked the pet images and found there are some error jpgs, such as Abyssinian_5.jpg.

**Comment by Tomlin0110** [comment]
@jason-zhu 
Hi, I also get this error message while I trained my dataset on SSD_mobilenet_v2
how can I find the error jpeg by some lib or pass this batch when training

**Comment by carlosprados11** [comment]
Hi, this is because there are some images in the pet dataset that don't have a proper format. Some of them are actually .png files instead .jpg, even though they are in .jpg extension. These images are:

Egyptian_Mau_14, 139, 145, 156, 167, 177, 186, 191;
Abyssinian_5, 34.

Other images are also corrupted even though the extension is good:

chihuahua_121 
beagle_116

You should remove these images. 
Remove also the .xml and the trimaps files related to these images. And remove their names from 'list.txt' and 'trainval.txt'. Everything is inside the 'annotations' folder

When you remove them, generate again the TFRecords files:
`python3 object_detection/dataset_tools/create_pet_tf_record.py --label_map_path=object_detection/data/pet_label_map.pbtxt --data_dir=`pwd` --output_dir=`pwd``

And copy into your working folder.

**Comment by KarmakarDeepak** [comment]
I removed only these 2 xml and images
chihuahua_121
beagle_116

**Comment by zzh805780186** [comment]
> I removed only these 2 xml and images chihuahua_121 beagle_116
I use PIL read images and convert to RGB format , then cv2 can read the two images.

img = Image.open(img_path)
img = img.convert('RGB')
