### ISSUE TITLE
why faster_rcnn_inception_resnet_v2_atrous_lowproposals_oid model cost so much time when I test it under gpu?

### ISSUE THREAD

**Issue by houxiaoxia1** [tensorflow/models#3146]
hi,  all. Could you tell me why it costs so much time when I test faster_rcnn_inception_resnet_v2_atrous_lowproposals_oid model under gpu, it takes about 29s per picture while https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md tell me it takes only 347ms. Thank you.

**Comment by cy89** [comment]
@houxiaoxia1 aside from referring you to StackOverflow, have you tried profiling your code to see where it spends its time? Look for the TF timeline tool. 

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
