### ISSUE TITLE
Bad performance of object detection API.

### ISSUE THREAD

**Issue by aastalin** [tensorflow/models#3243]
We use object detect API with ssd_mobilenet_v1_coco on TITAN Z.
Our result is around 75ms, far from the score mentioned on this page:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

Could you share more information about how to reproduce the 30ms results with ssd_mobilenet_v1_coco?
We are using TensorFlow-1.4 and CUDA 8.0.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

In particular note this section of the page you referenced:

model speed --- we report running time in ms per 600x600 image (including all pre and post-processing), but please be aware that these timings depend highly on one's specific hardware configuration (these timings were performed using an Nvidia GeForce GTX TITAN X card) and should be treated more as relative timings in many cases.

**Comment by madhavajay** [comment]
I am having similarly bad performance.
On my Macbook Pro in Tensorflow CPU model I get:
Inference time 0.13113617897033691 sec
On an AWS px2.large K80 GPU instance im getting:
Inference time 0.08756685256958008 sec

Tensorflow GPU is installed and says its connected and I see the process in the nvidia-smi tool.

Anyone have an idea why inference is so slow on GPU?
Is it simply not possible to do it faster? Thats like 12 fps on a K80...
