### ISSUE TITLE
"ValueError: model_dir should be non-empty" for RNN for Drawing Classification

### ISSUE THREAD

**Issue by noumanriazkhan** [tensorflow/models#3253]
### System information
- **What is the top-level directory of the model you are using**: ~/networks/autodraw$
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**:1.4.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0.61
- **GPU model and memory**: Tesla K80 / 24 GB
- **Exact command to reproduce**: 

### Describe the problem
I followed the tutorial as it is but its giving me "ValueError: model_dir should be non-empty".

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

I also suggest you provide more details, e.g. a link to the documentation you're following, and the exact command that produced the error.

**Comment by noumanriazkhan** [comment]
Well I simply follow the tutorial https://www.tensorflow.org/versions/master/tutorials/recurrent_quickdraw

**Comment by noumanriazkhan** [comment]
The issue has been resolved by making a new directory and mentioning it in the --model_dir flag.

**Comment by jurschreuder** [comment]
this is referring to --output-dir, had this issue when the --output-dir was not local, but /home/me/etc/etc
