### ISSUE TITLE
7x1 and 1x7 filters mixed up in Inception v4

### ISSUE THREAD

**Issue by rs1024** [tensorflow/models#3313]
I noticed several places where the filter order is mixed up in Inception v4. For example, in the Inception-B block, branch 2 filters are in the order of: 1x1, 7x1, 1x7, 7x1, 1x7; however, in the paper, the order is described as: 1x1, 1x7, 7x1, 1x7, 7x1. There are a few other occurrences throughout the model.

Is there any reason for this?

**Comment by reedwm** [comment]
/CC @sguada, can you take a look?

**Comment by GeorgeARM** [comment]
Noticed the same issue in the Inception-B block. In the provided model, in `Branch_1` instead of performing a `1x7` followed by `1x7` , a `1x7` followed by `7x1` is performed. Moreover in `Branch_2` the convolution filters are swapped. I assume that the output concept remains the same as the fms of a `1x7` convolution and `7x1` convolution are concatenated, but what is the reason behind this change? Better accuracy?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
