### ISSUE TITLE
proto buff compilation error

### ISSUE THREAD

**Issue by oja1** [tensorflow/models#3567]
object_detection/protos/*.proto: No such file or directory.this error occured even after setting the whole path
![screenshot 1](https://user-images.githubusercontent.com/37286601/37268921-4fbc2800-25ee-11e8-8c08-6f862f96e4b1.png)
i'm kinda new to this .I'll be really grateful if anyone solves my problem

**Comment by KishoreKaushal** [comment]
First of all bro this doesn't seems like a compilation error. You need to specify the locations properly.

As  given in the [installation documentation](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md):-

Protobuf Compilation:
The Tensorflow Object Detection API uses Protobufs to configure model and training parameters. Before the framework can be used, the Protobuf libraries must be compiled. This should be done by running the following command from the tensorflow/models/research/ directory:

```
# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.

```

Replace the above command as follows:
`<path-to-protoc>   <path-to-tensorflow\models\research>\object_detection\protos\*.proto --python_out=.`

**Remember to use ' \ ' instead of ' / ' while typing the path on windows.**

**Comment by saiharshanani** [comment]
If That doesn't work, Download the correct file: https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-win32.zip
Unzip it
Run the executable from the command line similar to my 2nd box above to compile the protobuf files for Python.

**Comment by elhammoumi** [comment]
I used protoc-3.3.0 instead of 3.5.1 and it worked.

**Comment by yousf95** [comment]
![sans](https://user-images.githubusercontent.com/36472645/43047568-061e955c-8dd1-11e8-9726-3820e2183df3.png)
quelq'un peut m'aider mercii !!

**Comment by ymodak** [comment]
Closing since the issue has been resolved. Feel free to reopen if the problem still persists. Thanks!
