### ISSUE TITLE
How to use multi nvidia-card to train?

### ISSUE THREAD

**Issue by shipeng-uestc** [tensorflow/models#3667]
I have 8 cards, when train on cityscapes datasets, I set batch_size=8,it still have ResourceExhaustedError.

`python deeplab/train.py \
    --logtostderr \
    --training_number_of_steps=90000 \
    --train_split="train" \
    --model_variant="xception_65" \
    --atrous_rates=12 \
    --atrous_rates=24 \
    --atrous_rates=36 \
    --output_stride=8 \
    --decoder_output_stride=4 \
    --train_crop_size=769 \
    --train_crop_size=769 \
    --train_batch_size=8 \
    --dataset="cityscapes" \
    --tf_initial_checkpoints=${PATH_TO_INITIAL_CHECKPOINT} \
    --train_logdir=${PATH_TO_TRAIN_DIR} \
    --dataset_dir=${PATH_TO_DATASET}`

**Comment by aquariusjay** [comment]
Please change num_clones = 8 (see [here](https://github.com/tensorflow/models/blob/master/research/deeplab/train.py#L38)).
Since you set train_batch_size = 8, then you will have 8 / 8 = 1 image per GPU.
Also, you could check [slim.deployment.model_deploy](https://github.com/tensorflow/models/blob/master/research/slim/deployment/model_deploy.py) for more details about multi-GPU training.
