### ISSUE TITLE
How to increase the fps rate in the object_detection_tutorial.ipynb file?

### ISSUE THREAD

**Issue by Sharma96** [tensorflow/models#3778]
The object_detection_tutorial.ipynb file runs but the fps(frame per second) is slow,is there any change with which the fps rate becomes moderate?
Thank you for your time.

**Comment by smitshilu** [comment]
That depends on your system configuration. Which GPUs are you using ?

**Comment by Sharma96** [comment]
I am not using any GPU,only CPU.But,it results the same even with the GPUs(comments of this video:https://www.youtube.com/watch?v=MyAOtvwTkT0&index=2&list=PLQVvvaa0QuDcNK5GeCQnxYnSSaar2tpku)
Can we change some parameters in the code to make it run faster?
Thank you for your time.

**Comment by kangshintae** [comment]
You have a similar problem with me.
I've seen and studied all of Sentdex's tutorials.
The model is learned from the data I have, but it is too slow to operate.
My graphics card is the GTX 1070 and the resolution of the video I put in the model is (1280, 720).
Is there a solution?

**Comment by smitshilu** [comment]
Have you installed GPU version of tensorflow? For realtime detection I would suggest NVIDIA 1080Ti >=8GB GPU. If you are using CPU it will run with <5 FPS

**Comment by kangshintae** [comment]
Yes, I installed a GPU version of tensorflow 1.5.0.
And I've even finished training. However, running uses only the memory of the GPU.
Is there any error in my source code?
==========================================================================
# coding: utf-8

import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
#import zipfile

from collections import defaultdict
#from io import StringIO
#from matplotlib import pyplot as plt
from PIL import Image

sys.path.append("..")
from object_detection.utils import ops as utils_ops

import cv2

path = "test.mp4"

cap = cv2.VideoCapture(path)

from utils import label_map_util

from utils import visualization_utils as vis_util

# What model to download.
MODEL_NAME = 'car_mobile_graph'

# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_CKPT = MODEL_NAME + '/frozen_inference_graph.pb'

# List of the strings that is used to add correct label for each box.
PATH_TO_LABELS = os.path.join('training', 'object-detection.pbtxt')

NUM_CLASSES = 1

detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)


def run_inference_for_single_image(image, graph):
  with graph.as_default():
    with tf.Session() as sess:
      # Get handles to input and output tensors
      ops = tf.get_default_graph().get_operations()
      all_tensor_names = {output.name for op in ops for output in op.outputs}
      tensor_dict = {}
      for key in [
          'num_detections', 'detection_boxes', 'detection_scores',
          'detection_classes', 'detection_masks'
      ]:
        tensor_name = key + ':0'
        if tensor_name in all_tensor_names:
          tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
              tensor_name)
      if 'detection_masks' in tensor_dict:
        # The following processing is only for single image
        detection_boxes = tf.squeeze(tensor_dict['detection_boxes'], [0])
        detection_masks = tf.squeeze(tensor_dict['detection_masks'], [0])
        # Reframe is required to translate mask from box coordinates to image coordinates and fit the image size.
        real_num_detection = tf.cast(tensor_dict['num_detections'][0], tf.int32)
        detection_boxes = tf.slice(detection_boxes, [0, 0], [real_num_detection, -1])
        detection_masks = tf.slice(detection_masks, [0, 0, 0], [real_num_detection, -1, -1])
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            detection_masks, detection_boxes, image.shape[0], image.shape[1])
        detection_masks_reframed = tf.cast(
            tf.greater(detection_masks_reframed, 0.5), tf.uint8)
        # Follow the convention by adding back the batch dimension
        tensor_dict['detection_masks'] = tf.expand_dims(
            detection_masks_reframed, 0)
      image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')

      # Run inference
      output_dict = sess.run(tensor_dict,
                             feed_dict={image_tensor: np.expand_dims(image, 0)})

      # all outputs are float32 numpy arrays, so convert types as appropriate
      output_dict['num_detections'] = int(output_dict['num_detections'][0])
      output_dict['detection_classes'] = output_dict[
          'detection_classes'][0].astype(np.uint8)
      output_dict['detection_boxes'] = output_dict['detection_boxes'][0]
      output_dict['detection_scores'] = output_dict['detection_scores'][0]
      if 'detection_masks' in output_dict:
        output_dict['detection_masks'] = output_dict['detection_masks'][0]
  return output_dict


fourcc = cv2.VideoWriter_fourcc(*'XVID')
output = cv2.VideoWriter('output.avi', fourcc, 14.9810442644, (1280, 720))

while True:
  ret, image_np = cap.read()

  image_np = cv2.resize(image_np, (800, 600))
  # Expand dimensions since the model expects images to have shape: [1, None, None, 3]

  image_np_expanded = np.expand_dims(image_np, axis=0)

  # Actual detection.
  output_dict = run_inference_for_single_image(image_np, detection_graph)
  # Visualization of the results of a detection.
  vis_util.visualize_boxes_and_labels_on_image_array(
      image_np,
      output_dict['detection_boxes'],
      output_dict['detection_classes'],
      output_dict['detection_scores'],
      category_index,
      instance_masks=output_dict.get('detection_masks'),
      use_normalized_coordinates=True,
      line_thickness=8)
  cv2.imshow("result", image_np)

  output.write(image_np)

  if cv2.waitKey(1) & 0xFF == ord('q'):
    cap.release()
    output.release()
    cv2.destroyAllWindows()

    break

**Comment by smitshilu** [comment]
I made some changes to your file try it now and let me know if you encounter some errors. You were initializing session every time which takes most of the time. So you have to initialize session once and after that just use inference for each frame.

**Comment by Sharma96** [comment]
Can you please recommend if some changes can be done in this file as well?
https://gist.github.com/Sharma96/1c8ee4c09c8fc74b41f397ef4c8e7f2f

**Comment by smitshilu** [comment]
@Sharma96 it looks good in your case. Your problem is you are not using GPU that's why it is running slow. I would recommend to use GPU for faster and better performance.

**Comment by kangshintae** [comment]
@smitshilu Thank you. The source code you sent me was quicker than before. But there is still a problem. Running only uses a GPU at 6%.
====================================================================
+--------------------------------------------------------------------------------------------------------+ |
| NVIDIA-SMI 384.111                Driver Version: 384.111                                               |
|-------------------------------+----------------------+-------------------------------------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A       |   Volatile Uncorr. ECC          |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage    | GPU-Util  Compute M.     |
|===============================+===================================
|   0  GeForce GTX 1070    Off        |       00000000:09:00.0  On       |                  N/A    |
|  0%   40C    P2    37W / 200W      |       7880MiB /  8110MiB         |      6%      Default  |
+-------------------------------+----------------------+-------------------------------------------------+                         
+---------------------------------------------------------------------------------------------------------+
| Processes:                                                   GPU Memory                                           |
|  GPU       PID   Type   Process name                                             Usage                   |
|====================================================================
|    0      1238      G   /usr/lib/xorg/Xorg                           188MiB                                   |
|    0      2064      G   compiz                                        81MiB                                       |
|    0     14488      C   python3                                     7607MiB                                     |
+------------------------------------------------------------------------------------------------------------+

**Comment by saiteja040** [comment]
> I made some changes to your file try it now and let me know if you encounter some errors. You were initializing session every time which takes most of the time. So you have to initialize session once and after that just use inference for each frame.

can you please suggest me the changes to my file which is almost similar to @kangshintae .The only change is that i referenced to another model name which doesnot matter at all. Thank you

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
