### ISSUE TITLE
Error while training oxford pet data

### ISSUE THREAD

**Issue by ashley915** [tensorflow/models#3803]
Hi I'm having trouble training the oxford data. 
It states:
google.protobuf.text_format.ParseError: 1:1 : Message type "object_detection.protos.TrainEvalPipelineConfig" has no field named "syntax".

I'm attaching a screenshot of my error. I'm using Ubuntu 16.04.3, Python 3.5, Tensorflow_gpu-1.5, and I am running all this locally. Please help me out. 
Thank you!
![screenshot from 2018-03-29 17-16-11](https://user-images.githubusercontent.com/35290370/38083923-f67dd5ea-3385-11e8-85e0-18942927171d.png)

**Comment by derekjchow** [comment]
Could you share your config?

**Comment by ashley915** [comment]
It's just exactly as I've cloned it from git.

![screenshot from 2018-03-30 09-39-05](https://user-images.githubusercontent.com/35290370/38119639-43fae506-33fe-11e8-95f3-5080b3f38f28.png)

**Comment by derekjchow** [comment]
Ashley, you're using the config definition instead of a config.

Most of our valid training configs can be found in the [configs folder](https://github.com/tensorflow/models/tree/master/research/object_detection/samples/configs). In your case, you probably start with using [Faster RCNN101](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/faster_rcnn_resnet101_pets.config). Please be aware you will need to modify the PATH_TO_BE_CONFIGURED parts of this config to match your setup.

Happy training!

**Comment by ymodak** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
