### ISSUE TITLE
Only one way of shortcut in official resnet?

### ISSUE THREAD

**Issue by dzk9528** [tensorflow/models#3825]
When I read code in the official/resnet, when the dimensions increase, it seems like the short cut function only represents the second way in the paper, which introduces extra parameters unlike the first type of short cut in the paper. Does it means that the first way of short cut is not effective?

**Comment by karmel** [comment]
@robieta -- care to comment?

**Comment by robieta** [comment]
Hi. The code allows any projection function to be passed through, but we only do the convolution method. I haven't personally tested parameter free shortcuts, but the 2015  paper (Figure 3) suggests that there is a modest improvement using convolutions. 

I think the broader issue is that every degree of freedom we add increases complexity (instead of ResNet_50_v2 there is ResNet_50_v2_ProjectionModeA & ResNet_50_v2_ProjectionModeB & ResNet_50_v2_ProjectionModeC) and increases the learning curve. As a result we don't implement every permutation proposed between the two ResNet papers to keep the code approachable.

**Comment by dzk9528** [comment]
Thanks for the answer, you do make a point. 

Do you mind another question?
Although the resnet is official model, why there is only code for it to train the cifar-10 and imagenet. Can there be a code to tell you how to feed your own dataset? I believe since this is a official model, a high level tool, it should have such function. I recently write one modified version based on cifar10_main.py to feed my own dataset. Do you mind I add it or you will add one for the tf datasets with specific forms?

**Comment by robieta** [comment]
Sure. Eventually I would like to see a logical separation of datasets and layer definitions. As you say, imagenet and cifar10 aren't resnet concepts, they're just generic image datasets. Unfortunately I can't give you a timeline on when this will happen.

I'm going to close this issue as the original question has been addressed.

**Comment by dzk9528** [comment]
Then I am looking forward to seeing the future work, thanks for answering.
