### ISSUE TITLE
Motion Tracking and Detection

### ISSUE THREAD

**Issue by sakethramanujam** [tensorflow/models#3859]
How to track the motion of an object., ie., whether it is stationary/ moving ? Accompanied / unaccompanied by another class of objects?

**Comment by qlzh727** [comment]
Since this is a question about Tensorflow use case instead of bug reporting, please post this on stackoverflow with tag [tensorflow]. In that way, your question will be answered by Tensorflow team as well as community member.

You could also try the code example under tensorflow/model/research/object_detection to get more ideas.
