### ISSUE TITLE
NotFoundError: ; No such file or directory

### ISSUE THREAD

**Issue by Navdar** [tensorflow/models#3912]
Can’t train my own data set.
![fullsizeoutput_44e](https://user-images.githubusercontent.com/35260638/38472193-6f3510cc-3b7c-11e8-8327-e5f056b2d3e2.jpeg)

**Comment by asimshankar** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/models/issues/new). Please provide all the information it asks. Thank you.

In particular, more information about the full error seen would be helpful. Does adding a trailing `/` to the `--train_dir` flag help?

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
