### ISSUE TITLE
[deeplab] is there a bug in refine_by_decoder?

### ISSUE THREAD

**Issue by ruihou** [tensorflow/models#3920]
https://github.com/tensorflow/models/blob/aad56e4c428ce9ff5fbb1e9e1b0ef96f1e1fdfd2/research/deeplab/model.py#L560
Is this an indent error, or just on purpose. The second loop (line 560) should not be under the first one(L549)
The first loop (line 549) traverse all the branches in the feature_list.
And the second loop concatenates them together and do the decoder_conv0 and conv1

**Comment by robieta** [comment]
I believe you are correct. @aquariusjay could you take a look?

**Comment by aquariusjay** [comment]
It is not a bug.

The first loop traverses feature_list which contains all the low-level feature maps. It allows gradually up-sampling. In our use case, feature_list only contains the low-level feature maps that have output_stride = 4.

The second loop traverses decoder_feature_list to resize all the elements to have the same spatial dimension so that one could use tf.concat in the following convolution operations.

Note one could perform the decoder_conv0 and decoder_conv1 at each step in the gradually upsampling.

**Comment by ruihou** [comment]
Thanks for the clarification.

**Comment by robieta** [comment]
Thanks.
