### ISSUE TITLE
extract features of objects

### ISSUE THREAD

**Issue by Pyy666666** [tensorflow/models#3960]
Hello,I have been detected objects by Faster RCNN successfully,and now i want to extract features of objects which have been detected.
Thanks a lot in advance.

**Comment by asimshankar** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/models/issues/new). Thanks!

(When posting on StackOverflow you'd probably want to be more detailed in precisely what you're looking for)
