### ISSUE TITLE
Text file

### ISSUE THREAD

**Issue by nishajith** [tensorflow/models#3979]
It's not an issue..I wanted to save the name of the detected objects in a separate text file..How to do that??

**Comment by robieta** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
