### ISSUE TITLE
DELF: image pyramid in testing

### ISSUE THREAD

**Issue by rhina** [tensorflow/models#3981]
I'm trying to extract DELF using my implementation, but the number of features are different from official one.
Could you explain the details about an image pyramid in testing?

In official code, 5000-6000 features are extracted with the options 'max_features_num=100000, score_threshold=0.0'.
However, in my implementation, at most 1570 features were extracted from one image.
I first center-crop, resize (250x250), and crop the image (224x224) like the preprocessing in training  described in the paper, and then construct image pyramid using 7 scales (0.25, 0.3536, 0.5, 0.7071, 1.0, 1.4142, 2.0).
Is this correct?

Thanks

**Comment by rhina** [comment]
I have another question about detecting the location of descriptors.
I think that it can be computed by CalculateReceptiveBoxes and CalculateKeypointCenters in delf/extract_features.py

I have two concerns about this code.
1. stride=32.0 are used for both `resnet_v1_50/block3` and `resnet_v1_50/block4` (code below), but I think stride should be 16.0 for `resnet_v1_50/block3`. 

```
if layer_name == 'resnet_v1_50/block3':
    feature_depth = 1024
    rf, stride, padding = [291.0, 32.0, 145.0]
elif layer_name == 'resnet_v1_50/block4':
    feature_depth = 2048
    rf, stride, padding = [483.0, 32.0, 241.0]
else:
    raise ValueError('Unsupported layer_name.')
```

2. this function returns the location (0,0) for first feature at (0,0). but I think the center location of receptive field should be more than zero.

Could you answer my these concerns?

Thanks

**Comment by rhina** [comment]
cc @andrefaraujo 
I would be really appreciated if you could answer my questions.

**Comment by andrefaraujo** [comment]
Let me reply to your questions one by one.

1) Number of features.
The DELF model is fully convolutional, so it does not require resizing to a specific size when performing inference. The model we released will simply process the input image at whatever resolution you feed it, and produce a number of features which is proportional to the input resolution. We only resize to a specific size when doing training, for efficient batching. So, if you make sure the input image size is the same for both cases, that should produce the exact same number of features.

2) Stride.
This is because of the ResNet implementation we use. See the way we call the ResNet function:
https://github.com/tensorflow/models/blob/master/research/delf/delf/python/delf_v1.py#L220
In particular, note that `store_non_strided_activations` is set to False (default). This will give a stride of 32, not 16.

3) Feature location.
The Resnet model is aligned such that the first feature at the output feature map is centered at the first pixel. That is why the location is (0,0).
For more information on how the receptive field information is computed, and how to map features to pixel locations, see the TF module [tf.contrib.receptive_field](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/receptive_field)

**Comment by rhina** [comment]
Thank you so much for your detailed response!

1.
I get high performance by not resizing images in testing. Thanks!

2.
I think that your used ResNet50 is the same as the one in the official paper: http://openaccess.thecvf.com/content_cvpr_2016/papers/He_Deep_Residual_Learning_CVPR_2016_paper.pdf (Table1, 50-layer).
The shape of conv4_x feature (corresponding to block3) is (14x14), so I think stride is 224/14=16.0.
I can understand that a stride of conv5_x (corresponding to block4) is 32,0, but I think a stride of conv4_x is 16.
Is it correct?

3.
I see. maybe I was wrong.
I will take a look at your introduced page and learn how to compute receptive field.

**Comment by andrefaraujo** [comment]
Regarding the stride, your observation based on the paper is correct. However, the ResNet implementation we use does an additional striding at conv4_x. So, we use conv4_x with an additional subsampling of 2, which is the default configuration for the tensorflow ResNet implementation we use. That's what I was trying to explain in my previous post :)

**Comment by rhina** [comment]
I understand. I didn't know that tensorflow default implementation is like that.
Thank you so much for answering my questions many times ^^

**Comment by VPRzhou** [comment]
Hi,there is a question I want to ask you.How to calculate the size of a image in testing?For example,input resolution is 1024X1024，output? @rhina
