### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1001] rhs shape= [1000]

### ISSUE THREAD

**Issue by rohith14** [tensorflow/models#4001]
##Code

$ python export_inference_graph.py --alsologtostderr --model_name=resnet_v1_50 --output_file=/local/del/ResNet50_v1_inf_graph.pb

$python freeze_graph.py --input_graph /local/del/ResNet50_v1_inf_graph.pb --input_checkpoint=/local/del/resnet_v1_50.ckpt --input_binary=true --output_graph=/local/del/frozen_resnet_v1_50.pb --output_node_names=ResNetV150/Predictions/Reshape_1

## Error
Traceback (most recent call last):
  File "/local/Anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/local/Anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/local/Anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1001] rhs shape= [1000]

**Comment by rohith14** [comment]
Got this working by setting --labels_offset=1

**Comment by mikechen66** [comment]
> Got this working by setting --labels_offset=1

Hi rohith14: 

I meet an error while dealing with Google Inception v4 by running $ inceptiion_v4.py in Anaconda Environment. I have already know that I need to set "labels_offset=1". But I have not know where "labels_offset=1" shall be inserted. Please see the error details as follows.

0. My Weights

inception-v4_weights_tf_dim_ordering_tf_kernels.h5
inception-v4_weights_tf_dim_ordering_tf_kernels_notop.h5

1. if set num_classes=1001, I can get the correct model structure with model.summary()

model = inception_v4(num_classes=1001, dropout_prob=0.2, weights='imagenet', include_top=True)
model.summary()
2. If set num_classes=1001, I get the error while getting prediction

 model = inception_v4(num_classes=1001, dropout_prob=0.2, weights='imagenet', include_top=True)
 preds = model.predict(x)
 print('Predicted:', decode_predictions(preds))
raise ValueError('If using `weights` as imagenet with `include_top`' ValueError: If using `weights` as imagenet with `include_top` as true, `classes` should be 1000
3. If set num_classes=1000, I get the error while getting prediction

 model = inception_v4(num_classes=1000, dropout_prob=0.2, weights='imagenet', include_top=True)
 preds = model.predict(x)
 print('Predicted:', decode_predictions(preds))
_raise ValueError("Shapes %s and %s are incompatible" % (self, other)) ValueError: Shapes (1536, 1000) and (1536, 1001) are incompatible
How can I do correctly with both model.summary() and model.predict(x)? Please help me out of the error.


**Notes:**

_1. Adding --labels_offset=1 can not solve the issue._ 

`$ python inception_v4.py --labels_offset=1`

_2. I cannot use the following method to deal with the error because I do not use the bazel environment._

```
./bazel-bin/slim/train
--train_dir=${TRAIN_DIR}
--dataset_dir=${DATASET_DIR}
--dataset_name=imagenet
--dataset_split_name=train
--model_name=resnet_v1_50
--checkpoint_path=${CHECKPOINT_PATH}
--labels_offset=1
```

https://github.com/jonsafari/tensorflow-models/blob/master/slim/README.md
