### ISSUE TITLE
How to solove in TensorFlow Object Detection API

### ISSUE THREAD

**Issue by darkies4ever** [tensorflow/models#4024]
### Describe the problem
I have a question while using the Tensorflow Object Detection API.
While using this API, I do not want to detection person recognition.
For example, if you have person and scissors, I want to detection only scissors, except person.
We Would like to exclude Person detection
I need a solution.
How do you solve it?
Please help me...

**Comment by robieta** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
