### ISSUE TITLE
Question about TensorRT benchmark 

### ISSUE THREAD

**Issue by luotao1** [tensorflow/models#4028]
In https://github.com/tensorflow/models/tree/master/research/tensorrt, there are benchmarks on TensorFlow graph using TensorRT. 

While https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/topics/topics/workflows/tf_to_tensorrt.html tells another method, i.e, import a TensorFlow model into TensorRT and create a TensorRT engine directly.

May I know the elapsed time difference between these two methods? Does "TensorFlow graph using TensorRT" will be slower than "import a TensorFlow model into TensorRT"?

Thanks very much!

**Comment by robieta** [comment]
@karmel Can you comment?

**Comment by karmel** [comment]
CC @aaroey @samikami for more details on TRT performance.

**Comment by aaroey** [comment]
@samikama

**Comment by aaroey** [comment]
Generally speaking, for a TF model whose ops are all supported by TensorRT, importing it into TensorRT and running TensorRT directly should be more efficient than running it through TF-TensorRT integration. The trade-off is then between the ease of use and the performance gain (which may be negligible, depending on the model and the way you run it). We don't have numbers on the performance difference yet, as for common models it's hard to write native TensorRT implementations, and usually TensorRT doesn't support all the ops. So I think contributions are welcome here.

**Comment by samikama** [comment]
The main difference is uff path requires all model to be supported by TensorRT. Even though TensorRT supports large fraction of ops encountered in the models it doesn't support everything. TF-TRT approach enables you to get supported parts of the networks run in TensorRT and unsupported part to run in TensorFlow, so that you can get partial speedup that wouldn't be possible. In the future we will add plugin support so a larger fraction of the networks could be transformed to TensorRT engine. Our tests indicate that, for the converted segments, TFTRT performance is pretty close to TensorRT performance.

**Comment by karmel** [comment]
Thanks, @aaroey and @samikama ; closing this issue as resolved, but, @luotao1 , if you have specific issues with the implementation, please open a new issue.

**Comment by luotao1** [comment]
Thanks to all of you very much!
