### ISSUE TITLE
TypeError: `pred` must be a Tensor, or a Python bool, or 1 or 0. Found instead: None

### ISSUE THREAD

**Issue by dtuyenle** [tensorflow/models#4043]
Keep having below issue when run object_detection/train.py
TypeError: `pred` must be a Tensor, or a Python bool, or 1 or 0. Found instead: None

**Comment by nickyua** [comment]
change 109 line in   ssd_mobilenet_v1_feature_extractor.py:
from 
``` 
              is_training=None, regularize_depthwise=True)):```
to 
```
              is_training=True, regularize_depthwise=True)):
```

**Comment by dtuyenle** [comment]
that works. thanks

**Comment by hakillha** [comment]
@nickyua I think this can potentially cause serious problems since the export_inference_graph.py script runs this module to build the models as well.
I found this problem since I somehow got to export the frozen graphs with the older and the newer version of the API and the graphs differed in performance dramatically. So I changed that line to is_training=False when I was exporting the graph which fixed the problem.

**Comment by pkulzc** [comment]
This problem exists for a certain period of time when slim dir is outdated. Syncing to latest and this should be gone.

**Comment by leccyril** [comment]
where is  ssd_mobilenet_v1_feature_extractor.py ?

**Comment by tesfagabir** [comment]
@pkulzc I still have the same problem even if I update the tensorflow/models to its latest version. I have a version which was updated on July 17. But still getting the problem. I also changed from `training=None` to `training=True` on `ssd_mobilenet_v2_feature_extractor.py` module. Could you please help me on that?

**Comment by pkulzc** [comment]
Are you still setting training=True? You should never hardcode training because it may keep updating batch norm when running eval.

**Comment by tesfagabir** [comment]
Yes I did. So should I bring it back to training=None?

**Comment by florinmatei** [comment]
> where is ssd_mobilenet_v1_feature_extractor.py ?

I can't find this file either. Were you able to find it?
