### ISSUE TITLE
adversarial_text loss is negative values

### ISSUE THREAD

**Issue by janguck** [tensorflow/models#4312]
If you run trainclassifier.py in your adversarial_text , is loss normal to negative values?

**Comment by kmeng01** [comment]
I had this issue when I ran `train_classifier.py` with 3 classes, instead of the default 2; the loss values reached -15000 at one point. 

However, I soon realized that I forgot to specify in the args that `--num_classes=3`. After changing this, the script worked correctly, and loss was back to being >0. Try and see if that works.

**Comment by wt-huang** [comment]
Closing this as it is resolved, feel free to reopen if problem persists.
