### ISSUE TITLE
object_detection: Windows installation instructions?

### ISSUE THREAD

**Issue by anchpop** [tensorflow/models#4317]
The [installation instructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) for the object detection api seem to be for MacOS or Linux, is Windows supported? If so, if someone can help me set it up on Windows I'd be happy to submit a PR with some Windows installation instructions. If not, that information should probably be added to the readme or installation.md.

Thanks

**Comment by giorigor** [comment]
Installation on Windows is pretty similar to their Unix counterpart, though you need to use `\` instead of `/` for directories, and you need to compile the protobufs individually. [Here's a great guide for Windows 10 users](https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10).

**Comment by anchpop** [comment]
Thanks. I got it working but there were some other gotchas. I had to use a
different repository for cocoapi (a fork with windows support), cygwin to
use make, etc.

**Comment by wt-huang** [comment]
Closing as this is resolved

**Comment by Walid-Ahmed** [comment]
On windows 10, I am getting the following error when I try to execute train.py from the legacy folder  
python train.py --logtostderr --train_dir=train
I am getting the following exception:-
 c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open:  : The system cannot find the path specified.
