### ISSUE TITLE
[deeplab v3+]How to change the input size 

### ISSUE THREAD

**Issue by fuchao01** [tensorflow/models#4369]
I trained ade20K data, but when using inputsize=513, I want to change the input size. How do I do it?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by robieta** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by beerensahu** [comment]
@fuchao01 even I am looking for the same. Did you find the answer? If yes, please share here. Meanwhile, if I could find something I will share here too.

**Comment by chichilicious** [comment]
Did any of you find a solution? I tried for 257 and 321, it works. I want a larger size.

**Comment by chichilicious** [comment]
check [FAQ](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/faq.md ), 8th question.
