### ISSUE TITLE
How to do Batch Inference SSD MobileNet C++

### ISSUE THREAD

**Issue by SANTHAKUMAR91** [tensorflow/models#4420]
Tensorflow C++ Implementation for SSD Mobilenet in Visual Studio 2015,

### System information
- I have used Tensorflow example API.
- OS Platform and Distribution (Windows 10)
- TensorFlow installed from (source).
- TensorFlow version (v1.5)*
- Windows build using Visual Studio 2015 update3.
- CUDA/cuDNN version 9.1
- GPU model and memory GTX1070

I have successfully compiled tensorflow in windows to use with c++, The current code does inference for one image, I want to optimize for batch inference. 

Below is my implementation.  
 **For Single Image:-**
```
tensorflow::Tensor imgTensorWithSharedData(tensorflow::DT_UINT8, { 1, inputHeight, inputWidth, cvImg->channels() });
	uint8_t *p = imgTensorWithSharedData.flat<uint8_t>().data();
	cv::Mat outputImg(inputHeight, inputWidth, CV_8UC3, p);
	cvImg->convertTo(outputImg, CV_8UC3);

std::vector<tensorflow::Tensor> outputs;
	tensorflow::Status run_status = (*tf_session)->Run({ { "image_tensor:0", imgTensorWithSharedData } },
	{ "detection_boxes:0", "detection_scores:0", "detection_classes:0", "num_detections:0" },
	{},
		&outputs);
// Read Prediction
tensorflow::TTypes<float>::Flat scores = outputs[1].flat<float>();
	tensorflow::TTypes<float>::Flat classes = outputs[2].flat<float>();
	tensorflow::TTypes<float>::Flat num_detections = outputs[3].flat<float>();
	auto boxes = outputs[0].flat_outer_dims<float, 3>();

	int detectionsCount = (int)(num_detections(0));


```
**for Batch Image:-**
```
tensorflow::Tensor imgTensorWithSharedData(tensorflow::DT_UINT8, { (batchSize, inputHeight, inputWidth, cvImg[0]->channels() });
	uint8_t *p = imgTensorWithSharedData.flat<uint8_t>().data();
	for (int i = 0; i < batchSize; i++) {
		p += i * inputHeight * inputWidth * inputDepth;
		cv::Mat outputImg(inputHeight, inputWidth, CV_8UC3, p);
		cvImg[i]->convertTo(outputImg, CV_8UC3);
	}

//Inference:-
std::vector<tensorflow::Tensor> outputs;
	
	tensorflow::Status run_status = (*tf_session)->Run({ { "image_tensor:0", imgTensorWithSharedData,  } },
	{ "detection_boxes:0", "detection_scores:0", "detection_classes:0", "num_detections:0" },
	{},
		&outputs);

```

I am not able to get batch output, it always gives me one image inference.
How to get results for batch image?.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
Bazel version
Exact command to reproduce

**Comment by SANTHAKUMAR91** [comment]
Hi, this is the model which iam using.
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz

Bazel version - NA (using CMake & Visual Studio) 

Using TF Label image c++ as reference code

**Comment by k-w-w** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by SANTHAKUMAR91** [comment]
Thanks

**Comment by spivakoa** [comment]
Hi @SANTHAKUMAR91. I'm dealing exactly with the same issue  when running a batch instead of a single image through the SSD based on Mobilenet. It looks like something is working though, as runtime becomes larger when running a batch, but same as you, I can't get the outputs.
I asked a question on Tensorflow GitHub and after being forwarded to few different persons, got an answer that batch inference isn't implemented on C++ API, comparing to a Python one. It seems very strange to me, if you had this issue resolved somehow, I would like to hear how.

Thank you,
Alex.

**Comment by ilidar** [comment]
@spivakoa Check it out, maybe it will help https://github.com/tensorflow/tensorflow/issues/19909#issuecomment-405241355
