### ISSUE TITLE
How to do data argumentation and multi-scale test by Object Detection API?

### ISSUE THREAD

**Issue by songzenghui** [tensorflow/models#4665]
Do i need to modify the `config` file? e.g.  `faster_rcnn_resnet101_voc07.config`?  There is a line in this file:
 `data_augmentation_options {
random_horizontal_flip {
}
}`
Does this line of code mean that it has done data argumentation?
And How to do multi-scale ?

**Comment by FreedoomFighter** [comment]
If you use 'ssd_mobilenet_v1_coco_2017_11_17' then you need make little changes (I have not tried, it's assumption):
1. Change generate_tfrecord (just add other options)
Example:
# TO-DO replace this with label map
def class_text_to_int(row_label):
    if row_label == 'fox':
        return 1
    elif row_label =='wolf':
        return 2
    else:
        return None

2. Change label.pbtxt:
item {
  id: 1
  name: 'fox'
}
item {
  id: 2
  name: 'wolf'
}

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by k-w-w** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
