### ISSUE TITLE
A problem happened when I run models/research/slim/eval_image_classifier.py

### ISSUE THREAD

**Issue by Iorest** [tensorflow/models#4722]
I am running this program in tensorflow 1.8. Then the power supply to the GPU is stopped, which causes the GPU to not work，unless restart the computer.
However,this problem does not appear when running other programs.

## System information
GPU model and memory:Titan X, 12G(ubuntu18.04); 
Tensorflow version: 1.8.0(GPU)(install from anaconda)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
Exact command to reproduce

**Comment by LeaForest** [comment]
I am sorry,these are information in detail.

## What is the top-level directory of the model you are using
I clone this repository，and build the environment follow the tutorial。I run the inception_v3 model on the "flowers" dataset .The top-level directory is models/research/slim/
## Have I written custom code
I do not change any code.
## OS Platform and Distribution
ubuntu 18.04
## TensorFlow installed from
anaconda 5.2.0
## CUDA/cuDNN version
7.1
## Exact command to reproduce
python eval_image_classifier.py     --alsologtostderr     --checkpoint_path=tmp/train_logs/flowers_inception_v3/     --dataset_dir=tmp/data/flowers     --dataset_name=flowers     --dataset_split_name=validation     --model_name=inception_v3

This problem happens when I run the eval_image_classifier.py .however,when I run the train_image_classfier.py,everything is OK.

**Comment by mmanoharahere** [comment]
Hi @Iorest , I am facing a similar issue. Could you find any solution to this?
Thank you!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
