### ISSUE TITLE
Concern on linking to database

### ISSUE THREAD

**Issue by niranjan8129** [tensorflow/models#4828]
I like very much of your model but Just have a concerns . how to set up database based tokenized field

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by niranjan8129** [comment]
I want to deploy at my facebook account through Djano server . if i give any request to bot,  I would expect to get reply through bot from datababe(lilke MYSQL). If bot does not have answers or do not have answers at database table , it will ask to user  sorry ,bot  don't have answers and  train me . if use say/write SKIP/NO , then it will ask to user proceed to the next question .  If I say  YES ,write some thing and it will store in tot he  database . next time if I will ask to bot same question , bot will give reply to user based user feeding data previously  .

Have I written custom code
OS Platform and Distribution -- Windows/mac
TensorFlow installed from -  Windows/mac
TensorFlow version    - 1.8
Bazel version N/A
CUDA/cuDNN version -1.9
GPU model and memory -1.8
Exact command to reproduce- N/A

**Comment by k-w-w** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
