### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection'

### ISSUE THREAD

**Issue by Mayurji** [tensorflow/models#4908]
### With recent update in Tensorflow/Models/research/object_detection, there exists a conflict between path i.e the file train.py in "/object_detection/legacy" folder has dependency on a file stored in "/object_detection/builders".

<img width="960" alt="object_detection_error" src="https://user-images.githubusercontent.com/10477789/43262075-800936a0-90fc-11e8-951b-0e0ccad02b46.PNG">

how do i execute train.py if it has dependency on subfolders.

**Comment by manu1a** [comment]
You are trying to execute the script from 'legacy' directory and it cannot find object_detection inside the directory 'legacy'. You should configure the $PYTHONPATH and then try to run the script. I am not a windows user, but this is the problem i faced on linux, which i could rectify by configuring $PYTHONPATH correctly.

**Comment by Mayurji** [comment]
I understood what you're trying to say, previously legacy folder was not
present in research folder and I think it has been recently updated in
tensorflow.

I will try to resolve the issue as suggested.

Thank you

**Comment by Mayurji** [comment]
Can you be more specific regarding the pythonpath or point me to a link where I can find the exact solution.

**Comment by manu1a** [comment]
Follow the below link for some tips on windows. I haven't used it. But i hope it helps. 
https://www.youtube.com/watch?v=rWFg6R5ccOc
Please be sure if the problem is an issue when you post here. This post looks like a stack overflow question more than an issue, and you have not filled the standard issue template. Its not a crime, but it is just my suggestion to be sure to post some problem as an issue in this forum.

**Comment by Mayurji** [comment]
Thanks @manu1a I was able to follow up with the video.

**Comment by Samll-Kosmos** [comment]
I don't know what is shown in the video but I resolved the problem simply by:
import sys
sys.path.path(path/to/research/folder)
