### ISSUE TITLE
Transfer Learning On The Pre-trained Model And Add Layers But Get Error.

### ISSUE THREAD

**Issue by chawdoe2** [tensorflow/models#5006]
### System information
- **What is the top-level directory of the model you are using**:master/research/object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Win10
- **TensorFlow installed from (source or binary)**:binary
- **TensorFlow version (use command below)**:1.8.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:did not install cuda/cudnn
- **GPU model and memory**:did not use gpu to run the program
- **Exact command to reproduce**:python train.py( I have modified the train.py.)

### Describe the problem
I want to add some layers to the faster rcnn arch.
I modify the box_predictor.py
![add_layers](https://user-images.githubusercontent.com/34465151/43688331-36ac6408-9919-11e8-82fa-eb13499ce80b.png)
So I add a full-connect layer before we output the final result.
And then I want to retrain the pre-trained model which is built in the old arch.
But I get error as follows.

NotFoundError：Key SencondStageBoxPredictor/NewLayer/biases not found in the checkpoint

I know it would not be found.
But I just want to load the weights and biases which can be found And init the new parameters
and then train them anyway.

**Comment by karmel** [comment]
A checkpoint typically has to match the graph exactly. There are ways to load particular variables in a checkpoint to reuse those, but it would take changing more than one line. See [this StackOverflow question](https://stackoverflow.com/questions/41621071/restore-subset-of-variables-in-tensorflow) and the [docs for Saver](https://www.tensorflow.org/api_docs/python/tf/train/Saver) mentioned there for more.

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by kjmiller013** [comment]
I have a follow-up question to this.

It looks like the solutions in the StackOverflow post rely on passing certain arguments to the Saver, but I'm having trouble finding where the Saver is called in the object detection API.  As far as I know, it happens somewhere in tf.estimator.train_and_evaluate when it's called from research/object_detection/model_main.py at line 97.

Is there a way to get the Saver to only load certain variables, without having to modify Tensorflow library functions such as tf.estimator.train_and_evaluate?  Thanks!
