### ISSUE TITLE
The eval miou is so bad!

### ISSUE THREAD

**Issue by gshdong** [tensorflow/models#5142]
I use single GTX1080TI GPU. The eval result miou is so bad, about  19% on cityscapes dataset. Who can help me?
The train script is:
```
python train.py \
  --logtostderr \
  --train_split="train" \
  --model_variant="mobilenet_v2" \
  --output_stride=16 \
  --train_crop_size=769 \
  --train_crop_size=769 \
  --train_batch_size=10 \
  --training_number_of_steps=60000 \
  --fine_tune_batch_norm=False \
  --dataset="cityscapes" \
  --tf_initial_checkpoint="datasets/cityscapes/init_models/deeplabv3_mnv2_cityscapes_train/model.ckpt.index" \
  --train_logdir="datasets/cityscapes/exp/train_on_train_set/train" \
  --dataset_dir="datasets/cityscapes/tfrecord"
```
The eval script is:
```
python eval.py \
  --logtostderr \
  --eval_split="val" \
  --model_variant="mobilenet_v2" \
  --eval_crop_size=1025 \
  --eval_crop_size=2049 \
  --dataset="cityscapes" \
  --checkpoint_dir="datasets/cityscapes/exp/train_on_train_set/train" \
  --eval_logdir="datasets/cityscapes/exp/train_on_train_set/eval" \
  --dataset_dir="datasets/cityscapes/tfrecord" \
  --max_number_of_evaluations=1
```

**Comment by cjr0106** [comment]
hi  when i run the eval.py 
meet the problem:
NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from
the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key lr not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64, DT_FLOAT],
_device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
could you give me advice?
