### ISSUE TITLE
Image compression time delay

### ISSUE THREAD

**Issue by EhsanVahab** [tensorflow/models#5174]
I've used image compression model to compress and store my images. the result is fantastic when I use iteration 15 but it takes a long time.
my OS specification is :
Windows 10 x64 , 16GB RAM , CPU Corei7 -6700HQ 2.6 GHz
I've seen when I use iteration 15 all the iteration results are performed and stored in results array.
In order to reduce time delay, I wanted to know is it possible to perform only iteration 15, without others [0,1,2...14]?
Or is there any way to reduce time delay and the output.npz file size?

**Comment by EhsanVahab** [comment]
Thanks for your response and sorry for my mistake to incomplete the form. 
The top level directory is [here](https://github.com/tensorflow/models/tree/master/research/compression) 
Is:  windows 10  x64
Tensorflow installed from:  pip install ten airflow
Tensorflow version: 1.10.1
Basel version:  N/A
Cute: N/A
GPU:  N/A

**Comment by nmjohn** [comment]
Hello Ehsan,

Because this model is recurrent, both in the encoder and the decoder, by definition if you want the output at 15, we must run the previous steps as well. Additionally the model creates a progressive code, so the results at 15 is a concatenation of [0-15].

As far as file size goes, each step in the sequence targets 1/8th of a bit per pixel. So if you're wanting a smaller file size, you'll be running an iteration < 15.

I hope this makes the model more clear,

-- Nick

**Comment by ymodak** [comment]
Is this still an issue?

**Comment by EhsanVahab** [comment]
> 
> 
> Did you get a chance to try nmhohn's suggestion?. Is this still an issue for you?

Dear ymodak,
My question was asked by nmhohn.
please close the topic.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
