### ISSUE TITLE
Deeplab V3+ error： convert my own datasets from jpg and png to tfrecord.

### ISSUE THREAD

**Issue by SdustZhangzhen** [tensorflow/models#5195]
**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **What is the top-level directory of the model you are using:~/models/research/deeplab
- **OS Platform and Distribution : Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below):1.6.0
- **CUDA/cuDNN version: CUDA 9.0, cuDNN 7.0
- **GPU model and memory: GeForce GTX 1080, 8G
- **Exact command to reproduce**:

When I convert my own datasets from jpg and png to tfrecord, using the command as follow:

python build_voc2012_data.py  --image_folder="/home/zhang/Deeplab/models/research/deeplab/datasets/pascal_voc_seg/VOCdevkit/VOC2012/JPEGImages"   --semantic_segmentation_folder="/home/zhang/Deeplab/models/research/deeplab/datasets/pascal_voc_seg/VOCdevkit/VOC2012/SegmentationClass"   --list_folder="/home/zhang/Deeplab/models/research/deeplab/datasets/pascal_voc_seg/VOCdevkit/VOC2012/ImageSets/Segmentation"   --image_format="jpg"   --output_dir="/home/zhang/Deeplab/models/research/deeplab/datasets/pascal_voc_seg/tfrecord"

But Error as fllow:

>> Converting image 666/2662 shard 0
>> Converting image 1332/2662 shard 1
>> Converting image 1998/2662 shard 2
>> Converting image 2662/2662 shard 3Traceback (most recent call last):
  File "build_voc2012_data.py", line 141, in <module>
    tf.app.run()
  File "/home/zhang/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "build_voc2012_data.py", line 137, in main
    _convert_dataset(dataset_split)
  File "build_voc2012_data.py", line 116, in _convert_dataset
    image_data = tf.gfile.FastGFile(image_filename, 'rb').read()
  File "/home/zhang/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/zhang/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/zhang/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/zhang/Deeplab/models/research/deeplab/datasets/pascal_voc_seg/VOCdevkit/VOC2012/JPEGImages/.jpg; No such file or directory

In the last error cue is "No such file or directory", but all my files and directory are set as require.
where is wrong? Thanks.

**Comment by sumsuddin** [comment]
Can you check the text files in "/home/zhang/Deeplab/models/research/deeplab/datasets/pascal_voc_seg/VOCdevkit/VOC2012/ImageSets/Segmentation". There should be three text files all containing image file names

Looks like the image filenames are not right.

**Comment by SdustZhangzhen** [comment]
I found the reason for the error. In the folder of the training list, the file ended up with a blank line and the blank line needed to be deleted.

**Comment by minyil** [comment]
@SdustZhangzhen , how do you create your own dataset? I want to add one new class to pascal VOC dataset, but I don't know how to label the new segmentation image. Is there any tool or information to create the custom dataset? 
Thanks.

**Comment by sumsuddin** [comment]
@SdustZhangzhen ,

> The users could modify the provided dataset/build_{cityscapes,voc2012}_data.py and dataset/segmentation_dataset.py to build their own dataset

More [here](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/faq.md).

**Comment by minyil** [comment]
@SdustZhangzhen Sorry, my description is not clear. My question is how to create the segmentation images for training? Is any tool to create the segmentation .png file?
Thanks for your comment.

**Comment by SdustZhangzhen** [comment]
@minyil  In my opinion, there are three ways to create the segmentation .png file. First one, owing to the label has specific value of RGB. For example, the  value of road is R 255 G 255 B 255, and the label of road is 1, so you can write a program to make the R 255 G 255 B 255 into the label of 1. Second, you can use ' Decision tree classification' to make the label. I use this method by the software of ENVI that is specially designed for image processing. Third, someone use photoshop to make the label.

**Comment by sumsuddin** [comment]
Sorry, my bad. Have a look at [this tool](https://github.com/Labelbox/Labelbox). @minyil

**Comment by jillelajitta** [comment]
Hi,
Sorry for hijacking this thread.
I'm getting following warnings when I'm trying to retrain my model, I am using SSD+GoogleNet. Please someone help me.

Thanks.

WARNING:tensorflow:Ignoring ground truth with image id 2132974076 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 2132974076 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 483474429 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 483474429 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1042541771 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1042541771 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 374107777 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 374107777 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 851704672 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 851704672 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1267094741 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1267094741 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 674017641 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 674017641 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 2011324514 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 2011324514 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 655823972 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 655823972 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 1069886348 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 1069886348 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 432647899 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 432647899 since it was previously added
WARNING:tensorflow:Ignoring ground truth with image id 192947873 since it was previously added
WARNING:tensorflow:Ignoring detection with image id 192947873 since it was previously added

**Comment by NiallDelany** [comment]
I'm having a similar problem trying to convert a custom dataset to tfrecord for DeepLab v3+, following this tutorial. My directory setup is as follows:

+ datasets
  + custom_dataset
    + VOCdevkit
      + VOC2012
        + JPEGImages
        + SegmentationClassRaw
        + ImageSets
           +Segmentation
    + tfrecord
I also have downloaded the Pascal VOC dataset and the two directory structures are now identical. When I run the build_voc2012_data.py script on the PascalVOC dataset as follows:

#from models/research/deeplab/dataset/pascal_voc_seg

python build_voc2012_data.py \
--image_folder="./VOCdevkit/VOC2012/JPEGImages" \
--semantic_segmentation_folder="./VOCdevkit/VOC2012/SegmentationClassRaw" \
--list_folder="./VOCdevkit/VOC2012/ImageSets/Segmentation" \
--image_format="jpg" \
--output_dir="./tfrecord"
...everything works fine, the dataset gets converted to tfrecord files with a progress bar displayed. However when I run the same script from my custom dataset directory, the following error occurs:

>> Converting image 1/164 shard 0Traceback (most recent call last):
  File "build_voc2012_data.py", line 146, in <module>
    tf.compat.v1.app.run()
  File "/home/delanyn/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/delanyn/.local/lib/python2.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/delanyn/.local/lib/python2.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "build_voc2012_data.py", line 142, in main
    _convert_dataset(dataset_split)
  File "build_voc2012_data.py", line 121, in _convert_dataset
    image_data = tf.io.gfile.GFile(image_filename, 'rb').read()
  File "/home/delanyn/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/home/delanyn/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
.jpg; No such file or directoryors_impl.NotFoundError: ./VOCdevkit/VOC2012/JPEGImages/2020_0

What could I be missing here? My images are JPEG with the same dimensions as the Pascal VOC images. The segmentation masks have the same colormap as well, and I use remove colormap script on them in advance.
