### ISSUE TITLE
textsum: data.py thread error

### ISSUE THREAD

**Issue by InTheCloudDan** [tensorflow/models#522]
## Please let us know which model this issue is about (specify the top-level directory)
textsum

I am receiving a thread error on 16 threads as soon as I run:
```
# Run the training.
bazel-bin/textsum/seq2seq_attention \
  --mode=train \
  --article_key=article \
  --abstract_key=abstract \
  --data_path=data/training-* \
  --vocab_path=data/vocab \
  --log_root=textsum/log_root \
  --train_dir=textsum/log_root/train
```

stdout starts showing:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/summing/textsum/batch_reader.py", line 135, in _FillInputQueue
    (article, abstract) = input_gen.next()
  File "/opt/summing/textsum/batch_reader.py", line 244, in _TextGenerator
    e = example_gen.next()
  File "/opt/summing/textsum/data.py", line 102, in ExampleGen
    example_str = struct.unpack('%ds' % str_len, reader.read(str_len))[0]
MemoryError
```

All the way to Exception in thread Thread-16:

I'm running a 4GB VPS on Debian 8, I've tried the bazel build with:
```
bazel build -c opt --config=cuda textsum/...
```

And then did a clean and tried it with:

```
bazel build -c opt --spawn_strategy=standalone --local_resources=2000,1,1.0 textsum/...
```

They are both throwing the exact same error

**Comment by xtr33me** [comment]
@InTheCloudDan What version of TF/CUDA/CUDNN are you using? What is the GPU hardware you are running against on the VPS?  I assume your 4GB is VRAM? 

What dataset are you using? Your own generated one or the toy dataset?  Have you tried stepping into the code to see what is happening as data.py?  

What I'm currently leaning towards is that if this is against your own dataset, you may need to break your training data down to smaller sizes.  This is of course a complete theory, as I don't really know much yet about your env, but when I first started playing with this I put all my articles in one file and all my vocab in one file. The vocab so far has not been an issue, but the articles were. I was training this on my laptops 980M so the resources weren't as abundant as some of these other rigs you see on here. 

Hopefully if you provide a bit more detail, someone might have a little bit of a better idea as to what may be the source.  If you are doing this against your own data, have you tried with the toy dataset yet?  It might be good to see if you have the issue with it as well.

**Comment by InTheCloudDan** [comment]
@xtr33me Thanks, I think I need to spend more time getting a handle on tensorflow overall before tackling this specifically. The VPS doesn't have any cuda support so dropped that out. Tried the same thing on a ubuntu laptop with 8GB of ram and it ran overnight pegging a core almost continuously and maxing ram while spewing out the errors so must be something I'm doing.

Just so I can get a grasp of if, for the toy data is it just copying the data/data and renaming it training-0?

**Comment by xtr33me** [comment]
@InTheCloudDan The first thing I will state, is this will be a much more enjoyable experience for you if you can get a hold of a GPU :)  That said, on my MBP I couldnt use the GPU because it only had a Gig of VRAM so I too had to use the cpu at first. But if you can get your hands on a GPU, it is sooo much quicker.  You can also look at using a g2.2xlarge AWS instance ....jsut something to keep in mind.  I am actually currently looking at the Google cloud which looks awesome, but I still need to get my ehad wrapped around setting everything up so it can consume it. 

That said, as for the toy data, it is definitely the best way to start and play textsum. The data is clean and that is one big headache you dont have to deal with right now. Then once you get more familiar, then the fun comes to try and procure your own data.  I'm still trying to figure out how so many people have access to the $6k Gigaword dataset. Perhaps they have fat wallets :p  

By simply doing what you stated and renaming data to training-0 or just redirecting the path passed to the data file under textsum.  That is your choice.  One important thing though is the vocab file will not work for you.  If you scroll to the bottom you will find the reference to a vocab file I generated that you will want to use instead. However, using the toy dataset provided and that vocab file and I think you will be quite surprised by the results.

Hope this helps!  Good luck and have fun!

https://github.com/tensorflow/models/issues/417

**Comment by jart** [comment]
Thanks for helping out with support @xtr33me. I'm not sure if this is a bug or if it's just that the VPS has so little RAM. We would probably want profiling reports and other details to decide if it's worth us going in and trying to optimize something. If you have other questions in the future, the [Stack Overflow](http://stackoverflow.com/questions/tagged/tensorflow) community provides good support.

**Comment by ENate** [comment]
Hi All,
I have the same problem on trying to run the toy dataset on both python3.6 and python2.7! Any solutions to this problems? Thanking!
