### ISSUE TITLE
Anybody knows how could we got mAP by using own dataset?

### ISSUE THREAD

**Issue by dongsheng20170812** [tensorflow/models#5292]
I tried to train myself dataset, and get the correct model. Also, I want to evaluate the performance of the model by calculate mAP, however, I don't get any idea. Is there anybody knows how could do this?

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
