### ISSUE TITLE
How to save one-hot encoded lables in deeplab v3+?

### ISSUE THREAD

**Issue by asgsaeid** [tensorflow/models#5510]
### System information
- **What is the top-level directory of the model you are using**: deeplab
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: u 16.04
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**: 1.9
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: titanX
- **Exact command to reproduce**:

### Describe the problem

I need the one-hot encoded labels for each image in train and Val sets. I found the labels are converted to one-hot before computing loss, but how to save one-hot encoded labels for all the images in the same order that deeplab uses; so each image should have a one-hot encoded matrix of hxwx19

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
