### ISSUE TITLE
deeplab: might you release the PASCAL and PASCAL Person Part trained DPC models?

### ISSUE THREAD

**Issue by tqfjo** [tensorflow/models#5602]
### System information
- **What is the top-level directory of the model you are using**: `research/deeplab`
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
- **TensorFlow installed from (source or binary)**: N/A
- **TensorFlow version (use command below)**: N/A
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: N/A

### Describe the problem
For DPC, only the cityscapes and imagenet trained models have been released. I think many people would greatly appreciate the PASCAL and PASCAL Person Part models as well. 

Not to mention that the DPC is a social animal by nature. I'm not sure I can support a model zoo with only two of them.

**Comment by aquariusjay** [comment]
Hi tqfjo,

Thanks for the query!
Currently, we do not have any plan to open-source the other checkpoints because (1) the PASCAL checkpoint has similar performance to the [one](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md#model-details) that has been already open-sourced, and (2) we need some more efforts to support PASCAL Person Part (e.g., tutorial, dataset conversion and so on).

**Comment by ymodak** [comment]
Closing this issue since @aquariusjay explanation resolves this issue. Feel free to reopen the issue if have any follow up questions. Thanks!
