### ISSUE TITLE
Type mismatch when exporting wide_deep model

### ISSUE THREAD

**Issue by Lw-Cui** [tensorflow/models#5679]
When exporting `wide_deep` model on `movielen` dataset I got error

```
TypeError: Value passed to parameter 'dense_defaults' has DataType int32 not in list of allowed values: float32, int64, string
```

It caused by `tf.uint8` in this [line](https://github.com/tensorflow/models/blob/3a6c5f11c25f01080e61012ac17218847487e971/official/wide_deep/movielens_dataset.py#L68):
```
 genres = tf.feature_column.numeric_column(
      movielens.GENRE_COLUMN, shape=(movielens.N_GENRE,), dtype=tf.uint8)
```

Here is my environment:
* Have I written custom code: No
* OS Platform and Distribution: custom Linux
* TensorFlow installed from: Docker
* TensorFlow version: 1.7.0 (git_hash: v1.7.0-3-g024aecf414)
* Bazel version: N/A
* CUDA/cuDNN version: 9.0.176 / 7005
* GPU model and memory: Tesla P40, 23015 MB memory
* Exact command to reproduce: Just run `python movielens_main.py -ed saved`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
