### ISSUE TITLE
do not compute loss

### ISSUE THREAD

**Issue by mjanddy** [tensorflow/models#5694]
How can I do not compute loss with some class? Because I don't want it to be a positive sample or negative sample.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by mjanddy** [comment]
Ubuntu 16.04 python2.7 tensorflow 1.10 cuda9.0 cudnn 7.05 GPU 1080ti 10GB

**Comment by robieta** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
