### ISSUE TITLE
Please provide us with a more detailed tutorail of syntaxnet framework

### ISSUE THREAD

**Issue by Yangyangainana** [tensorflow/models#576]
1.I think there must be some problems on Git Server, for I have tried for a week typing the same commands  @only to install bazel and syntaxnet. The ubuntu14.04 terminate always shows the errors that fetch data error or downloading error. Please check.
2.Fortunately, I can use syntaxnet framework now, but there are still some things that confuse me.  When I try to POS tag a corpus following the README, I do not know : 
     (1) Where does "wsj.conll" and "wsj-tagged.conll" come from? Are they input or output? Or are both of them input?
     (2)The complete commands or steps about how to POS tag a corpus, rather than the cpmmand pieces like:  "Then we can use --input=wsj-data --output=wsj-data-tagged on the command line to specify reading and writing to these files.". 

    Hope for reply. Thank you all for making the world better! @calberti

**Comment by asimshankar** [comment]
@Yangyangainana :  The files `wsj.conll` and `wsj-tagged.conll` do not exist in this repository. They are mentioned in the [Annotating a corpus](https://github.com/tensorflow/models/tree/master/syntaxnet#annotating-a-corpus) section just to illustrate the how you'd change `TaskSpec` protocol buffer in order to use your own files. In that particular example, `wsj.conll` would be the input and `wsj-tagged.conll` is the output because of the flag settings: `--input=wsj-data` and `--output=wsj-data-tagged` flag values mentioned in that section. Overall, this section of the README is trying to highlight how you would make changes to the configuration and flags to run on your own data. The spec file used in the demo is [`parsey_mcparseface/context.pbtxt`](https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/models/parsey_mcparseface/context.pbtxt) and the `--input` and `--output` flags are set in [`demo.sh`](https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/demo.sh#L31)

Slightly longer term though, we do hope to standardize on the description and instructions used for each of the models in this repository.

Since the ask here is a bit broad and we do have intentions to clarify the models in general, I'm going to go ahead and close this issue. If you have any specific suggestions on how to change the wording of the README, we gladly accept pull requests! @calberti may have thoughts as well. Thanks!
