### ISSUE TITLE
How to convert an image into uint8 tensor of type (1,300,300,3) in android

### ISSUE THREAD

**Issue by ramreddyy** [tensorflow/models#5839]
I am doing an android project.
I have a model and an image.
Now I want to detect the image , in order to do that I have to convert bitmap into an uint8 tensor of type (1,300,300,3).
Can someone explain how to do that?
Thanks in advance.

**Comment by ymodak** [comment]
May be [tf.image.decode_bmp](https://www.tensorflow.org/api_docs/python/tf/image/decode_bmp) can help you to achieve it.

**Comment by ramreddyy** [comment]
tf.image.decode_bmp is available in python. How to do the same in java / kotlin?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
