### ISSUE TITLE
object_detection_tutorial.ipynb error downloading model

### ISSUE THREAD

**Issue by pringithub** [tensorflow/models#6236]
I realize this notebook is over 1.5 years old, but it would be very useful to run correctly

I get an error when trying to download the model - the lastline is the offending one
```
# What model to download.
MODEL_NAME = 'ssd_mobilenet_v1_coco_2017_11_17'
MODEL_FILE = MODEL_NAME + '.tar.gz'
DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'
opener = urllib.request.URLopener()
**opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)**
```

What I'm assuming is happening here is the tensorflow server is not serving the data, nor throwing an error. Stopping the kernel also shows that the line is stuck at some recv().

Going to the DOWNLOAD_BASE url shows that one needs an account to log on ... the data does not automatically start downloading

I'm also running this from a company computer that may have proxies/firewalls (I'm not totally sure how all that stuff works) which may be stopping my request ..

Any ideas?

**Comment by pkulzc** [comment]
I just tested http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz and it still works. I guess the issue is with your internet.

BTW, for newer models you can visit our [model zoo page](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).
