### ISSUE TITLE
Yolov3 with TensorFlowobject detection API

### ISSUE THREAD

**Issue by Rahul-Venugopal** [tensorflow/models#6244]
Hi ,

Is it possible to use Yolov3 with Tensorflow Object detection API ?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Bahramudin** [comment]
Have the same question.

**Comment by rootkitchao** [comment]
It’s been a few months since the last update of the object detection API.The object detection API may need a lot of refactoring to fit Tensorflow 2.0,Because Tensorflow 2.0 removed the slim module.Although the object detection API does not have some implementations of the more critical models after 2017 (such as Deformable Convolutional Networks-v1-v2), and does not support new features such as mixed precision training.But this is still the hottest and most complete object detection project on github.
For models that are not in the model zoo, you may need to implement them yourself.But still thanks to all those who have maintained this project.

**Comment by pkulzc** [comment]
Unfortunately we don't have a plan for YOLO v3 at this moment. 

@rootkitchao we did start the TF 2.0 migration internally. We will release the next version when it's ready (may still take some time though).

Contributions to our project are always welcomed.

**Comment by AlexeyAB** [comment]
@pkulzc 

> Unfortunately we don't have a plan for YOLO v3 at this moment.

What is the main readon, is the reason low Accuracy/Speed compared to SOTA or the big efforts of adding Yolo support or something else?
