### ISSUE TITLE
How to train im2txt model with Open Images dataset?

### ISSUE THREAD

**Issue by okasanasan** [tensorflow/models#628]
Model: im2txt.

Please, explain if we can use Open Images dataset (https://research.googleblog.com/2016/09/introducing-open-images-dataset.html) for re-training the model?
We've already trained the model with MSCOCO dataset as it was written in docs https://github.com/tensorflow/models/tree/master/im2txt. Now we want to improve results and to train this model with Google Open Images dataset which has another format. 
Is it possible?
If yes how do we need to prepare the new dataset for training?

Thanks!

**Comment by girving** [comment]
Github issues are for bug reports and feature requests.  Please ask questions like this on StackOverflow.

**Comment by coliinkc** [comment]
@okasanasan Hey, I was wondering if you were able to re-train/fine-tune the model with a new dataset? If so, which words_counts file were you using? I am planning on fine-tuning the model (pre-trained on MSCOCO) with new data and I was wondering, if I should merge the word_counts files since the vocabulary differs. Any tips?

Thanks in advance!
