### ISSUE TITLE
absl.flags._exceptions.IllegalFlagValueError: flag --pipeline_config_path=None: Flag --pipeline_config_path must have a value other than None.

### ISSUE THREAD

**Issue by ravikantSTAR** [tensorflow/models#6372]
I'm trying to export the trained model in colab. Getting the following error.
Please help!

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 528, in _assert_validators
    validator.verify(self)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_validators.py", line 81, in verify
    raise _exceptions.ValidationError(self.message)
absl.flags._exceptions.ValidationError: Flag --pipeline_config_path must have a value other than None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/export_inference_graph.py", line 156, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 636, in __call__
    self._assert_all_validators()
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 510, in _assert_all_validators
    self._assert_validators(all_validators)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 531, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --pipeline_config_path=None: Flag --pipeline_config_path must have a value other than None.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by LEEcloudz** [comment]
> 我正在尝试在colab中导出训练好的模型。得到以下错误。
> 请帮忙！
> 
> 回溯（最近一次调用最后一次）：
> 文件“/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py”，第528行，在_assert_validators 
> validator.verify（self）
> 文件中“/ usr / local / lib / python3.6 / dist-packages / absl / flags / _validators.py“，第81行，在verify 
> raise _exceptions.ValidationError（self.message）
> absl.flags._exceptions.ValidationError：Flag --pipeline_config_path必须有一个除无以外的值。
> 
> 在处理上述异常期间，发生了另一个异常：
> 
> 回溯（最近一次调用最后一次）：
> 文件“object_detection / export_inference_graph.py”，第156行，在
> tf.app.run（）
> 文件中“/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform /app.py“，第119行，在运行
> argv = flags.FLAGS（_sys.argv，如果argv是无其他argv，known_only = True）
> 文件”/usr/local/lib/python3.6/dist-packages/tensorflow/ python / platform / flags.py“，第112行，在**call call**
> self中。**dict** ['__wrapped']。**调用**（* args，** kwargs）
> 文件“/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py”，第636行，**调用**
> self._assert_all_validators（）
> 文件“/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py”，第510行，在_assert_all_validators中
> self._assert_validators（all_validators）
> 文件“/usr/local/lib/python3.6/ dist-packages / absl / flags / _flagvalues.py“，第531行，在_assert_validators中
> 引发_exceptions.IllegalFlagValueError（'％s：％s'％（message，str（e）））
> absl.flags._exceptions.IllegalFlagValueError：flag - -pipeline_config_path =无：标志--pipeline_config_path必须具有None以外的值。

How do you solve this porblem? I meet the same question

**Comment by LEEcloudz** [comment]
I have solved this problem. The wrong is the argument. The command I copied from a blog causes this problem. Then I check the export_inference_graph.py and copy the example usage and then resolve this problem. Paste the following commad on your terminal and dont remmember change the path:
python export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path path/to/ssd_inception_v2.config \
    --trained_checkpoint_prefix path/to/model.ckpt \
    --output_directory path/to/exported_model_directory

**Comment by igs8** [comment]
how to solve it, please

**Comment by KathiravanNatarajan** [comment]
> how to solve it, please

in the blog, based on the tensorflow version, it could have been --output in the command line arguments. For example, in tensorflow 1.8 , the command line arguments are --output_directory, where as in tensorflow 1.12, it is just --output. So, make sure which version you use and check it in the file, for example, here it is export_inference_graph.py.

**Comment by CnMao2** [comment]
> > how to solve it, please
> 
> in the blog, based on the tensorflow version, it could have been --output in the command line arguments. For example, in tensorflow 1.8 , the command line arguments are --output_directory, where as in tensorflow 1.12, it is just --output. So, make sure which version you use and check it in the file, for example, here it is export_inference_graph.py.

I changed the command argument --output according to my tensorflow version, but it still doesn't work

**Comment by CnMao2** [comment]
So has anyone found a good solution to this problem? It almost drives me crazy since I don't know what to do with this 'flag --pipeline_config_path = None' problem.

**Comment by Oshana** [comment]
did you finds a solution?

**Comment by Oshana** [comment]
Found the solution. It is an inability in the windows command prompt. Use the command as this 

python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/ssd_mobilenet_v1_pets.config --trained_checkpoint_prefix training/model.ckpt-9133 --output_directory ships_inference_graph

copy together and use it. works for me

**Comment by etatbak** [comment]
> Found the solution. It is an inability in the windows command prompt. Use the command as this
> 
> python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/ssd_mobilenet_v1_pets.config --trained_checkpoint_prefix training/model.ckpt-9133 --output_directory ships_inference_graph
> 
> copy together and use it. works for me

It works for me, many thanks.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be an old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by moein1924** [comment]
Use this command line. This solved the issue for me:

python exporter_main_v2.py --input_type image_tensor --pipeline_config_path models/my_ssd_resnet50_v1_fpn/pipeline.config --trained_checkpoint_dir models/my_ssd_resnet50_v1_fpn/ --output_directory exported-models/

**Comment by bestfriend815** [comment]
Hi. It doesn't work on windows? Please someone tell me the solutions.

I have these issues.
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\flags\_flagvalues.py", line 510, in _assert_all_validators
    self._assert_validators(all_validators)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\flags\_flagvalues.py", line 531, in _assert_validators
    raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
absl.flags._exceptions.IllegalFlagValueError: flag --data_dir=None: Flag --data_dir must have a value other than None.

**Comment by moein1924** [comment]
> Hi. It doesn't work on windows? Please someone tell me the solutions.
> 
> I have these issues.
> File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\flags_flagvalues.py", line 510, in _assert_all_validators
> self._assert_validators(all_validators)
> File "C:\Users\Dell\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\flags_flagvalues.py", line 531, in _assert_validators
> raise _exceptions.IllegalFlagValueError('%s: %s' % (message, str(e)))
> absl.flags._exceptions.IllegalFlagValueError: flag --data_dir=None: Flag --data_dir must have a value other than None.

Can you write your command line you are using?

**Comment by NaumanHSA** [comment]
> Use this command line. This solved the issue for me:
> 
> python exporter_main_v2.py --input_type image_tensor --pipeline_config_path models/my_ssd_resnet50_v1_fpn/pipeline.config --trained_checkpoint_dir models/my_ssd_resnet50_v1_fpn/ --output_directory exported-models/

I used the exact same command but didn't work for me. Then I copied your command and it worked ... LOL

**Comment by ChrisrunnerR** [comment]
import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile

# adding here
import argparse

from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image
#0 for camera 1
import cv2
cap = cv2.VideoCapture(0)

# This is needed since the notebook is stored in the object_detection folder.
sys.path.append("..")


# ## Object detection imports
# Here are the imports from the object detection module.

# In[3]:

from utils import label_map_util

from utils import visualization_utils as vis_util


# # Model preparation 

# ## Variables
# 
# Any model exported using the `export_inference_graph.py` tool can be loaded here simply by changing `PATH_TO_CKPT` to point to a new .pb file.  
# 
# By default we use an "SSD with Mobilenet" model here. See the [detection model zoo](https://github.com/tensorflow/models/blob/master/object_detection/g3doc/detection_model_zoo.md) for a list of other models that can be run out-of-the-box with varying speeds and accuracies.

# In[4]:

# What model to download.
MODEL_NAME = 'new_graph' #changed 
#MODEL_FILE = MODEL_NAME + '.tar.gz'
#DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'

# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_CKPT = MODEL_NAME + '/frozen_inference_graph.pb'


# List of the strings that is used to add correct label for each box.
#PATH_TO_LABELS = os.path.join('training', 'label_map.pbtxt')
PATH_TO_LABELS = os.path.join('data', 'mscoco_label_map.pbtxt') #changed
                                      # mscoco_label_map.pbtxt

NUM_CLASSES = 1


# ## Download Model

# In[5]:                #changed# 
##
##opener = urllib.request.URLopener()
##opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)
##tar_file = tarfile.open(MODEL_FILE)
##for file in tar_file.getmembers():
##  file_name = os.path.basename(file.name)
##  if 'frozen_inference_graph.pb' in file_name:
##    tar_file.extract(file, os.getcwd())


# ## Load a (frozen) Tensorflow model into memory.  

# In[6]:
##
detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.compat.v1.GraphDef()
  with tf.compat.v2.io.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')





# ## Loading label map
# Label maps map indices to category names, so that when our convolution network predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility functions, but anything that returns a dictionary mapping integers to appropriate string labels would be fine

# In[7]:

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)


# ## Helper code

# In[8]:

def load_image_into_numpy_array(image):
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)


# # Detection

# In[9]:

# For the sake of simplicity we will use only 2 images:
# image1.jpg
# image2.jpg
# If you want to test the code with your images, just add path to the images to the TEST_IMAGE_PATHS.
PATH_TO_TEST_IMAGES_DIR = 'test_images'
TEST_IMAGE_PATHS = [ os.path.join(PATH_TO_TEST_IMAGES_DIR, 'image{}.jpg'.format(i)) for i in range(1, 3) ]

# Size, in inches, of the output images.
IMAGE_SIZE = (12, 8)


# In[10]:

with detection_graph.as_default():
  with tf.compat.v1.Session(graph=detection_graph) as sess:
    while True:
      ret, image_np = cap.read()
      # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
      image_np_expanded = np.expand_dims(image_np, axis=0)
      image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
      # Each box represents a part of the image where a particular object was detected.
      boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
      # Each score represent how level of confidence for each of the objects.
      # Score is shown on the result image, together with the class label.
      scores = detection_graph.get_tensor_by_name('detection_scores:0')
      classes = detection_graph.get_tensor_by_name('detection_classes:0')
      num_detections = detection_graph.get_tensor_by_name('num_detections:0')
      # Actual detection.
      (boxes, scores, classes, num_detections) = sess.run(
          [boxes, scores, classes, num_detections],
          feed_dict={image_tensor: image_np_expanded})
      # Visualization of the results of a detection.
      vis_util.visualize_boxes_and_labels_on_image_array(
          image_np,
          np.squeeze(boxes),
          np.squeeze(classes).astype(np.int32),
          np.squeeze(scores),
          category_index,
          use_normalized_coordinates=True,
          line_thickness=8)

      cv2.imshow('object detection', cv2.resize(image_np, (900,590)))
      if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
