### ISSUE TITLE
DELF details: how to combine delf local descriptors with DIR global descriptor?

### ISSUE THREAD

**Issue by LinXiLuo** [tensorflow/models#6409]
@andrefaraujo  

Thanks for your public code! But I have some problem with combining local descriptors with a single glocal descriptor. 
How did you concatenate a 2048-D descriptor to 40 1000-D descriptors? Please show me the detail about this issue. Thanks a lot again!

> DELF improves accuracy nontrivially inthedatasetswhencombinedwithDIR,althoughitdoesnot show the best performance by itself. This fact indicates that DELF has capability to encode complementary information that is not available in global feature descriptors.

**Comment by LinXiLuo** [comment]
I am eager for your reply as soon as possible.

**Comment by andrefaraujo** [comment]
The answer is in the paper:

"For this experiment, we simply obtain the score per image using the proposed method,
and make a late fusion with the score from DIR by computing a weighted mean of two normalized scores, where the weight for DELF is set to 0.25"

In other words: compute the DIR score by itself (ie, the distance between DIR descriptors of query and database); compute the DELF score by itself (ie, by computing the number of local feature matches between query and database image). Both scores are normalized, then combined via a weighted mean.

In particular, for this experiment, we used a KD-tree to index the database DELF local features (instead of brute-force matching), which is more realistic.

Hope this helps!

**Comment by LinXiLuo** [comment]
Got it! Thank you.
