### ISSUE TITLE
Objectmotion and Egomotion

### ISSUE THREAD

**Issue by knightzazh** [tensorflow/models#6465]
### System information
- **What is the top-level directory of the model you are using**: models/research/struct2depth
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18
- **TensorFlow installed from (source or binary)**: pip3
- **TensorFlow version (use command below)**: 1.5
- **Bazel version (if compiling from source)**: -
- **CUDA/cuDNN version**: CUDA 10
- **GPU model and memory**: 1080Ti 12GB
- **Exact command to reproduce**: inference.py

### Describe the problem
Good morning, I have using inference.py to get the ego motion and object motion (for object motion I add some modification in the code). I got egomotion.txt and objectmotion.txt .
But I have no view what the meaning of this file, I already read the code, this value is from the egomotion network & objectmotion network but I still haven't any view the meaning of this file. Is there anyone has view about the meaning is these value? I wonder that it is x y z motion and also the velocity of x y z.

I attached the example of egomotion and objectmotion output

Egomotion : 
![ego](https://user-images.githubusercontent.com/49016766/55135402-8a480300-5166-11e9-8632-232ff8f52962.JPG)

Objectmotion : 
![obj](https://user-images.githubusercontent.com/49016766/55135415-916f1100-5166-11e9-95ae-8aae7ac3e47b.JPG)

**Comment by ymodak** [comment]
@aneliaangelova Can you please take a look? Thanks!

**Comment by aneliaangelova** [comment]
Each line contains a number for the frame and two transforms each of 6 numbers.
The fist 6 numbers are transformation of frame 1_2 and the next are frame 2_3 (means 2 to 3)
Then within the 6 numbers, I assume it is x,y,z and then rot_around_x, rot_around_y, rot_around_z. 
You can check out the code and confirm that too - it is easy to track it. Thanks!

**Comment by knightzazh** [comment]
> Each line contains a number for the frame and two transforms each of 6 numbers.
> The fist 6 numbers are transformation of frame 1_2 and the next are frame 2_3 (means 2 to 3)
> Then within the 6 numbers, I assume it is x,y,z and then rot_around_x, rot_around_y, rot_around_z.
> You can check out the code and confirm that too - it is easy to track it. Thanks!

Oh I see, Thank you for your information

**Comment by na-hri** [comment]
@knightzazh Hey...can you exactly specify the modifications you made for getting the object motion?

**Comment by na-hri** [comment]
@aneliaangelova Great work! I have a few questions:
1) Are the intrinsic parameters of the camera required for getting object motion during inference time?
2) Is the way of getting object motion during inference simply to use the code starting [here](https://github.com/tensorflow/models/blob/0e0a94a6d1e0c149697994db726b6c1de1002276/research/struct2depth/model.py#L246) in the model.py file, or any further modification required?
3) The network predicts 2 transforms (each of 6 numbers) for a given triplet of images, for ex. for an input triplet frame 1_2_3, you get transformations for frame 1_2 and frame 2_3. We can also get a transformation for frame 2_3 by an input triplet frame 2_3_4. Ideally, these 2 transformation for frame 2_3 should be same right?
4) For converting the 6 DoF output vector to a trajectory w.r.t first frame of a sequence for either object motion or ego motion, what exact transformation should be used? I'm asking this because I've seen differences in the way people do that, so just want to confirm directly from you.

**Comment by aneliaangelova** [comment]
knightzazh@ correct. That will give the delta movement and you can apply Rot , Translation to the current position orientation to obtain the new one.

**Comment by aneliaangelova** [comment]
na-hri@
1.No you don't need the intrinsics for that. However the ego-motion or motion xyz outputs are in "network" units, i.e. are not tied to global metric system.
3. Correct, they should be the same, though I expect a small amount of noise if you swap their places like that.
2,4 vincentca@

**Comment by VincentCa** [comment]
Hi @na-hri,
2. Our example of the inference.py code currently instantiates the model with handle_motion set to False (default), causing it to not include the object motion network as part of the graph. But you can simply change this flag and use model.inference_objectmotion(...) to call object motion inference. Make sure your input data is prepared appropriately for networks trained with motion masks, i.e. use_masks=True, otherwise your results will be very off/unreasonable. Keep in mind that if you want object motion estimates, you do need to provide aligned segmentation masks for the data just as you would have to for training.
4. You could just build homogeneous transformation matrices from the transform vector estimates and apply those sequentially to an initial pose. However, the other ways you might have encountered are designed to mitigate numerical issues that will cause drift and I would recommend using them instead.
Hope this helps!
Vincent

**Comment by na-hri** [comment]
Hi @VincentCa @aneliaangelova 

Thanks for your response!

1) While training the object motion network, your code starting [here](https://github.com/tensorflow/models/blob/0e0a94a6d1e0c149697994db726b6c1de1002276/research/struct2depth/model.py#L246) uses intrinsic parameters, estimated ego motion and depth to modify the input for the object motion network. To get the object motion during test time, I'm assuming we need to follow the same modification steps? But this would require intrinsic parameters right?
2) I looked at 2 different repositories for generating the trajectory:
- Depth from videos in the wild (sequentially applies transform vector estimates to the initial pose [here](https://github.com/google-research/google-research/blob/ecaee3f601f219fd59649d6ce3b1f1e5f9b4d125/depth_from_video_in_the_wild/trajectory_inference.py#L139))
- SfMLearner (computes pose wrt first frame for subsequent transform vector estimates [here](https://github.com/tinghuiz/SfMLearner/blob/2a387b763bc2b6f95b095f929bf751797c9db68a/kitti_eval/pose_evaluation_utils.py#L371))

I believe the output vector from the above models has the same format as yours, but both have different transformations for generating the trajectory? Am I correct? Why is that so, and which one would you recommend for generating trajectories using your transformation vector estimates?

**Comment by na-hri** [comment]
@VincentCa @aneliaangelova Just a gentle reminder. Please let me know. Basically, I'm interested in plotting object and ego motion trajectories using output vector from your network.

**Comment by poornimajd** [comment]
> ### System information
> 
>     * **What is the top-level directory of the model you are using**: models/research/struct2depth
> 
>     * **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
> 
>     * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18
> 
>     * **TensorFlow installed from (source or binary)**: pip3
> 
>     * **TensorFlow version (use command below)**: 1.5
> 
>     * **Bazel version (if compiling from source)**: -
> 
>     * **CUDA/cuDNN version**: CUDA 10
> 
>     * **GPU model and memory**: 1080Ti 12GB
> 
>     * **Exact command to reproduce**: inference.py
> 
> 
> ### Describe the problem
> 
> Good morning, I have using inference.py to get the ego motion and object motion (for object motion I add some modification in the code). I got egomotion.txt and objectmotion.txt .
> But I have no view what the meaning of this file, I already read the code, this value is from the egomotion network & objectmotion network but I still haven't any view the meaning of this file. Is there anyone has view about the meaning is these value? I wonder that it is x y z motion and also the velocity of x y z.
> 
> I attached the example of egomotion and objectmotion output
> 
> Egomotion :
> ![ego](https://user-images.githubusercontent.com/49016766/55135402-8a480300-5166-11e9-8632-232ff8f52962.JPG)
> 
> Objectmotion :
> ![obj](https://user-images.githubusercontent.com/49016766/55135415-916f1100-5166-11e9-95ae-8aae7ac3e47b.JPG)

Hey could you please let me know what modifications you did in inference.py  to get the object motion?
I have tried giving motion masks directly with corresponding input, but have not been able to run and ended up getting a ValueError each time.

>   ValueError: operands could not be broadcast together with shapes (1,128,416,9) (3,128,416,27)

Can you please help me out?

**Comment by poornimajd** [comment]
> @VincentCa @aneliaangelova Just a gentle reminder. Please let me know. Basically, I'm interested in plotting object and ego motion trajectories using output vector from your network.

@na-hri have you been able to do this? I am also trying to interpret the output for object and ego motion.
Any suggestion is greatly appreciated!
Thank you

**Comment by mikibella** [comment]
Hello, is it possible to extract a object motion vector for every instance from the instance mask which will be provided inside the inference.py ?

**Comment by mikibella** [comment]
@knightzazh Did you were able to extract the objectmotion of the objects in the instance mask?

**Comment by mikibella** [comment]
@poornimajd did you were able to extract the object motion?

**Comment by mikibella** [comment]
@aneliaangelova 

> na-hri@ 1.No you don't need the intrinsics for that. However the ego-motion or motion xyz outputs are in "network" units, i.e. are not tied to global metric system. 3. Correct, they should be the same, though I expect a small amount of noise if you swap their places like that. 2,4 vincentca@

regarding 1. Is there a way to do a transfer to the global metric system from the "network units". 
Thank you
