### ISSUE TITLE
How to do transfer learning in only last layer in Tensorflow?

### ISSUE THREAD

**Issue by AI-LastWish** [tensorflow/models#6479]
I followed this tutorial https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

I know that by default, TF API initialize from a checkpoint but allow retraining for all layers.

But I just want to retrain only the last layer, because I want to use pre-trained model in COCO to train in Open Images dataset.

Are there anyone can tell me how to do that?
------------------------

### System information
What is the top-level directory of the model you are using:(I don't really understand the meaning of "top-level directory of the model")
I just followed https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

I used faster_rcnn_nas_lowproposals_coco downloaded from
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

OS Platform and Distribution:
Ubuntu 16.04
TensorFlow installed from:
GPU version of Tensorflow
TensorFlow version:
v1.12
Bazel version:
NA: don't know what is Bazel
CUDA/cuDNN version:
NA: don't know, but it's not the related to the problem
GPU model and memory:
Titan V
Exact command to reproduce:
NA

**Comment by rootkitchao** [comment]
You can set `from_detection_checkpoint: false`.
I think train a model in OID by init from a coco pre-trained model checkpoint may save some time,but also reduce the accuracy.

**Comment by AI-LastWish** [comment]
I'm using faster_rcnn_nas_coco.config, so you mean set `from_detection_checkpoint: false` in this file?
Moreover, I retrain only the last layer because I retrain faster_rcnn_nas_lowproposals_coco with input size: 1200x1200, which will led to 'OOM out of memory' error because the input resolution is so high, and it requires more RAM than RAM in my TITAN V(11 GB RAM)

**Comment by rootkitchao** [comment]
Sorry, I copied this paragraph directly from my config, you should set it to true.
I don't think it will save much memory, and the memory overhead of the model itself still exists. If you want to use high resolution, you can only replace models with fewer parameters.

**Comment by AI-LastWish** [comment]
But if I train with only the last layer, will it reduce the accuracy because of the model is optimized for COCO, not for Open Images. So if I retrain only the last layer, will I get bad result with Open Images?

**Comment by rootkitchao** [comment]
> But if I train with only the last layer, will it reduce the accuracy because of the model is optimized for COCO, not for Open Images. So if I retrain only the last layer, will I get bad result with Open Images?
Yes, of course. The MSCOCO data set is relatively small, so it is initialized from the ILSVRC checkpoint during training.But the OID v4 data set is relatively large, only need to train from scratch.So this will definitely reduce the accuracy slightly.

**Comment by ymodak** [comment]
Closing this issue since its addressed by rootkitchao's comment above. Feel free to reopen if have any further questions. Thanks!

**Comment by adrian1906** [comment]
It is still unclear on how to do transfer learning with the API
I'm looking for the proper way to add a class to a trained model. For example, the  **SSD with Mobilenet v1**

The methods I've seen using the object detection API involve making the following changes:
In the config file:

1. Change num_classes: 90 to num_classes: **1**
2. Change fine_tune_checkpoint:  to  **"../yourlocalpath/model.ckpt**
3. Keep from_detection_checkpoint: **true**
4. Change train_input_reader/ input_path: to **"../yourtrainimagepath/train.record"**
5. Change train_input_reader/ label_map_path to **"../yourlocalpath/classes.pbtxt"**
6. Change eval_input_reader / input_path to **"../yourtestimagepath/test.rocord"**
7. Change eval_input_reader / label_map_path to **"../yourlocalpath/classes.pbtxt"**

Also,

Change the file:  **"../yourlocalpath/classes.pbtxt"** to only contain:

```
item {
id: 1
name: 'some_new_class'
}
```


I trained 600 images for 200,000 epochs (18 hours) to a loss of 1.2. I achieved over 90% accuracy on the training data but less than 10% on the evaluation. This was clearly an overfit. My first take was that the model is too complex for a single item. It just memorized the training data.  I also noticed that the other 90 original items were no longer found.

I then change the num_classes to 91 and simply added 
item {
id: 91
name: 'some_new_class'
}
to the original classes.pbtxt file?

My results did not improve. (This time I stopped training around 100,000 epochs but the learning curve pretty much flattened by that point).

For both cases, I chose not to change the **"from_detection_checkpoint: true"** setting.
because "starting from a detection checkpoint will usually result in a faster training job than a classification checkpoint."  reference:  https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/configuring_jobs.md#model-parameter-initialization

What is the proper way to train an object detector to detect all objects (old and new)?
