### ISSUE TITLE
Error with bazel build inception/flowers_train

### ISSUE THREAD

**Issue by chrisrn** [tensorflow/models#667]
When running the above command I am receiving:

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=92
INFO: Reading options for 'build' from /etc/bazel.bazelrc:
  'build' options: --action_env=PATH --action_env=LD_LIBRARY_PATH --action_env=TMPDIR --test_env=PATH --test_env=LD_LIBRARY_PATH
Unrecognized option: --action_env=PATH

What's wrong?

**Comment by prb12** [comment]
This looks most likely to be a bazel version/installation issue and unlikely to have anything to do with the specific program you are trying to build.

For general build/usage support, could you please re-ask your question on StackOverflow. 
If you are sure that this problem is specific to this model then please re-open this issue and provide sufficient information to reproduce the issue (i.e. exact software versions, installation method and command lines)
