### ISSUE TITLE
[im2txt] slow inception execution

### ISSUE THREAD

**Issue by redserpent7** [tensorflow/models#715]
Hi,

I just completed the training for the im2txt model on 3M steps. I had no issues during training and it seems to be working fine. My problem is the time it takes to generate captions. It seems to be too slow, takes about 5-6 seconds per image, highly impractical given the fact that I need to generate captions for over 10M images, given the execution time this would take over 2 years. I tried with and without GPU and the result is the same.

I noticed that each time I execute run_inception it does some initialization (detecting cores, loading the model, etc) before it gets to generating captions, and this seems to me the longest part in the process.

So I was wondering if there is a way to have it running, much like a service, so it detects the cores and load the model only once instead of having to do that for each single image as its highly impractical.

Any ideas?

**Comment by cshallue** [comment]
@redserpent7 The flag [--input_files](https://github.com/tensorflow/models/blob/master/im2txt/im2txt/run_inference.py#L38) accepts a file-pattern or a comma-separated list of file-patterns, so you can generate captions for as many images as you like while only initializing the model once. Still, generating captions is a relatively slow process and will likely still take over a second per image.

You could try to reimplement beam search in C++ rather than Python, and perhaps this would be faster, but that's up to you! :)

**Comment by redserpent7** [comment]
Well I'm not keen on reimplementing  beam. All I wan is to keep the model loaded. Unfortunately using multiple input files at once is not ideal for my need. I don't mind re-implementing run_inception myself to keep the model loaded but I'm not sure where to start.

**Comment by tylertroy** [comment]
I have had some success with this using python's zmq library. You basically run a messaging cue and set up the model to caption in a loop. I have a GeForce 1080 Ti, with an i3 3.8GHz, proc, and 8MB of Ram and it takes about 1.5 seconds per image. If you're still interested feel free to message me.
