### ISSUE TITLE
strided_slice() missing 1 required positional argument: 'strides'

### ISSUE THREAD

**Issue by DanilBaibak** [tensorflow/models#752]
I'm working with **models/tutorials/rnn/ptb/**.

After run command `python ptb_word_lm.py --data=simple-examples/data/ --model small`:

```
Traceback (most recent call last):
  File "ptb_word_lm.py", line 371, in <module>
    tf.app.run()
  File "/home/danil/miniconda/envs/tf/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 331, in main
    train_input = PTBInput(config=config, data=train_data, name="TrainInput")
  File "ptb_word_lm.py", line 94, in __init__
    self.input_data, self.targets = reader.ptb_producer(data, batch_size, num_steps, name=name)
  File "/home/danil/projetcs/ml/boots/ptb_word_lm/reader.py", line 116, in ptb_producer
    x = tf.strided_slice(data, [0, i * num_steps], [batch_size, (i + 1) * num_steps])
TypeError: strided_slice() missing 1 required positional argument: 'strides'
```
Thanks in advance!

**Comment by aselle** [comment]
What version of TensorFlow are you using?

**Comment by DanilBaibak** [comment]
Currently, I'm using `tensorflow 0.12.0rc0`. 

The parameter `strides` is optional in the master branch. Maybe you know, when this changes will be released? :)

Thanks!

**Comment by aselle** [comment]
This will likely not make it into a release until 1.0 since 0.12 is cut.You can work around this on the model by adding a strides  to the model's call to strided_slice.

**Comment by DanilBaibak** [comment]
@aselle, yep, problem can be fixed with adding strides to the model. Thanks for help :)

**Comment by LeenaShekhar** [comment]
Hello,

I cannot understand what is the fix for this problem. Can somebody please help. Below is the error:

 python ptb_word_lm.py --data_path=/home/user/Downloads/simple-examples/data/ --model small
Traceback (most recent call last):
  File "ptb_word_lm.py", line 374, in <module>
    tf.app.run()
  File "/home/user/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 334, in main
    train_input = PTBInput(config=config, data=train_data, name="TrainInput")
  File "ptb_word_lm.py", line 94, in __init__
    data, batch_size, num_steps, name=name)
  File "/home/user/anaconda3/lib/python3.5/site-packages/tensorflow/models/tutorials/rnn/ptb/reader.py", line 117, in ptb_producer
    [batch_size, (i + 1) * num_steps])
TypeError: strided_slice() missing 1 required positional argument: 'strides'

**Comment by DanilBaibak** [comment]
Hi @LeenaShekhar,

for fix this issue you can try adjust `reader.py` like:
`x = tf.strided_slice(data, [0, i * num_steps], [batch_size, (i + 1) * num_steps], tf.ones_like([0, i * num_steps]))`

**Comment by LeenaShekhar** [comment]
Thank you so much as that solved the problem, but I am still getting errors. Is it because of TF version? I installed it using the Anaconda installation steps mentioned on the website (see the TF folder path). I want to run the RNN and Seq2Seq model. Is there a preferred installation process? I really appreciate your fast response.

python ptb_word_lm.py --data_path=/home/usr/Downloads/simple-examples/data/ --model small
Traceback (most recent call last):
  File "ptb_word_lm.py", line 374, in <module>
    tf.app.run()
  File "/home/user/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 336, in main
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "ptb_word_lm.py", line 119, in __init__
    cell = tf.contrib.rnn.MultiRNNCell(
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'MultiRNNCell'

**Comment by LeenaShekhar** [comment]
The code seems to work now. I am able to train the model. I made the following changes:
1. Added the changes pointed by @DanilBaibak in reader.py (2 places).
2. Changed tf.contrib.rnn.MultiRNNCell to tf.nn.rnn_cell.MultiRNNCell.
3. Changed tf.contrib.legacy_seq2seq.sequence_loss_by_example to tf.nn.seq2seq.sequence_loss_by_example.

Thank you.

**Comment by hfirouzi** [comment]
My code started working after applying changes suggested by @DanilBaibak and @LeenaShekhar and also these two changes in ptb_word_lm.py:
1) tf.contrib.rnn.BasicLSTMCell  --> tf.nn.rnn_cell.BasicLSTMCell
2) tf.contrib.rnn.DropoutWrapper --> tf.nn.rnn_cell.DropoutWrapper

I am running the code in windows (python 3.5 and pip "https://www.tensorflow.org/install/install_windows")

**Comment by taylorty** [comment]
@hfirouzi and @LeenaShekhar: I encountered the same problem but after I updated Tensorflow with pip installation by following link here (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#pip-installation), everything works fine. They usually keep updating the binary url of the latest Tensorflow on the page. Hope it helps.

**Comment by oelgendy** [comment]
@LeenaShekhar Thanks for your comment. Where can I find the files tf.contrib.rnn.MultiRNNCell and tf.contrib.legacy_seq2seq.sequence_loss_by_example??
