### ISSUE TITLE
can you add more instructions on keypointnet?

### ISSUE THREAD

**Issue by aohan237** [tensorflow/models#7582]
about how to what is the format for dataset, and how to generate my own dataset.

and if there si any faq for this model, like object detection api does.

thanks in advance

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by vedenev** [comment]
aohan237, have you tried the keypoint net? Was it succesfull? Does it detects the points precisly? What is your task?

**Comment by aohan237** [comment]
nope. i have to imple one by myself.

these models seem that they provide only to show their muscle.

and of course, it seems that they dont have the motivation to provide these things

thanks any way

**Comment by vedenev** [comment]
Thank you, aohan237. Why did you imple it by yourself? Does the models/research/keypointnet/ work? Does it have bugs? What was the problem? How did you implement it by yourself? Was it difficult? How much time did you spend? What is your objects? Does it have stable training? I'am asking because I think about to try the keypointnet for keypoints detection of real planes but I'am afraid to spend a lot of time for this because of bugs, no documentation, ect. Please answer my questions and I will be able to decide to try the keypointnet or not.

**Comment by aohan237** [comment]
I'm afraif that i cant answer you too much questions.

what i can answer that is try to use models which have detailed document and instructions.

otherwise, it will be a waste of time.
