### ISSUE TITLE
hi, tensorflow object detection API

### ISSUE THREAD

**Issue by gloomyfish1998** [tensorflow/models#7647]
i just want to know whether tensorflow object detection API already support tensorflow 2.0 now //???

i did not see any release notes on this ,please let me know ~~~~~

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by njanirudh** [comment]
@gloomyfish1998  I dont think the object detection api is ported to [tf 2.0]
you will have to use the older scripts for running them i guess

**Comment by enyangxxx** [comment]
i also meet the error "module 'tensorflow' has no attribute 'GraphDef'". is it removed from tf 2.0.0?

**Comment by njanirudh** [comment]
@enyangxxx  can you give a brief description of which model, scripts and tf version are you using?

**Comment by saberkun** [comment]
Hi, I heard keras team has some models ported to TF2 in OD api.
@tomerk Can keras team share some code pointers?

**Comment by enyangxxx** [comment]
tf version is 2.0.0, script is https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
section **Load a (frozen) Tensorflow model into memory.**

**Comment by tomerk** [comment]
CC'ing @jch1 @tombstone .

The object detection API does not work just yet externally in TF2 because certain contrib imports need to be avoided. Model_lib_v2 contains the logic to train in TF2 with eager + tf.functions https://github.com/tensorflow/models/blob/master/research/object_detection/model_lib_v2.py

But there is currently no open sourced model_main.sh file to call these methods. Contributions are welcome if anyone wants to put together a model_main_v2 script, & to make the contrib imports conditional on TF version. Alternatively, you can wait until the Object Detection team has time to do this (But I can't speak to their timelines)

**Comment by guizili0** [comment]
> tf version is 2.0.0, script is https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb
> section **Load a (frozen) Tensorflow model into memory.**

emm, this part was removed just now.

**Comment by njanirudh** [comment]
This shows just the detection...Is there any scripts for training the model also as part of the new API in [TF2.0]

**Comment by wAikAp** [comment]
As anyone knows any other ways to train the model with TF2.0 for now situation?

**Comment by horczech** [comment]
Any news considering the retraining of object detection models with TF2?

**Comment by tnaduc** [comment]
Anyone knows if TF2x object detection api is available yet?
