### ISSUE TITLE
ImportError: cannot import name 'mobilenet_v3'

### ISSUE THREAD

**Issue by Diaislam** [tensorflow/models#7760]
I am experiencing an issue when i test object detection or when i train

this error keeps occuring:
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/root/dia/tensorflow/models/research/object_detection/builders/model_builder.py", line 56, in <module>
    from object_detection.models.ssd_mobilenet_v3_feature_extractor import SSDMobileNetV3LargeFeatureExtractor
  File "/root/dia/tensorflow/models/research/object_detection/models/ssd_mobilenet_v3_feature_extractor.py", line 25, in <module>
    from nets.mobilenet import mobilenet_v3
ImportError: cannot import name 'mobilenet_v3'

i have no problem with path or anything 
cuda version : CUDA Version 9.0.176
tensorflow version 1.12 and 1.14 (tried with both)
python version (3.5,3.6,3.7) tried them all

**Comment by siyiding1216** [comment]
Same here. Using TF.1.13.1

**Comment by siyiding1216** [comment]
Have it fixed. Check your PYTHONPATH

**Comment by Diaislam** [comment]
> Have it fixed. Check your PYTHONPATH
i checked and everything alright
its not the first installation of object detection api i make
this is weird this time

**Comment by Diaislam** [comment]
i guess it's due to the last commit of 15-october

**Comment by Diaislam** [comment]
i fixed that error by git checkout "ID"
ID of the commit before adding mobilenet_v3 
now it works perfectly

**Comment by SeraphWeng** [comment]
So may I ask that how did you fix that?

**Comment by Marwen-Bhj** [comment]
> i fixed that error by git checkout "ID"
> ID of the commit before adding mobilenet_v3
> now it works perfectly
can you explain more, what do you mean with gut checkout 'ID' ?

**Comment by PravinVedurla** [comment]
For future readers, I've faced the same problem. Turns out it's because the nets folder is probably outdated In the version you're using. 
A quick workaround is to download the latest version of TensorFlow models.
[https://github.com/tensorflow/models](url)
then copy contents of "~/models/research/slim/nets/mobilenet" from the latest version to your project directory following a similar path, must be "~/models/research/slim/nets/mobilenet" again. Just replace the files when prompted, and you've gotta build slim after this copy.

in the folder dir "~/model/research/slim"
`python setup.py build
python setup.py install`

Worked like a charm for me.
PS: Also make sure your PYTHONPATHs are all good.
