### ISSUE TITLE
Transformer base model in models/official/transformer does not reach the reported BLEU score on ende translation task

### ISSUE THREAD

**Issue by Urmish** [tensorflow/models#7816]
### System information
- **What is the top-level directory of the model you are using**:
models/official/transformer
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: Docker Image (nvcr.io/nvidia/tensorflow:19.07-py3)
- **TensorFlow version (use command below)**: 
>>> import tensorflow as tf
2019-11-15 22:10:12.854264: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
>>> print(tf.__version__)
1.14.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: Cuda version 10.1, Driver version 418.56, 
- **GPU model and memory**: 2 GeForce RTX 2080 with 11 GB memory each
- **Exact command to reproduce**:
Commands used -
1.  python transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR \
    --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET \
    --bleu_source=$DATA_DIR/newstest2014.en --bleu_ref=$DATA_DIR/newstest2014.de --num_gpus=2
2.  python transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR \
    --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET \
    --bleu_source=$DATA_DIR/newstest2014.en --bleu_ref=$DATA_DIR/newstest2014.de --num_gpus=1
3.  python transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR \
    --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET \
    --bleu_source=$DATA_DIR/newstest2014.en --bleu_ref=$DATA_DIR/newstest2014.de --num_gpus=2 --batch_size=4096
4.  python transformer_main.py --data_dir=$DATA_DIR --model_dir=$MODEL_DIR \
    --vocab_file=$VOCAB_FILE --param_set=$PARAM_SET \
    --bleu_source=$DATA_DIR/newstest2014.en --bleu_ref=$DATA_DIR/newstest2014.de --num_gpus=2 --batch_size=8192

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
I used the instructions provided by the official/transformer to train the transformer base network for en-de translation task. I used the instructions as is. However, I never reached the baseline accuracy of 27.7. For some batch-sizes the model diverges to NaN, for others the accuracy increases to 23/24 bleu_uncased score and then starts decreasing again. I tried training these networks for more epochs and yet ran into similar issue.
BS/num_gpus - Best Bleu
2/2048 - NaN
2/4096 - 25.554
1/2048 - 24.40
2/8192 - NaN
2/10000 - NaN

Am I doing something wrong, or is there an issue with the source code/ README?
### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by xinliupitt** [comment]
Hello Urmish! Could you let me know the loss value you got when you finished training the model? Also did you set train_steps to a specific value or just use the default value?

**Comment by jiunoh** [comment]
I am having the same issue. My version is 2.3.0 and my model(base) never reached BLEU 27 or 26. It stopped at about 25.7. 
I modified the vocab_size to 33945 because it was hardcoded to different number(33708). train_steps was 800000 and max_length was 256.
(By the way, where did 27.7 come from? I cannot find the expected score in README, and baseline score in the paper was 27.3)

**Comment by xinliupitt** [comment]
Hi jiunoh! Could you post your complete parameter settings? That is, apart from vocab_size, train_steps, what did you set for other parameters? Then I am able to understand your situation more detailedly.

**Comment by jiunoh** [comment]
full command:
```
python transformer_main.py --data_dir=$DATA_DIR --model_dir=ENDE/model \
--vocab_file=$DATA_DIR/vocab.ende.32768 --param_set=base --train_steps=800000 \
--steps_between_evals=20000 --max_length=64 --batch_size=2048 \
--bleu_source=$DATA_DIR/newstest2014.en \
--bleu_ref=$DATA_DIR/newstest2014.de \
--num_gpus=1 \
--enable_time_history=false --enable_tensorboard=true
```

I thought that the max_length limited the score, so I tried

```
python transformer_main.py --data_dir=$DATA_DIR --model_dir=$DATA_DIR/model \
--vocab_file=$DATA_DIR/vocab.ende.32768 --param_set=base --train_steps=800000 \
--steps_between_evals=20000 --max_length=256 --batch_size=2048 \
--bleu_source=$DATA_DIR/newstest2013.en \
--bleu_ref=$DATA_DIR/newstest2013.de \
--num_gpus=1 \
--enable_tensorboard=true
```

(used newstest2013 as eval set and newstest2014 as test set this time)
but both results were about 25.7. never reached 27 or 26 anyway.
I did not changed other hyperparameters(learning rate, dropout rate, etc) except the vocab_size.
Also, I inserted try/except in the transformer_main.py

```
      try:
        if (flags_obj.bleu_source and flags_obj.bleu_ref):
          uncased_score, cased_score = self.eval()
          cased_score_history.append([current_iteration + 1, cased_score])
          uncased_score_history.append([current_iteration + 1, uncased_score])
      except Exception as e:
        pass
```
because sometimes self.eval() raised an exception `ValueError: Reference and translation files have different number of lines` and stopped training. But I don't think that this code would change the result.

**Comment by xinliupitt** [comment]
I am glad to see your detailed params! I think I found the key problem. The following is my command:

```
python3 transformer_main.py \
    --model_dir=${MODEL_DIR} \
    --data_dir=${GCS_DATA_DIR} \
    --vocab_file=${GCS_DATA_DIR}/vocab.ende.32768 \
    --bleu_source=${GCS_DATA_DIR}/newstest2014.en \
    --bleu_ref=${GCS_DATA_DIR}/newstest2014.de \
    --batch_size=24576 \
    --train_steps=300000 \
    --steps_between_evals=10000 \
    --param_set=big \
    --max_length=64 \
    --decode_batch_size=32 \
    --decode_max_length=97 \
    --num_gpus=8
```
I got BLEU score 28.4 at around 250k steps.

My batch size is very large, 24576, with `param_set=big`. I use 8 "V100" GPUs in Google Cloud Platform to run this model. 

Although you use `param_set=base`, it still needs a large batch size. Since you have 1 GPU, it may not be able to efficiently process 24576 batch size. You can try whether batch size larger than 2048 (e.g., 4096) gives you a better BLEU score. I think it will give you a little better BLEU score, but may not reach 27.

To reach benchmark performance (BLEU score 27.3 for base, 28.4 for large), I highly recommend to train the model with 24576 batch size in multiple GPUs in Google Cloud Platform.

This file gives you more information about params in the model:
https://github.com/tensorflow/models/blob/master/official/nlp/transformer/model_params.py



You also mention the exception `ValueError: Reference and translation files have different number of lines`. This is because the model is not well trained. This happens to me when the model overfits. The phenomenon of overfitting is that, I can see BLEU score decreases (from 19 to 11, 7, 5...) as I have more checkpoints, even if the training loss is decreasing. Finally I get that exception error message.

Hope this helps!

**Comment by jiunoh** [comment]
I see. My GPU is RTX 2080ti 11GB RAM, so I reduced my batch size too much. I will try 4096 or bigger(although it will may not reach 27, as you said). 
For the exception ValueError, it seems not overfitting because the exception occurred even at step 20K~40K, which is the early stage of training. But maybe it also would be due to the batch size, I suspect.

It helped me a lot. Thank you for comments!

**Comment by laxmareddyp** [comment]
Hi @Urmish,

This issue same as [this](https://github.com/tensorflow/models/issues/9830) and already alternate solution was provided in [this](https://github.com/tensorflow/models/issues/9830) and still  you would like to have discussions continue here.
Thanks.
