### ISSUE TITLE
Multi GPU not being utilized

### ISSUE THREAD

**Issue by kun-dao** [tensorflow/models#7885]
I  have four TITAN XP cards , but only one of them  has been used, anyone has ideas?

**Comment by saberkun** [comment]
What TF version do you use? For TF2 mirrored strategy, you can make sure devices are passed correctly.

**Comment by wxjcn** [comment]
I meet something similar. I'm trying to run resnet_imagenet_main.py on multiple machines with multiple GPUs, but the tensorflow log shows "Device is available but not used by distribute strategy". (Tensorflow1.14, MultiWorkerMirroredStrategy ")

**Comment by saberkun** [comment]
You probably need to use TF 2.1 with multi worker mirrored strategy. It should be ready now.
@yuefengz

**Comment by dao-kun** [comment]
Thanks a lot ! my  TF version is 1.12, I will retry it ,here a another my question #7893, can you take a moment to have a look, please！

**Comment by saberkun** [comment]
Another thought. I did a similar mistake by forget setting some num_gpus flag.
If you use mirroredstrategy, by default it uses all gpus.
However, the utils we have: https://github.com/tensorflow/models/blob/master/official/utils/misc/distribution_utils.py#L84
requires providing a number of gpus because it supports using some of all gpus....

**Comment by saberkun** [comment]
The code has been moved to benchmark only repo.
