### ISSUE TITLE
Training and serving a realtime mobile object detector error: 404 ValidateBoxes(decoded_boxes, num_boxes) was not true

### ISSUE THREAD

**Issue by Brechard** [tensorflow/models#7918]
### System information
- **What is the top-level directory of the model you are using**: research/object-detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 18.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.15
- **Bazel version (if compiling from source)**: 0.26.1
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I have tried to follow the tutorial in: 

https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193

and tried to train using the config files for mobilenet v1 and v3 and I always get the same error in android studio.

    2019-12-06 14:44:56.286 15984-15984/? E/Zygote: isWhitelistProcess - Process is Whitelisted
    2019-12-06 14:44:56.286 15984-15984/? E/Zygote: accessInfo : 1
    2019-12-06 14:44:57.381 15984-16054/org.tensorflow.lite.examples.detection     E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 15984
    java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/detection_postprocess.cc:404 ValidateBoxes(decoded_boxes, num_boxes) was not true.
    Node number 63 (TFLite_Detection_PostProcess) failed to invoke.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:152)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:296)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:193)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)

The config files I have tried are:
ssd_mobilenet_v1_0.75_depth_quantized_300x300_pets_sync.config
ssdlite_mobilenet_v3_large_320x320_coco.config
changing only the paths to the tfrecords, the label maps and the original model.

I have uploaded in the link the tfrecords that I use, the label maps for training and android studio and the tflite model after conversion for the mobilenet v1.

https://1drv.ms/u/s!AjxID0PP8Jlkld0v3Iscv454cMiubQ?e=ugr9dh

and this are the commands I run:
cd ~/models/research/

export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
export CONFIG_FILE=/home/brechard/models/google/ssd_mobilenet_v1_0.75_depth_quantized_300x300_pets_sync.config
export CHECKPOINT_PATH=/tmp/training/mobilenetv1/model.ckpt-2000
export OUTPUT_DIR=/tmp/tflite

python object_detection/model_main.py \
	--pipeline_config_path=$CONFIG_FILE \
	--model_dir=/tmp/mobilenetv1/training/ \
	--num_train_steps=2000 \
	--alsologtostderr \
	--sample_1_of_n_eval_examples=1

python object_detection/export_tflite_ssd_graph.py \
	--pipeline_config_path=/home/brechard/models/google/ssd_mobilenet_v1_0.75_depth_quantized_300x300_pets_sync.config \
	--trained_checkpoint_prefix=/tmp/mobilenetv1/training/model.ckpt-2000 \
	--output_directory=/home/brechard/models/google/mobilenetv1/tflite \
	--add_postprocessing_op=true

_for installing tensorflow:
git clone http://github.com/tensorflow/tensorflow /tmp/tf
cd /tmp/tf
git checkout r1.15
./configure_

bazel run -c opt tensorflow/lite/toco:toco -- \
--input_file=/home/brechard/models/google/mobilenetv1/tflite/tflite_graph.pb \
--output_file=/home/brechard/models/google/mobilenetv1/tflite/detect-mobilenetv1.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 \
--std_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops

once I get the tflite model, I just put it in the assets folder, replace the labelmap and set TF_OD_API_MODEL_FILE = detect-mobilenetv1.tflite

UPDATE: There is no need to load in Android studio, if the models are loaded in python like this:

    import numpy as np
    import tensorflow as tf

    # Load TFLite model and allocate tensors.
    interpreter = tf.lite.Interpreter(model_path=PATH_TO_TFLITE)
    interpreter.allocate_tensors()

    # Get input and output tensors.
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    # Test model on random input data.
    input_shape = input_details[0]['shape']
    input_data = np.array(np.random.random_sample(input_shape), dtype=np.uint8)
    input_tensor= tf.convert_to_tensor(input_data, np.uint8)
    interpreter.set_tensor(input_details[0]['index'], input_tensor)

    interpreter.invoke()
 you get the following error:

    RuntimeError: tensorflow/lite/kernels/detection_postprocess.cc:402 ValidateBoxes(decoded_boxes, num_boxes) was not true.Node number 63 (TFLite_Detection_PostProcess) failed to invoke.

**Comment by MichaelW17** [comment]
I got the same error here with ssd_mobilenet_v2 and FLOAT tflite

**Comment by hvico** [comment]
Same problem here, error:  tensorflow/lite/kernels/detection_postprocess.cc:404 ValidateBoxes(decoded_boxes, num_boxes) was not true.

Using SSD, export_tflite_ssd_graph.py and TOCO.

**Comment by JimKimHome** [comment]
I have trained 6 models:

1. ssd_mobilenet_v1 with pretrained checkpoint
2.ssd_mobilenet_v1_0.75 with pretrained checkpoint
3.ssd_mobilenet_v1_0.125 without pretrained checkpoint
4.ssd_mobilnetnet_v2 with pretrained checkpoint
5.ssdlite_mobilnet_v2 with pretrianed checkpoint
6.ssdlite_mobilenet_v3_small without pretrained checkpoint

after trianed each model for 200k steps or less,I converted them into tflite models with command like :
`python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path /home/xxx//ssd_mobilenet_v1_0.75.config \
--trained_checkpoint_prefix /home/xxx/model.ckpt-200000 \
--output_directory /home/xxx/saved_model`
and 
`tflite_convert --output_file /home/xxx/tflite_graph.tflite \
--graph_def_file /home/xxx/saved_model/tflite_graph.pb  \
--input_arrays "normalized_input_image_tensor" \
--input_shapes "1,300,300,3" \
--output_arrays 'TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' \
--output_format TFLITE \
--inference_type=FLOAT \
--input_data_type=FLOAT \
--allow_custom_ops`
then I try to load each tflite model in Android Studio to do inference,and I got error like @Brechard just mentioned when the model is ssd_mobilenet_v2 or ssdlite_mobilenet_v2 , so I convert a new tflite model with anohter ssd_mobilenet_v2 ckpt which is not the final ckpt, and the new one worked fine. However I can not resolve the problem when it comes to ssdlite_mobilenet_v2.

the other day, I write a python code to load tflite model to do inference on multiple images,and then something  weird happended, some models can inference on all images and some can only do inference on a few images:
![image](https://user-images.githubusercontent.com/11896420/81273969-3fdfc800-9082-11ea-9391-de9a8d0fea3a.png)
I wonder if this is because of the preprocess of the input images, so I change the code:
input_image = (2.0 / 255.0) * input_image - 1.0
into:
input_image = (1.0 / 255.0) * input_image
the inference worked ,but the result is different between two method
 actually there is official description telling us the input should be in [-1,1]:
![image](https://user-images.githubusercontent.com/11896420/81274423-d7ddb180-9082-11ea-817f-37f1759e5caa.png)
But I just can not do inference with some tflite models when I use the first preprocessing method, in conclution, models trained without pretrianed model will worked fine in tflite mode and models trained with pretrained model will suffer from 'ValidateBoxes(decoded_boxes, num_boxes) was not true' problems when doing inference.

**Comment by siyangbing** [comment]
Me too, can't solve this problem, this is a problem that came out recently, there is no problem before

**Comment by csmcallister** [comment]
I had the same issue using the `ssd_mobilenet_v2_quantized_300x300_coco` model. I was able to finetune for a couple dozen steps on my data and then export the graph, convert to tf lite, and use the python tf lite interpreter. But when I finetuned on my own data again for ~200,000 steps and repeated the same process, it failed with the `ValidatedBoxed` error message. I'm on Windows 10 using TF version 1.15.0 (through conda as tensorflow-gpu). **Downgrading to tensorflow-gpu=1.13 got it to work.**

**Comment by BernardinD** [comment]
Any update on this issues? It happens to me as well when using GoogleColab with version 1.15.x

**Comment by nrasadi** [comment]
I also have the same issue.
- OS Platform and Distribution: Linux Ubuntu 16.04
- Model: SSD MobileNetV2
- Tensorflow-gpu=2.2 (Installed using conda)

I fine-tuned the model on my own dataset (11 classes). It has been converted successfully but the mentioned error occurs when I call invoke() method.
I am using Python API of TFLite interpreter.

**Code:**
tflite_interpreter = tf.compat.v1.lite.Interpreter(model_path=tflite_model_file)
tflite_interpreter.allocate_tensors()
input_details = tflite_interpreter.get_input_details()
output_details = tflite_interpreter.get_output_details()
image = cv2.imread('images.jpeg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = cv2.resize(image, (300, 300))
image = np.expand_dims(image, 0)
tensor = tf.compat.v1.convert_to_tensor(np.array(image) / 255. , dtype='float32')
tflite_interpreter.set_tensor(input_details[0]['index'], tensor)
tflite_interpreter.invoke()

**Comment by Jonathan995** [comment]
Did somebody manage to solve the problem? I am facing the same issue after having trained ssd_mobilenet_v1_0.75 with pretrained checkpoint on TF1.15 and then converted it to TFLite.

**Comment by ipetel** [comment]
I was encountered with the same issue as described here.
here is my error: `RuntimeError: tensorflow/lite/kernels/detection_postprocess.cc:402 ValidateBoxes(decoded_boxes, num_boxes) was not true.Node number 63 (TFLite_Detection_PostProcess) failed to invoke.`

My workaround was to [build TF from source](https://www.tensorflow.org/install/source) while changing the "[detection_postprocess.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/detection_postprocess.cc)" file to print the box.ymin, box.ymax, box.xmin, and box.xmax values instead of return False, what cause the raise of this error.

**my finding were that few boxes had the same value for the ymin and ymax, and for the xmin and xmax.** 
following this change, my code was able to run and produce great results.

**Comment by egamez099** [comment]
Is there any solution?
I do have the same error with a rpi 3 with tensorflow 1.15.2, tried to downgrade with tf 1.13 and below but the error still occurs. 
The weirdest thing is that if I run the code on my workstation (tf 1.15.2), runs flawlessly without any error...

Any help will be so apreciated.

**Comment by lu-wang-g** [comment]
We've made a fix today, and relaxed the constraint of verifying boxes. So now cases that xmin=xmax or ymin=ymax won't raise the error, and the rest of the pipeline can handle this case very well.

It fix will be available in the tf-nightly build tomorrow.

**Comment by Ectrics** [comment]
> We've made a fix today, and relaxed the constraint of verifying boxes. So now cases that xmin=xmax or ymin=ymax won't raise the error, and the rest of the pipeline can handle this case very well.
> 
> It fix will be available in the tf-nightly build tomorrow.

I had this error as well. Some images were invoked without problems, while others caused this error. Indeed `pip install tensorflow==2.5.0-dev20210301` fixed it.

**Comment by Azazel17** [comment]
I have this same issue on my Android project using flutter, works great with images, loaded from gallery but in real time and also on image taked with the camera i get this error 
Caused by: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: tensorflow/lite/kernels/detection_postprocess.cc:426 ValidateBoxes(decoded_boxes, num_boxes) was not true.
