### ISSUE TITLE
what is the process of training the custom model in models/official/vision/detection

### ISSUE THREAD

**Issue by sreenupadidapu** [tensorflow/models#8069]
Please go to Stack Overflow for help and support:

http://stackoverflow.com/questions/tagged/tensorflow

Also, please understand that many of the models included in this repository are experimental and research-style code. If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **What is the top-level directory of the model you are using**:
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by yeqingli** [comment]
I assume this is for experimenting models in your own environment.
The answer depends on how different is the model. To train a new model, the training entry is  [main.py](https://github.com/tensorflow/models/blob/master/official/vision/detection/main.py).

Here are a few steps of how to add new models.

 If you want to just build a simple model, say MyRetinaNet,  on top of current existing components like layers, losses, existing heads, you might need to: 

1. Add a config template for the new model like [this one](https://github.com/tensorflow/models/blob/master/official/vision/detection/configs/retinanet_config.py).
2. add a file "my_retinanet_model.py" in the modeling folder (similar to "retinanet_model.py") and implement the model. 
3. add a branch to the [factory file](https://github.com/tensorflow/models/blob/master/official/vision/detection/modeling/factory.py) so that you can use it in [main.py](https://github.com/tensorflow/models/blob/master/official/vision/detection/main.py).

If you want to add some fine-grained components like heads and backbones, the you need to add something to the [models/official/vision/detection/modeling/architecture/](https://github.com/tensorflow/models/tree/master/official/vision/detection/modeling/architecture) folder.

1. Add a class to heads.py (for heads) or a new .py file for backbones.
2. Update the [factory.py](https://github.com/tensorflow/models/blob/master/official/vision/detection/modeling/architecture/factory.py) accordingly.
3. You might also need to change [the model configs](https://github.com/tensorflow/models/blob/master/official/vision/detection/configs/retinanet_config.py) accordingly,

For even finer-grained ops, you can add to [ops](https://github.com/tensorflow/models/tree/master/official/vision/detection/ops) and [utils](https://github.com/tensorflow/models/tree/master/official/vision/detection/utils)

Hope this helps.

**Comment by laxmareddyp** [comment]
Hi @sreenupadidapu,

Please let us know that, did you get chance to review above workaround provided.

Thanks.
