### ISSUE TITLE
models/official/vision/image_classification/ How to implement trained model?

### ISSUE THREAD

**Issue by SabinaUS** [tensorflow/models#8199]
**Please provide the entire URL of the model you are using?**

**Describe the feature you request and the current behavior/state.**

**Are you willing to contribute it (Yes/No)?**

**Any other info.**

**Comment by SabinaUS** [comment]
In Image classification ResNet case

**Comment by laxmareddyp** [comment]
Hi @SabinaUS,

Please let us know more details and clarity on issue to investigate further?

Please use the below template for raising any issues.

1. The entire URL of the gist file you are using
2. Describe the bug
3. Steps to reproduce
4. Expected behavior
5. Additional context
6. System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device name if the issue happens on a mobile device:
TensorFlow installed from (source or binary):
TensorFlow version (use command below):
Python version:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
