### ISSUE TITLE
what is the this two configuration difference first_stage_nms_score_threshold vs first_stage_nms_iou_threshold?

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/models#8279]
// Non max suppression score threshold applied to first stage RPN proposals.
  optional float first_stage_nms_score_threshold = 13 [default=0.0];

  // Non max suppression IOU threshold applied to first stage RPN proposals.
  optional float first_stage_nms_iou_threshold = 14 [default=0.7];
Im trying to detect the very small object from large image scale. 
I want to understand the this two features

**Comment by netanel-s** [comment]
when using RPN, you have as many proposals as anchors, that's a lot.
To filter them wisely you do two things:
only keep those which have objectness score above some threshold (first parameter),
and use NMS in order to avoid many proposals of the same object.
The relevant parameter for the NMS is the iou_threshold (second parameter), which tells it when two proposals are considered two similar, thus keep only the one with higher score.

**Comment by pkulzc** [comment]
In FasterRCNN there are two stages and two NMS. These are used to filter unreliable proposals after first stage.
