### ISSUE TITLE
Model not training well on data for multiple objects in same image

### ISSUE THREAD

**Issue by Rutvik21** [tensorflow/models#8296]
I am using tensorflow object detection to retrain for face detection using WFLW dataset. Many images contain multiple faces in a single image. And I believe that training does not perform well on these dataset, becasue I have also trained for other object in which all the images contain only 1 object per image. So what should I do ?

**Comment by pkulzc** [comment]
All our experiments and pretrained checkpoints are used to detect all objects in the image. Your performance issue could be caused by your data preparation/config/hyperparameter or other reasons. OD API do not have this limitation. (you should see that max_num_boxes is set to 100 in most configs). Please use stackoverlow to seek more advices on adjusting your model.
