### ISSUE TITLE
Question about Autoaugment contrast function

### ISSUE THREAD

**Issue by HSWang0702** [tensorflow/models#8328]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.4.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.2/7.5.0
- **GPU model and memory**: NVIDIA Quadro P4000, 8G
- **Exact command to reproduce**:

### Describe the problem
I think the calculation result is not the pixel mean value, please help!
(filename: object_detection/utils/autoaugment_utils.py)

![error](https://user-images.githubusercontent.com/25216330/77500535-4b8b7c80-6e90-11ea-97e6-63db6905376d.JPG)

**Comment by ekindogus** [comment]
Hi @HSWang0702 thanks for noticing this, you're right! We tracked the bug to the version of PIL code that we took these operations from. Due to this bug Contrast op outputs a slightly brighter image than it should, but that's the only difference. 

We will run experiments to see if results improve after fixing this bug.  We expect that the results won't change much if at all.
