### ISSUE TITLE
Question about YAMNet input 

### ISSUE THREAD

**Issue by NiborZ** [tensorflow/models#8432]
I am a first learner of YAMNet and VGGish.

When I use YAMNet/inference.py to predict different audios, I find out that all duration of audios(larger than 975ms) can be computed into features and input into the model. If there is long audio with multiple events, the inference can only give me top5 labels which describe the whole audio(which single event it belongs to).

I wanna ask why the duration can have this range(>=0.975)? What is the duration of the training input data? Is the inference result of the audio whose duration is different from the training reasonable? 

Thanks for your concern. @dpwe

**Comment by dpwe** [comment]
YAMNet is trained on 64-channel, 96-time-frame log-mel-spectrogram patches. The spectrogram frame hop is 10ms, so 96 frames spans 960ms. Because the spectrogram window is 25ms (and we don’t zero-pad the edges), it takes 975ms to get one classification output. 

When the input audio is longer than 975ms, we form successive 96 x 64 patches from the spectrogram, and get successive classification outputs. We typically advance by 10 spectrogram frames (100 ms) between each patch, but this is arbitrary. 

By the end, we have around 10 classification outputs per second of input (less a little because of fitting in the 975ms window). We can the simply average them all together, giving a vector of the events seen anywhere in the sound, or we can examine the scores’ variation across time (as in the “score-o-gram” display in the IPython notebook demo).

**Comment by fairuzsamihasaeed** [comment]
Hi, I am a new user of YAMnet model. I have a question regarding this. Does yamnet requires equal duration of audio files for training the model? Thank you
