### ISSUE TITLE
model_main.py gives lot off package issues in V2, is there any alternate file that is used for evaluation

### ISSUE THREAD

**Issue by kalpa-subbaiah** [tensorflow/models#8495]
Not able to import graph_matcher.

![image](https://user-images.githubusercontent.com/30182218/81692451-0b9e4a00-947c-11ea-916c-eb0eb2f71e76.png)

**Comment by WillCZhang** [comment]
I was suffering exactly the same issue for the last few days. They are not updating their TF APIs, and for some reason, those problems weren't fixed by running their update script https://www.tensorflow.org/guide/upgrade. I wrote a small abstracted docker image to get away with these issues, here is the link https://github.com/WillCZhang/Object-Detector, hope it helps

**Comment by tombstone** [comment]
@kalpa-subbaiah Can you confirm that you are using TF 1.15 ?
