### ISSUE TITLE
Attention OCR inference in TensorRT

### ISSUE THREAD

**Issue by Ram-Godavarthi** [tensorflow/models#8636]
Hi, I have used attention OCR to train number plate images to recognize the characters and numbers. I was successful with that part. I got some good results. Now I want to perform inference on Jetson Nano using TensorRT. I know I should Convert my model to Uff /onnx and then to TensorRT. 
But unfortunately I could not do it as there are some unsupported layers such as : FusedbatchnormV2, AddV2, Split, cast, quedeque and other 2 layers. When I convert the model to UFF, It got converted but these layers are considered as custom ops. But it’s not possible to convert to TensorRT from UfF without these unsupported layers. 

I don’t know how to write customer plugins for these layers.
Can somebody help me out with this issue. 

Thank you

**Comment by kyscg** [comment]
You can use the `trtexec` command to get the TRT file

https://github.com/NVIDIA/TensorRT/blob/master/samples/opensource/trtexec/README.md

**Comment by Ram-Godavarthi** [comment]
But when I convert my model from tensorflow to uff , it is showing unsupported operations. How to avoid this issue??

**Comment by xavigibert** [comment]
Hi Ram. Thank you for your interest in using the Attention OCR model. I have zero experience with the TensorRT environment, so I can't give you support. One possible issue is that you may need to use device placement during graph construction. For example if you enclose the model creation code with "with tf.device('/TPU:0'):" the created graph would contain only operations that are compatible with TPU. However, I don't know if it possible to place the graph on the Jetson Nano, since you need to export to TensorRT. In that case, the only solution that I see is doing a graph rewrite. A graph rewrite means replacing the names of the operation inside the SavedModel with the compatible ones (like FusedbatchnormV2 with Fusedbatchnorm or whatever equivalent sequence of operations supported by TensorRT). I don't have experience with that approach either, but I see that trt_convert.py is a graph rewrite tool for TensorRT: https://github.com/tensorflow/tensorflow/tree/r1.15/tensorflow/python/compiler/tensorrt. You may want to try doing the graph rewrite and then convert it to UFF. Just a guess.

**Comment by xavigibert** [comment]
I'm closing the issue for now, since this is a research model and this is a very specific request.
