### ISSUE TITLE
/models/resnet: tf.select & tf.concat issues

### ISSUE THREAD

**Issue by AliMiraftab** [tensorflow/models#874]
## /models/resnet/

Two issues with version: '0.12.head' - bazel installation:
1. tf.concat(concat_dim, values) which can be solved by tf.concat_v2(values , concat_dim) 
2. AttributeError: 'module' object has no attribute 'select'

Can you pleas help to solve the latter?

**Comment by jart** [comment]
Thanks for reaching out. Most of the stuff in this repository is community maintained and supported. I'll let @panyx0718 weigh in since he wrote models/resnet.

**Comment by Iflier** [comment]
Today, I also have trouble with "Attribute :  'module' object has no attribute 'select'", sincerely hope to be able to solve earlier.Many thanks.

**Comment by jart** [comment]
Right now we're going through some 1.0 migration pains which are mostly documented here: https://github.com/tensorflow/tensorflow/releases. Any help you guys can offer in helping to keep this models code up to date would be a huge help, since this is mostly community contributed and supported. Although we've also been doing our best to update this while doing our refactorings. It's just difficult because a lot of this stuff, such a resnet, doesn't have unit tests.

**Comment by karmel** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
