### ISSUE TITLE
ModuleNotFoundError: No module named 'delf'

### ISSUE THREAD

**Issue by waelkht** [tensorflow/models#8773]
I got the following error while running the model training script from the tutorial

Traceback (most recent call last):
  File "models/research/delf/delf/python/training/train.py", line 35, in <module>
    from delf.python.training.datasets import googlelandmarks as gld

**Comment by andrefaraujo** [comment]
did you install the DELF library properly? https://github.com/tensorflow/models/blob/master/research/delf/INSTALL_INSTRUCTIONS.md

In other words, when you run

```
python3 -c 'import delf'
```

does it return silently?

**Comment by waelkht** [comment]
I think the original error comes from the following:
train.oy use aggregation_config_pb2 but the file name in protos is aggregation_config. this wouls be a version problem in the  install_delf.sh ?
Traceback (most recent call last):
  File "models/research/delf/delf/python/training/train.py", line 35, in <module>
    from delf.python.training.datasets import googlelandmarks as gld
  File "/kaggle/working/models/research/delf/delf/__init__.py", line 21, in <module>
    from delf.protos import aggregation_config_pb2
ImportError: cannot import name 'aggregation_config_pb2' from 'delf.protos' (/kaggle/working/models/research/delf/delf/protos/__init__.py)

**Comment by andrefaraujo** [comment]
Sorry, you didn't respond my question above. It sounds like you are trying to run training without properly installing the library.

It's clear you didn't install the library properly because the file becomes named aggregation_config_pb2 *after* you compile the protos: https://github.com/tensorflow/models/blob/master/research/delf/INSTALL_INSTRUCTIONS.md#protobuf
