### ISSUE TITLE
object_detection_tutorial.ipynb not found

### ISSUE THREAD

**Issue by mohammed-ab99** [tensorflow/models#8919]
Dear all,
I am using Tensorflow latest version for the Object Detection API. I followed all installation steps and explanations on Github and Youtube and everything worked fine with only one problem. There should be a file named object_detection_tutorial.ipynb in Tensorflow1\models\research\object_detection, but I cant find it I dont know why. I have looked almost every where to solve this issue but I didnt solve it. 
Is there a place where I can download the file separately? or I missed something ?

**Comment by khanx169** [comment]
The notebook was updated and moved [here](https://github.com/tensorflow/models/tree/master/research/object_detection/colab_tutorials). Beware though, if you are following tutorials/videos from more than a few months ago and are using TF1, these new notebooks won't work for you. Remarkably, instead of maintaining TF1 colabs/docs/scripts, etc, they got upgraded to TF2 for the most part.

**Comment by aleehamza25** [comment]
is there any updated tutorial for updated notebooks?
