### ISSUE TITLE
EfficientDet on tensorflow-gpu 1.15

### ISSUE THREAD

**Issue by nicholasguimaraes** [tensorflow/models#8968]
Hello world, 

I use tensorflow-gpu 1.15 but I’m interested on training a pre trained model of EfficientDet, do I need to create a virtual env and install tf2? 

Does Tensorflow 2 run on GPU?

**Comment by ravikyram** [comment]
@nicholasguimaraes 

Yes you can create virtual environment and install TF 2.
TF 2 will run on GPU as well.Please, refer https://www.tensorflow.org/guide/gpu?hl=en

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

Thanks!

**Comment by nicholasguimaraes** [comment]
Thank you @ravikyram

**Comment by ravikyram** [comment]
@nicholasguimaraes 

Please close this thread if it solves your question.Also, refer this[ link](https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817),might be useful to you. Thanks!
