### ISSUE TITLE
DELF: Rationale behind two-step training 

### ISSUE THREAD

**Issue by NHGJem** [tensorflow/models#9068]
[![Paper](http://img.shields.io/badge/paper-arXiv.1612.06321-B3181B.svg)](https://arxiv.org/abs/1612.06321)

In the above paper, it was mentioned that "While the feature representation and the score function can be trained jointly by backpropagation, we found that this setup generates weak models in practice."

Looking at [train.py](https://github.com/tensorflow/models/blob/master/research/delf/delf/python/training/train.py), line 237 mentions that unifying the backpropagation was a TODO.

Could I ask for clarification on if joint training still causes "weak models" and what it specifically means (e.g. poor Recall)? Or if the issue with joint training as been fixed and can be performed, but just hasn't been updated yet?

**Comment by andrefaraujo** [comment]
There are a few things going on here.

In the DELF paper, we indeed proposed to train the backbone and attention networks separately, which led to much better performance in terms of precision/recall on the Google Landmarks dataset, compared to training everything jointly (as your quote mentions).

Recently, with the DELG paper, one thing we were able to do is to design a procedure that makes it possible to train everything jointly, which simplifies things. The current implementation of train.py is one version of this joint training, using two separate forward/backward passes (one for the backbone, one for the attention). The TODO in there is for implementing this with a single forward/backward pass, instead of two of them as currently done.
