### ISSUE TITLE
Advantages of saved model (.pb) format ? Not able to save transformer model to saved model.

### ISSUE THREAD

**Issue by legacyai** [tensorflow/models#9114]
Before commenting the bug, would love to hear the performance benefits of saved_model formats. 

I have already opened one bug about saving models ( transformer ) into saved model .pb format. Before I spent time to fix it locally, can anyone help me here. Will saved model has any performance benefits comparing to other approaches like ```tf.keras.Model / Layer``` object and loaded from checkpoints. 

Or is saved_model is the most optimized ```( @tf.function )``` version of the model call ?

Please comment. Thanks.

**Comment by saberkun** [comment]
Hi, the savedmodel format is for TF2 default model serialization. I don't know what's the advantages of it comparing to H5 in terms of model saving. Add keras team here @k-w-w 

The transformer model itself is hard to save by model.save() because of the beam search decoding part.
We added a test case to demonstrate how to save it for serving. https://github.com/tensorflow/models/blob/master/official/nlp/transformer/transformer_test.py#L67
