### ISSUE TITLE
there has the bug when use keras

### ISSUE THREAD

**Issue by ImMrMa** [tensorflow/models#9193]
https://github.com/tensorflow/models/blob/f2c76e41f668b30cc6714ed8a866c07cc2f2275a/official/nlp/modeling/networks/bert_encoder.py#L215
The right code should be:
```
def get_config(self):
    base_config = super(TransformerEncoder, self).get_config()
    return dict(list(base_config.items()) + list(self._config_dict.items()))
```
tf.keras.models.load_model(
    filepath, custom_objects=None, compile=True, options=None
)
The api should work fine with this code rewrite

**Comment by chenGitHuber** [comment]
Hi

Thanks for proposing this fix. We added a test in [this commit](https://github.com/tensorflow/models/commit/c2d3fdc0c718e4e11a0610e4b03d4e56640271ff), which verifies that tf.keras.models.load_model() API works with bert_encoder.py now.

This was fixed by the following commit from tensorflow-keras a while ago:
https://github.com/tensorflow/tensorflow/commit/311c8d233bd040df18d7815491fce4f96ea78817
