### ISSUE TITLE
hardware requirements

### ISSUE THREAD

**Issue by epsilon11101** [tensorflow/models#9212]
Hello everyone I'm recently decided to use the TF2 model zoo, but I have a question,  which are the hardware requirements for running the models with a batch size of, 64, etc?
Thanks!

**Comment by ravikyram** [comment]
@epsilon11101 

Please, refer [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements) ,[link1](https://timdettmers.com/2018/12/16/deep-learning-hardware-guide/).

This question is better asked on StackOverflow since it is not a bug or feature request. Thanks!

**Comment by epsilon11101** [comment]
thanks @ravikyram  and sorry!
