### ISSUE TITLE
SyntaxNet installation on OS X  

### ISSUE THREAD

**Issue by negacy** [tensorflow/models#926]
Could someone point me to the right version of SyntaxNet and bazel that works on OS X? I tried bazel 2.2, 2.2b. 0.3, 0.3.1 and 0.4.3 but I couldn't install it yet. Three days passed but no solution. I have posted my errors [here](https://github.com/tensorflow/models/issues/657#issuecomment-273297854) and [here](https://github.com/bazelbuild/bazel/issues/2374). Any help  is appreciated. Thanks.

**Comment by asimshankar** [comment]
We've been getting a bunch of issues lately about compatibility with tensorflow/models and tensorflow/tensorflow, in light of all the 1.0 refactoring and API changes.

Unfortunately, many models in tensorflow/models are community maintained.
Syntaxnet needs some updates. As you pointed out, #902 is tracking them.

Closing this out as a duplicate, since I don't believe this is OS X specific.
@calberti may want to chime in.
