### ISSUE TITLE
Bert checkpoint conversion tf1.x to tfhub2.x

### ISSUE THREAD

**Issue by pretidav** [tensorflow/models#9336]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/nlp/bert/tf2_encoder_checkpoint_converter.py
https://github.com/tensorflow/models/blob/master/official/nlp/bert/export_tfhub.py

## 2. Describe the bug

Starting from a Tf1.X bert checkpoint (from https://github.com/google-research/bert) I tried to convert it to a Tf2.x checkpoint using tf2_encoder_checkpoint_converter.py. After this operation using export_tfhub.py I wanted to convert it again into a tfhub2.x format. 
I get errors from .assert_existing_objects_matched() in checkpoint restoration before the tfhub export. 
WARNING:tensorflow:Unresolved object in checkpoint: (root).bert_model.ckpt 
(same for each layer)
## 3. Steps to reproduce

Download a tf1.x checkpoint from from https://github.com/google-research/bert, run tf2_encoder_checkpoint_converter.py and then export_tfhub.py with appropriate file path at each step. 

## 4. Expected behavior

At the end of this (double) conversion from checkpoint tf1.x -> tfhub2.x the saved model should be consistent with the ones downloadable from https://github.com/tensorflow/models/tree/master/official/nlp/bert .

## 5. Additional context

I tried with both master (nightly) and v2.3.0 (tf2.3) branches obtaining same results.

## 6. System information

- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from source
- TensorFlow version 2.3.0 and Nightly (tried both)
- Python version 3.6 and 3.8
- CUDA/cuDNN version 10.1
- GPU model and memory V100

**Comment by saberkun** [comment]
@chenGitHuber 
This is because the export_tfhub.py tf.train.Checkpoint is mismatched.
https://github.com/tensorflow/models/blob/master/official/nlp/bert/tf2_encoder_checkpoint_converter.py#L52
The root object is encoder but https://github.com/tensorflow/models/blob/master/official/nlp/bert/export_tfhub.py#L82 is model. This is because of a recent commit.
Can you try to change it to 'encoder' as tf.train.Checkpoint root object?
We will fix this soon. Welcome to have a PR too!
