### ISSUE TITLE
Issue when using mask_rcnn_inception_resnet_v2_atrous_coco_2018_01_28 model

### ISSUE THREAD

**Issue by shvamabps** [tensorflow/models#9603]
![Screenshot from 2021-01-03 17-39-52](https://user-images.githubusercontent.com/37547983/103478158-b2a86b00-4dea-11eb-89e3-1aea09f72d01.png)

Kindly explain the reason as to why the model now downloaded doesn't work the way it should've.

**Comment by ravikyram** [comment]
@shvamabps 

Please, fill [issue template.](https://github.com/tensorflow/models/issues/new/choose)
Please, share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by shvamabps** [comment]
@ravikyram  this is the url [https://colab.research.google.com/github/tensorflow/models/blob/master/research/object_detection/colab_tutorials/object_detection_tutorial.ipynb#scrollTo=vQ2Sj2VIOZLA](url)

here the last part of the code responds this way and it is precoded in the tf2.x Object Detection API Jupiter notebook

**Comment by kirisakow** [comment]
@shvamabps In cell 24, run  

```
masking_model.signatures['serving_default'].output_shapes
```

instead of 

```
masking_model.output_shapes
```

**Comment by kirisakow** [comment]
# There is another issue concerning the masking model part of that notebook

`TypeError: Cannot interpret 'tf.uint8' as a data type` occurs while running the `show_inference` function for `masking_model`. 

The `show_inference` function calls the `run_inference_for_single_image` function which, in case of the `masking_model`, also calls the `utils_ops.reframe_box_masks_to_image_masks` function.

The latter expects the first of its parameters, `box_masks`, to be “A tensor of size [num_masks, mask_height, mask_width]” (see `object_detection/utils/ops.py:834`) so that it can read the value of the `box_masks.dtype` attribute (see `object_detection/utils/ops.py:850`).

Only what the `utils_ops.reframe_box_masks_to_image_masks` function receives as the `box_masks` parameter is not a tensor object but a `TensorShape([None, None, 33, 33])` object. Hence the error, I guess.

**Comment by jvishnuvardhan** [comment]
@shvamabps Is this still an issue for you. Can you check [this tutorial](https://tfhub.dev/tensorflow/faster_rcnn/inception_resnet_v2_640x640/1) and this [colab](https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_object_detection.ipynb).

Some issue in getting model outputs (could be some issue with input signature or something else). Thanks

**Comment by shvamabps** [comment]
Let me check and get back to you @jvishnuvardhan

**Comment by jvishnuvardhan** [comment]
@shvamabps Thanks for confirming. I will close this issue as this was resolved.

Please feel free to reopen the issue or create a new issue with a standalone code if the issue persists with a new TF version. Thanks!
