### ISSUE TITLE
Is translate model multi GPU parallelized ?

### ISSUE THREAD

**Issue by aronayne** [tensorflow/models#970]
/tensorflow/models/tree/master/tutorials/rnn/translate

Is translate parallelized  for multi GPU ?

[Searching](https://github.com/tensorflow/models/search?p=4&q=with+tf.device&utf8=%E2%9C%93) 'with tf.device' on tensorflow/models repo does not return any code for translate model.

Ref for using 'with tf.device' to enable multi GPU : https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/5_MultiGPU/multigpu_basics.ipynb

**Comment by jmchen-g** [comment]
The link seems to show the following instead in the end:
print "Single GPU computation time: " + str(t2_1-t1_1)
print "Multi GPU computation time: " + str(t2_2-t1_2)
Single GPU computation time: 0:00:11.833497
Multi GPU computation time: 0:00:07.085913

I believe such profiling is not giving you right comparison because of the initial over head...

**Comment by zheng-xq** [comment]
Doesn't seem so. Adding @nealwu to be sure.

**Comment by nealwu** [comment]
From what I can tell, this model doesn't support multiple GPUs. @lukaszkaiser is working on a new version of the model, but it may or may not include support for this (I don't know).
