### ISSUE TITLE
How could I finetune custom data?

### ISSUE THREAD

**Issue by stereomatchingkiss** [tensorflow/models#972]
This project show us easy way to finetune pretrained models on 4 datasets, flowers, mnist, cifar10 and imageNet, But what if we want to finetune our custom data? Do you have any suggestions?Like
 clear tutorials about this part? Or I have to read through your source codes to figure out how to do it?

**Comment by ogail** [comment]
You need to convert the custom dataset into tfrecords, develop data provider, update slim src code to have your dataset provider. Checkout [this tutorial](https://github.com/tensorflow/models/tree/master/inception#how-to-fine-tune-a-pre-trained-model-on-a-new-task).

**Comment by TheodoreGalanos** [comment]
Hello, thank you for sharing the tutorial!

As a beginner in the ML field and a new user of tensorflow I have found that there is a (somewhat unexpected) difficulty in getting help on the first steps, usually the ones experienced users hardly consider, rather than actually getting model architectures and such. 

The latter is the amazing result of this incredibly open source community that is ML. The former is simply, as mentioned above, a result of the high expertise involved in most users that not only practice but develop production models.

I know this is probably the wrong place to say this (I was planning to write in stackoverflow) but a simple, step-by-step tutorial of running a DL network with tensorflow using a completely custom dataset would be invaluable to new users in the field.

I hope someone finds this comment useful.

Kind regards,
Theodore.

**Comment by Nothing190** [comment]
I found this [tutorial](https://agray3.github.io/2016/11/29/Demystifying-Data-Input-to-TensorFlow-for-Deep-Learning.html) .  It helped me to get some insides how to create my own tfRecord file.

But I got stuck at line 228 where the training begins...

**Comment by stereomatchingkiss** [comment]
Thanks for the efforts you put into this library. I figured out how to transfer data into tfRecord file, trained a new model from scratch, but never find a complete tutorial of how to finetune on your own data set, most of the tutorials are more like advertise(tensorflow is super good) rather than a step by step tutorials showing you how to write your own codes to finetune trained models like [keras ](https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html) did. The only way to do it is reading the source codes and figure it out by yourself because the documents of finetuning is almost helpless unless you are very familiar to tensorflow.

I am surprise with the lack of documents/blogs on finetune, it looks like only a few of the experts of tensorflow know how to finetune trained models by codes even tensorflow have such a big communities. 
The lacks of documents means 

1 : most of the users do not know how to do it too
2 : this problem is too trivial to mention

The one and only way to figure it out is read through the source codes, this is too expert friendly.
