### ISSUE TITLE
how to get the NDCG of the NCF model?

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/models#9734]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this feature has not been requested already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/official/recommendation

## 2. Describe the feature you request

I just want the NDCG of the metrics, have seen the ndcg in the [compute_top_k_and_ndcg](https://github.com/tensorflow/models/blob/master/official/recommendation/neumf_model.py#L389) and  [metric_fn] (https://github.com/tensorflow/models/blob/852e098aba39cdc2611118061d1402f01a9d2b44/official/recommendation/neumf_model.py#L373) but not in the results
`I0218 14:25:29.260130 139715392775936 my_main5_4.py:881] Done eval epoch 14, hit_rate=0.581`

Could you please help me?
thx

**Comment by ucasiggcas** [comment]
of course we can refer the old closed [issue](https://github.com/tensorflow/models/issues/9618)

**Comment by saberkun** [comment]
How about https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/keras/metrics.py

**Comment by ucasiggcas** [comment]
@saberkun 
so how to use the metrics in NCF model ?

**Comment by songzy12** [comment]
The reason should be this:

https://github.com/tensorflow/models/blob/e39f2477ac207b2d0e15a8d9f172e07e76799eb0/official/recommendation/ncf_keras_main.py#L48-L51

You can see ndcg is omitted as the second return value of `compute_top_k_and_ndcg`, maybe you can just check these lines to something like
```
  _, ndcg, metric_weights, _ = neumf_model.compute_top_k_and_ndcg(
      logits, dup_mask, match_mlperf)
  metric_weights = tf.cast(metric_weights, tf.float32)
  return ndcg, metric_weights
```

**Comment by laxmareddyp** [comment]
Hi @ucasiggcas ,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.
The TF models official team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tf-models-official/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/models/releases/tag/v2.13.1) to stay up to date with the latest developments which are happening in the TF models official space.
