### ISSUE TITLE
latest_checkpoint returns None even though checkpoint file exists.

### ISSUE THREAD

**Issue by ricking06** [tensorflow/models#974]
## Please let us know which model this issue is about (specify the top-level directory)
Its im2txt model 

 checkpoint_path = tf.train.latest_checkpoint(checkpoint_path) is giving None even though the checkpoint file is present.

im using pretrained model from @psycharo from #466 .

the checkpoint file is inside im2txt/model/train/

**Comment by concretevitamin** [comment]
This is clearly not a TensorFlow core/Saver issue; I suspect something's wrong with the pretrained model.  Also, check if a file named `checkpoint` is under your checkpoint dir (and if it, if it contains the right content).

**Comment by ricking06** [comment]
i passed the full path of checkpoint file instead of its directory and it worked.

**Comment by FarnazJazayeri** [comment]
I had the very same problem with my code. Then I figured out that the checkpoint file was saved with .txt format. I renamed the 'checkpoint.txt' to 'checkpoint' and it worked!!

**Comment by landwash** [comment]
I used a pretrained model and I found that the path in the file "checkpoint" is not correct. changing the model path in this file should work

**Comment by zengsn** [comment]
@landwash what changes did you make? thanks

**Comment by landwash** [comment]
I used a pretrained model provided by others, and I opend the file
"checkpoint" and found that the paths in it was wrong.
After changing the paths to mine, the code started to work.

Shaoning Zeng <notifications@github.com> 于2018年5月31日周四 下午4:28写道：

**Comment by zengsn** [comment]
@landwash OK, thank you.

**Comment by kingspp** [comment]
Issue still persists in Tensorflow 1.8.0.

Ex:

```python
# Below path consists of checkpoint files.

# Valid Path:
/tmp/fs/model/flow/runner/saves/dl/

# Invalid Path:
/tmp/fs//model/flow///runner/saves/dl//
```

Since unix resolves path containing redundant '/', Tensorflow internally should be able to resolve redundant '/', instead of throwing Error.

**Comment by AbdelsalamHaa** [comment]
I'm getting the same error but I don't have any file called cheickpoint though , I have only these files
![image](https://user-images.githubusercontent.com/35866217/48818725-557ff700-ed01-11e8-99de-3b029f4c83b2.png)
 is that means I have to retrain the model again or how

**Comment by SMHendryx** [comment]
```
os.path.normpath(path)
```
resolves the issue noted by @kingspp

**Comment by Storyyeller** [comment]
I have an issue where `tf.train.latest_checkpoint` works on one directory, but if I copy and rename that directory, it will return None for the copy, even though the directory contains **the exact same files**.

**Comment by jpgard** [comment]
Wanted to follow up with a comment, and a request for more explanation if someone is able to provide it.

I also experience this issue, but only when attempting to load a checkpoint, which was written using a `tf.train.CheckpointManager`, from a different location where the model was originally trained. It isn't entirely clear why this process fails, but as @Storyyeller mentioned, it seems that somehow the path to the checkpoints is encoded somewhere (although it doesn't seemt to be in the `checkpoint` file itself. 

Could someone, either from TensorFlow or otherwise, explain what's going on here, perhaps providing some information about the structure of the checkpoint files and how one might copy checkpoint files to another location and use them to restore the model?
