### ISSUE TITLE
tensorflow font size detection!

### ISSUE THREAD

**Issue by rj0812** [tensorflow/models#9820]
I am new in ML and learning tensorflow. I want to convert my pdf to audiobook. To remove extra text like image markings page numbers from my audio book. I want to detect the font size of this unwanted text and then using python I want to convert the the rest of the text to audio book, I don't want to run cloud functions or cloud based solutions. Please help!

**Comment by chandyalex** [comment]
Hi @rj0812  
The idea of detecting font size using deep learning models has a lot of challenges, First of all, the input size of the deep learning model is fixed in most of the cases:
To understand the input size of the model please refer following links
https://ai.stackexchange.com/questions/2008/how-can-neural-networks-deal-with-varying-input-sizes
https://towardsdatascience.com/ultimate-guide-to-input-shape-and-model-complexity-in-neural-networks-ae665c728f4b


Also, there are some tutorials for text recognition using TensorFlow.
https://towardsdatascience.com/build-a-handwritten-text-recognition-system-using-tensorflow-2326a3487cd5
https://github.com/sh21kang/OCR_V1

So What I would suggest is, instead of going for developing a model which is capable of predicting the size of the text, you can define the region of interest to convert text to audio and perform the model on that specific area. Also, you can compare the relative pixel values of the detected character and verify them with the reference size of the character.

Look for some good ideas and try to hack it .
Kudos

**Comment by saikumarchalla** [comment]
@rj0812  Could you please provide the top level directory of the model?
