### ISSUE TITLE
Where is the "im2txt"

### ISSUE THREAD

**Issue by whqwill** [tensorflow/models#9846]
I can not find the "im2txt”. Where is it?

**Comment by Srikeshram** [comment]
'im2txt' model is not implemented in the Tensorflow Model Garden....If you want , Kindly raise the issue with the 
**(helpwanted: Paper Implementation)** tag.....

**Comment by ymodak** [comment]
The im2txt model used to be part of tensorflow/models/research till 1.12 . It can be found here https://github.com/tensorflow/models/tree/r1.12.0/research/im2txt
However you may also find this [image captioning tutorial](https://www.tensorflow.org/tutorials/text/image_captioning) on tensorflow website more helpful since its a later version.
