### ISSUE TITLE
how to get the negtive item for a user of NCF model ?

### ISSUE THREAD

**Issue by ucasiggcas** [tensorflow/models#9886]
hi,dear
how to get the negtive sample items for a user of the NCF  model, if I want to modify the sample function , how to deal with it ?
Now my dataset  label is click or not, and how to  correct ?
thx

**Comment by ucasiggcas** [comment]
NCF official is [here](https://github.com/tensorflow/models/tree/master/official/recommendation)

**Comment by laxmareddyp** [comment]
Hi @ucasiggcas,

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow-models) and [TensorFlow Forum](https://discuss.tensorflow.org/c/research-models/26) since it is not a bug or feature request. There is also a larger community that reads questions there.

Thanks
