### ISSUE TITLE
 def _get_postprocess_fn returns dummy which causes export_tflite_graph_lib_tf2 returns non-working model.

### ISSUE THREAD

**Issue by tungnat97** [tensorflow/models#9887]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the bug

I don't really know, but my saved_model converted by export_tflite_graph_tf2.py have 4 one-dimension zero outputs. Which I think is caused by _get_postprocess_fn in export_tflite_graph_lib_tf2.py;
```
def _get_postprocess_fn(self, num_anchors, num_classes):
        # There is no TF equivalent for TFLite's custom post-processing op.
        # So we add an 'empty' composite function here, that is legalized to the
        # custom op with MLIR.
        @tf.function(
            experimental_implements=self.postprocess_implements_signature())
        # pylint: disable=g-unused-argument,unused-argument
        def dummy_post_processing(box_encodings, class_predictions, anchors):
            boxes = tf.constant(0.0, dtype=tf.float32, name='boxes')
            scores = tf.constant(0.0, dtype=tf.float32, name='scores')
            classes = tf.constant(0.0, dtype=tf.float32, name='classes')
            num_detections = tf.constant(
                0.0, dtype=tf.float32, name='num_detections')
            return boxes, classes, scores, num_detections

        return dummy_post_processing
```

**Comment by srjoglekar246** [comment]
@tungnat97 That is intended behavior, if you want to arrive at a TFLite model (not otherwise). The dummy `tf.function` has an annotation (`experimental_implements=self.postprocess_implements_signature()`) that tells the TFLite converter to replace that dummy function with the TFLite custom NMS op. We do this to optimize the post-processing on-device. See the process mentioned [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md); also note that you need TF >= 2.4 for this whole process to work.
